// KPSS Türkçe Authentic Questions Bank (150 Questions - 5 Subcategories, 3 Levels, 10 Q per level)
// Category: 4 (Türkçe)

module.exports = function (addQ) {
    // -------------------------------------------------------------------------
    // Subcat 18: Sözcük ve Cümlede Anlam
    // -------------------------------------------------------------------------
    // Level 1: Temel Anlam
    addQ(4, 18, 1, 'Aşağıdaki altı çizili sözcüklerden hangisi mecaz anlamda kullanılmıştır?', '"Bu soğuk davranışların beni gerçekten çok kırdı."', '"Sıcak çayı bardağa koydu."', '"Kapının kolu kırılınca içeride kaldık."', '"Kuşlar gökyüzünde kanat çırpıyordu."', '"Karanlık odada göz gözü görmüyordu."', 'A', '"Soğuk davranış" ve "kırılmak" ifadeleri duygusal incinmeyi anlatarak gerçek anlamından tamamen uzaklaşmış mecazdır.');
    addQ(4, 18, 1, '"Burnundan kıl aldırmamak" deyiminin anlamı aşağıdakilerden hangisidir?', 'En küçük bir eleştiriye bile tahammül edememek, çok kibirli ve huysuz olmak', 'Çok titiz olmak', 'Korkusuz olmak', 'Hastalığa yakalanmak', 'Burnu büyük olmak', 'A', 'Kibirli, alıngan ve uyarılara tahammülü olmayan kişiler için kullanılan yaygın bir deyimdir.');
    addQ(4, 18, 1, 'Aşağıdaki cümlelerin hangisinde "neden-sonuç" (sebep-sonuç) ilişkisi vardır?', 'Sınava iyi hazırlandığı için yüksek puan aldı.', 'Sınavı kazanmak için gece gündüz çalışıyor.', 'Hava güzel olursa pikniğe gideriz.', 'Ders çalışırken müzik dinlemeyi sever.', 'Kitap okumak insanı zenginleştirir.', 'A', '"Yüksek puan alması" sonuç, "iyi hazırlanmış olması" ise bunun gerçekleşmiş nedenidir.');
    addQ(4, 18, 1, 'Aşağıdaki cümlelerin hangisinde "amaç-sonuç" ilişkisi söz konusudur?', 'Yazar, okurla doğrudan iletişim kurmak amacıyla günlük türünü seçmiştir.', 'Hava karardığından dolayı fenerleri yaktık.', 'Düştüğü için bacağı alçıya alındı.', 'Trafik sıkışınca toplantıya geç kaldı.', 'Sular kesilince yemek yapamadı.', 'A', '"Günlük türünü seçmesi" sonuç, "okurla doğrudan iletişim kurmak" ise henüz ulaşılmak istenen hedeftir.');
    addQ(4, 18, 1, '"Öznel anlatım" kişisel duygu ve beğenileri içerir, kanıtlanamaz. Aşağıdakilerden hangisi öznel bir cümledir?', 'Yazarın son romanı okuru adeta büyüleyen, sıcacık bir üsluba sahip.', 'Yazar bu kitabında 12 öyküye yer vermiştir.', 'Roman toplam 320 sayfadan oluşmaktadır.', 'Eser ilk baskısını 2022 yılında yapmıştır.', 'Kitapta geçen olaylar Kurtuluş Savaşı yıllarını anlatır.', 'A', '"Büyüleyen" ve "sıcacık" ifadeleri kişiden kişiye değişen kanıtlanamaz öznel yargılardır.');
    addQ(4, 18, 1, '"Ayağını yorganına göre uzat" atasözünün temel öğüdü nedir?', 'Giderlerini ve harcamalarını gelirine, bütçene uydur', 'Boyuna göre yatak seç', 'Gereksiz yere borçlan', 'Zamanı tasarruflu kullan', 'Tutumlu olmak cimriliktir', 'A', 'Kişinin mali imkanlarını aşan harcamalardan kaçınmasını öğütleyen atasözüdür.');
    addQ(4, 18, 1, 'Aşağıdaki cümlelerin hangisinde bir "varsayım" (farz etme) anlamı vardır?', 'Diyelim ki bu sınavdan yüz aldın, hedefine ulaştın mı?', 'Yarın kesinlikle oraya geleceğim.', 'Büyük ihtimalle treni kaçırmıştır.', 'Keşke ben de sizinle gelseydim.', 'Böyle bir hatayı asla beklemiyordum.', 'A', '"Diyelim ki, tut ki, farz edelim ki" kalıpları olmamış bir durumu bir an için olmuş kabul eden varsayımdır.');
    addQ(4, 18, 1, 'Aşağıdaki cümlelerin hangisinde "hayıflanma" (kendi yapmadığı bir şeyden dolayı üzülme) anlamı vardır?', 'Keşke gençliğimde daha çok kitap okusaydım.', 'Bana neden haber vermediniz?', 'Bu havada dışarı çıkılmaz.', 'Bütün işleri tek başıma yaptım.', 'Yine geleceğini tahmin etmiştim.', 'A', 'Kişinin geçmişte kaçırdığı bir fırsattan veya yapmadığı bir şeyden dolayı duyduğu pişmanlığa hayıflanma denir.');
    addQ(4, 18, 1, 'Aşağıdaki cümlelerin hangisinde "örtülü anlam" vardır?', 'Bu yılki tatile Ahmet de bizimle gelecek.', 'Güneş doğudan doğar.', 'Ankara Türkiye\'nin başkentidir.', 'Bugün hava yağmurlu.', 'Kitap masanın üzerinde duruyor.', 'A', '"Ahmet de gelecek" cümlesinde "de" bağlacı Ahmet dışında başkalarının da tatile geleceği örtülü anlamını taşır.');
    addQ(4, 18, 1, 'Aşağıdaki cümlelerin hangisinde "kanıksama" (zamanla bir duruma alışma, kabullenme) anlamı vardır?', 'Sürekli eleştirilmeye artık hiç ses çıkarmıyor, aldırmıyordu.', 'Yarın erkenden yola çıkacağız.', 'Bu kadarını beklemiyordum.', 'Yemek çok lezzetli olmuş.', 'Bana neden yalan söyledin?', 'A', 'Kötü veya rahatsız edici bir duruma zamanla alışıp tepki göstermez hale gelmeye kanıksama denir.');

    // Level 2: Orta Düzey
    addQ(4, 18, 2, 'Aşağıdaki cümlelerin hangisinde "kinaye" (hem gerçek hem mecaz anlama gelecek şekilde mecazı kastetme) sanatı vardır?', '"Bırak beni, sana kapım her zaman açıktır."', '"Gözleri adeta bir elmas gibi parlıyordu."', '"Gül dikensiz olmaz."', '"Bu yükü taşımaya gücüm kalmadı."', '"Ağaçlar ilkbaharda çiçek açar."', 'C', '"Gül dikensiz olmaz" sözünde hem gerçek gülün dikeni hem de her güzel şeyin bir kusuru/zahmeti olduğu mecaz anlamı kastedilmiştir.');
    addQ(4, 18, 2, '"Ad aktarması" (Mecaz-ı Mürsel), benzetme amacı gütmeden bir sözcüğün başka bir sözcük yerine kullanılmasıdır. Hangisinde ad aktarması vardır?', 'Bütün salon konuşmacıyı ayakta alkışladı.', 'Gözlerinden bir damla yaş süzüldü.', 'Güneş dağların ardından doğuyordu.', 'Rüzgar pencereleri sertçe çarptı.', 'Kitaplığın rafları toz içindeydi.', 'A', '"Salon" sözcüğü mekan adı olup salondaki "insanlar" kastedilmiştir.');
    addQ(4, 18, 2, 'Aşağıdaki cümlelerin hangisinde bir "ön yargı" (peşin hüküm) cümlesidir?', 'Bu yönetmenin filmi ne yaparsa yapsın kesinlikle tutmayacak.', 'Film dün sinemalarda vizyona girdi.', 'Yönetmen üçüncü ödülünü kazandı.', 'Oyuncuların performansı çok iyiydi.', 'Biletler ilk günden tükendi.', 'A', 'Sonuç henüz belli olmadan olumlu veya olumsuz peşin bir yargıda bulunulmuştur.');
    addQ(4, 18, 2, 'Aşağıdaki cümlelerin hangisinde "üslup" (anlatım tarzı) ile ilgili bir yargı bildirilmiştir?', 'Yazar, kısa ve devrik cümlelerle akıcı ve coşkulu bir anlatım yakalamıştır.', 'Yazar bu romanında Anadolu köylüsünün dramını işliyor.', 'Eser üç ana bölümden meydana gelmektedir.', 'Kitapta köyden kente göç konusu ele alınmış.', 'Romanın kahramanı bir öğretmendir.', 'A', 'Yazarın "nasıl anlattığı" (dil, cümle yapısı, akıcılık) üsluptur; "ne anlattığı" ise içeriktir.');
    addQ(4, 18, 2, 'Aşağıdaki cümlelerin hangisinde "içerik" (konu) ile ilgili bilgi verilmiştir?', 'Şair bu şiirinde yalnızlık ve gurbet temalarını derinlemesine işlemiştir.', 'Dili oldukça sade ve anlaşılırdır.', 'Kelimeleri seçerken çok titiz davranmıştır.', 'Ahenkli ve ritmik bir ses düzeni vardır.', 'Kısa mısralarla yoğun bir etki bırakmıştır.', 'A', 'Eserde neden bahsedildiği, hangi temanın ele alındığı eserin içeriğidir.');
    addQ(4, 18, 2, 'Aşağıdaki cümlelerin hangisinde "dolaylama" örneği vardır?', 'Kara kıta, yıllarca süren sömürgeciliğin izlerini hala silemedi.', 'Güneş batarken kızıllaştı.', 'Akşam serinliği çöktü.', 'Sular yavaş yavaş çekildi.', 'Rüzgar hafif hafif esiyordu.', 'A', '"Afrika" yerine iki sözcükle "Kara kıta" denmesi tipik bir dolaylamadır (Yavru vatan, Derya kuzusu, File bekçisi).');
    addQ(4, 18, 2, 'Aşağıdaki cümlelerin hangisinde "güzel adlandırma" yapılmıştır?', 'O amansız hastalığa yakalanan hastalar için yeni bir tedavi bulundu.', 'Gözleri çok iyi görüyordu.', 'Kuşlar yuvalarına döndü.', 'Çocuklar bahçede oynuyordu.', 'Ağaçlar çiçek açtı.', 'A', '"Kanser" veya "verem" yerine kulağa daha hafif gelen "amansız hastalık" ifadesi güzel adlandırmadır.');
    addQ(4, 18, 2, 'Aşağıdaki cümlelerin hangisinde "somutlaştırma" yapılmıştır?', 'Bütün o anılar ve kederler bir taş gibi yüreğime oturdu.', 'Kitap masanın üstündeydi.', 'Kalemi cebine koydu.', 'Bardaktaki su soğuktu.', 'Pencereden dışarı baktı.', 'A', 'Soyut bir duygu olan "keder", elle tutulur somut bir varlık olan "taş" ile anlatılmıştır.');
    addQ(4, 18, 2, 'Aşağıdaki cümlelerin hangisinde "aşamalı bir durum" (giderek değişme) bildirilmektedir?', 'Hastanın durumu günden güne daha iyiye gidiyordu.', 'Bugün sınav sonuçları açıklandı.', 'Okul yarın tatil olacak.', 'Ders zili erken çaldı.', 'Kitabı bir gecede bitirdi.', 'A', '"Günden güne, gitgide, gittikçe" ifadeleri bir sürecin basamak basamak ilerlediğini gösterir.');
    addQ(4, 18, 2, 'Aşağıdaki cümlelerin hangisinde "koşula bağlılık" (şart) anlamı vardır?', 'Ödevini zamanında teslim edersen hafta sonu maça gidebilirsin.', 'Ödevini teslim ettiği için maça gitti.', 'Ödev yapmak için odasına çekildi.', 'Ödevi çok uzundu.', 'Ödevini yapmadan uyudu.', 'A', '"-se/-sa" ekiyle maça gitmenin gerçekleşmesi ödevin teslimine bağlanmıştır.');

    // Level 3: Zor & Detay
    addQ(4, 18, 3, 'Aşağıdaki ikilemelerden hangisi "biri anlamlı biri anlamsız" sözcüklerin bir araya gelmesiyle oluşmuştur?', 'Eğri büğrü yollardan geçtik.', 'Güzel güzel konuştular.', 'Dost düşman herkes gördü.', 'İrili ufaklı taşlar topladık.', 'Yalan yanlış bilgiler verdi.', 'A', '"Eğri" anlamlı, "büğrü" tek başına anlamsız bir sözcüktür.');
    addQ(4, 18, 3, 'Aşağıdaki cümlelerin hangisinde duyular arası aktarım (duyu aktarımı) yapılmıştır?', 'Salonda tatlı bir koku ve kadife gibi yumuşak bir ses yankılandı.', 'Güneş odanın pencerelerini aydınlattı.', 'Rüzgar sertçe esti.', 'Deniz maviye boyanmıştı.', 'Çay çok sıcaktı.', 'A', '"Tatlı koku" (tatma duyusundan koklamaya) ve "yumuşak ses" (dokunma duyusundan işitmeye) duyu aktarımıdır.');
    addQ(4, 18, 3, 'Aşağıdaki cümlelerin hangisinde "yakınma" (başkalarının kusurundan şikayet etme) anlamı vardır?', 'İnsanlar günümüzde birbirlerinin yüzüne bakmadan sadece telefonlarıyla ilgileniyor.', 'Keşke ben de o kursa yazılsaydım.', 'Sınavı kazanırsam çok mutlu olurum.', 'Yarın Ankara\'ya gideceğim.', 'Kitabı çok beğendim.', 'A', 'Toplumun veya bir başkasının olumsuz davranışından duyulan rahatsızlığın dile getirilmesine yakınma denir.');
    addQ(4, 18, 3, 'Aşağıdaki cümlelerin hangisinde "öz eleştiri" (otokritik) yapılmıştır?', 'Yıllarca insanların fikirlerini dinlemeden peşin hüküm vererek büyük hata yapmışım.', 'Beni hiçbir zaman anlamadılar.', 'Bu proje onun hatası yüzünden gecikti.', 'Herkes kendi çıkarını düşünüyor.', 'Zaman çok hızlı geçiyor.', 'A', 'Kişinin kendi eksikliklerini ve yanlışlarını tarafsızca ortaya koymasına öz eleştiri denir.');
    addQ(4, 18, 3, '"Taşıma suyla değirmen dönmez" atasözünün anlattığı temel gerçeklik nedir?', 'Başkalarının küçük yardımlarıyla sürekli ve büyük bir iş yürütülemez, kalıcı öz kaynak gerekir', 'Su tasarrufu yapılmalıdır', 'Değirmen akarsu kenarına kurulmalıdır', 'Büyük işler tek başına yapılır', 'Her işin bir zamanı vardır', 'A', 'Dışarıdan gelen yetersiz ve geçici katkılarla büyük ve sürekli girişimlerin başarılamayacağını anlatır.');

    // -------------------------------------------------------------------------
    // Subcat 19: Paragrafta Anlam ve Ana Düşünce
    // -------------------------------------------------------------------------
    // Level 1: Temel Paragraf
    addQ(4, 19, 1, 'Bir paragrafın ana düşüncesi (ana fikri) genel olarak neyi ifade eder?', 'Yazarın okura vermek istediği temel mesajı ve öğüdü', 'Yazıda geçen örnekleri', 'Yazarın adını', 'Yazının yazıldığı tarihi', 'Paragrafın kaç cümle olduğunu', 'A', 'Ana düşünce yazarın metni yazma amacıdır ve metnin en kapsayıcı yargısıdır.');
    addQ(4, 19, 1, 'Bir paragrafta ana düşünceyi desteklemek, somutlaştırmak ve inandırıcı kılmak için kullanılan fikirlere ne denir?', 'Yardımcı düşünceler', 'Başlık', 'Ön söz', 'Dipnot', 'Kaynak', 'A', 'Ana fikri çevreleyen, onu açıklayan ve destekleyen her cümle yardımcı düşüncedir.');
    addQ(4, 19, 1, 'Anlatıcının bir olayı zaman, mekan ve kişi unsurlarına bağlayarak bir akış içinde anlatmasına ne ad verilir?', 'Öyküleyici Anlatım (Öyküleme)', 'Betimleyici Anlatım', 'Açıklayıcı Anlatım', 'Tartışmacı Anlatım', 'Epik Anlatım', 'A', 'Hareket, olay örgüsü ve zaman akışı varsa anlatım biçimi öykülemedir (hikaye etme).');
    addQ(4, 19, 1, 'Varlıkları okuyucunun gözünde canlandıracak şekilde renk, biçim, durum ve nitelikleriyle (sözcüklerle resim çizme) anlatma biçimi nedir?', 'Betimleyici Anlatım (Tasvir)', 'Açıklama', 'Tartışma', 'Kanıtlama', 'Tanımlama', 'A', 'Durağanlık ve sıfatların yoğunluğu varsa, zihinde bir fotoğraf oluşuyorsa betimlemedir.');
    addQ(4, 19, 1, 'Okuyucuya bilgi vermek, bir konuyu öğretmek veya aydınlatmak amacıyla nesnel bir dille yazılan anlatım biçimi nedir?', 'Açıklayıcı Anlatım (Açıklama)', 'Öyküleme', 'Betimleme', 'Tartışma', 'Mizahi Anlatım', 'A', 'Ders kitapları, makaleler ve ansiklopedik bilgiler açıklayıcı anlatımla yazılır.');
    addQ(4, 19, 1, 'Yazarın okuyucunun yerleşik bir düşüncesini değiştirmek ve kendi fikrini kabul ettirmek için karşılıklı konuşma havasında yazdığı anlatım biçimi nedir?', 'Tartışmacı Anlatım', 'Açıklama', 'Betimleme', 'Öyküleme', 'Destansı Anlatım', 'A', '"Bana göre, oysa, aksine, peki ama öyle mi?" ifadeleri tartışmacı anlatımın göstergesidir.');
    addQ(4, 19, 1, 'Düşünceyi geliştirme yollarından "Bu nedir? Bu kimdir?" sorularına cevap veren kavram belirleme yöntemine ne denir?', 'Tanımlama', 'Örneklendirme', 'Karşılaştırma', 'Tanık Gösterme', 'Sayısal Veri', 'A', '"...dır / ...denir" şeklinde biten ve bir kavramın sınırlarını çizen yargılar tanımlamadır.');
    addQ(4, 19, 1, 'Yazarın savunduğu düşünceyi inandırıcı kılmak için alanında uzman tanınmış bir kişinin ismini ve sözünü doğrudan aktarmasına ne denir?', 'Tanık Gösterme (Alıntı Yapma)', 'Örneklendirme', 'Benzetme', 'Kişileştirme', 'Somutlama', 'A', 'Sözün tırnak içinde bizzat aktarılması tanık göstermedir.');
    addQ(4, 19, 1, 'İki varlık, olay veya kavram arasındaki benzerlik ya da zıtlıkları ortaya koyarak anlatımı zenginleştirme yöntemine ne denir?', 'Karşılaştırma', 'Tanımlama', 'Örneklendirme', 'Betimleme', 'Mecaz', 'A', '"Daha, en, göre, ise, kadar" gibi sözcükler karşılaştırma yapıldığını gösterir.');
    addQ(4, 19, 1, 'Soyut veya genel bir düşünceyi somut olaylar, isimler veya eserlerle görünür kılma yoluna ne ad verilir?', 'Örneklendirme', 'Tanımlama', 'Tartışma', 'Açıklama', 'Öyküleme', 'A', 'Örneklendirmede soyut kural günlük hayattan örneklerle ete kemiğe büründürülür.');

    // Level 2: Orta Düzey
    addQ(4, 19, 2, 'Bir paragrafta "anlatımın akışını bozan cümle" nasıl tespit edilir?', 'Paragrafın genel konusu ve bakış açısından sapan, düşünce zincirini koparan cümle bulunarak', 'İlk cümleye bakılarak', 'En uzun cümleye bakılarak', 'Son cümleye bakılarak', 'Soru cümlesi seçilerek', 'A', 'Konu aynı kalsa dahi konunun farklı bir yönüne aniden atlayan cümle akışı bozar.');
    addQ(4, 19, 2, 'Bir metin iki paragrafa bölünmek istendiğinde ikinci paragraf hangi cümleden itibaren başlar?', 'Yazarın konunun başka bir boyutuna, yeni bir düşünceye veya farklı bir açıya geçtiği ilk cümleden', 'En kısa cümleden', 'Bağlaçla başlayan cümleden', 'Devrik cümleden', 'Üçüncü cümleden', 'A', 'Yeni bir konu veya aynı konunun yeni bir alt başlığı ikinci paragrafın giriş cümlesidir.');
    addQ(4, 19, 2, 'Aşağıdakilerden hangisi bir paragrafın "giriş cümlesi" olmaya uygun DEĞİLDİR?', '"Çünkü bu durum toplumun her kesimini derinden etkilemiştir."', '"Edebiyat insan ruhunu terbiye eden en eski sanatlardan biridir."', '"Sanatçı yaşadığı toplumun aynası olmak zorundadır."', '"Roman türü Batı\'da sanayi devrimiyle birlikte yükselmiştir."', '"Dil bir milletin hafızasıdır."', 'A', 'Giriş cümleleri kendisinden önce bir cümle varmış hissi veren "çünkü, bu nedenle, bundan dolayı, ama, oysa" gibi bağlayıcı unsurlarla başlayamaz.');
    addQ(4, 19, 2, 'İnsan dışındaki canlı ve cansız varlıklara insani özellikler yükleme sanatına ne ad verilir?', 'Kişileştirme (Teşhis)', 'Benzetme (Teşbih)', 'Tezat (Karşıtlık)', 'Abartma (Mübalağa)', 'Konuşturma (İntak)', 'A', '"Rüzgarın acı acı inlemesi" veya "Güneşin gülümsemesi" kişileştirmedir.');
    addQ(4, 19, 2, 'Kişileştirilen varlıkların insan gibi konuşturulması sanatına ne ad verilir?', 'Konuşturma (İntak)', 'Teşhis', 'Tezat', 'Mübalağa', 'Mecaz', 'A', 'Fabl türlerinde hayvanların konuşturulması intak sanatıdır; her intakta mutlaka teşhis de vardır.');
    addQ(4, 19, 2, 'Aşağıdaki anlatım ilkelerinden hangisi "anlatımda gereksiz sözcüklere yer vermemek, sözü uzatmamak" anlamına gelir?', 'Duruluk', 'Yalınlık', 'Akıcılık', 'Açıklık', 'Özgünlük', 'A', 'Cümleden bir sözcük çıkarıldığında anlam daralmıyorsa o sözcük gereksizdir; gereksiz sözcük olmaması "duruluk"tur.');
    addQ(4, 19, 2, 'Anlatımın süsten, sanattan, mecazlardan ve abartılı ifadelerden uzak, sade olması ilkesine ne denir?', 'Yalınlık (Sadelik)', 'Duruluk', 'Açıklık', 'Özgünlük', 'Evrensellik', 'A', 'Sanatsız ve gösterişsiz dille yazmaya yalınlık denir.');
    addQ(4, 19, 2, 'Anlatımda okurun takılmadan, pürüzsüz ve rahat bir şekilde okuyabilmesi, ses uyumunun bulunması ilkesi hangisidir?', 'Akıcılık', 'Doğallık', 'Tutarlılık', 'Yoğunluk', 'Bağlaşıklık', 'A', 'Söylenmesi zor seslerin olmaması ve ritmik okunuş akıcılığı sağlar.');
    addQ(4, 19, 2, 'Yazarın başkalarına benzememesi, taklitten uzak, kendine has bir tarz ve üsluba sahip olması ilkesine ne denir?', 'Özgünlük', 'Özlülük', 'Yalınlık', 'Evrensellik', 'Açıklık', 'A', 'Yazarın parmak izi gibi kendine has olmasına özgünlük denir.');
    addQ(4, 19, 2, 'Az sözle çok derin ve yoğun anlamlar ifade edebilme sanatına ne ad verilir?', 'Özlülük (Yoğunluk)', 'Duruluk', 'Akıcılık', 'Açıklık', 'Yalınlık', 'A', 'Atasözleri ve vecizeler az sözle ciltler dolusu anlam barındırdığı için özlü (yoğun) ifadelerdir.');

    // Level 3: Zor & Detay
    addQ(4, 19, 3, 'Bir metinde anlatılanların tüm insanlığı ilgilendirmesi, zaman ve mekan sınırlarını aşması hangi kavramla ifade edilir?', 'Evrensellik', 'Ulusalcılık', 'Özgünlük', 'Yerellik', 'Güncellik', 'A', 'Dostoyevski veya Shakespeare\'in tüm insanlığın ortak acı ve sevinçlerine hitap etmesi evrenselliktir.');
    addQ(4, 19, 3, 'Bir metinde düşüncelerin birbiriyle çelişmemesi, mantık kurallarına ve tezin savunuluşuna uygun olması ilkesine ne denir?', 'Tutarlılık', 'Bağdaşıklık', 'Özlülük', 'Akıcılık', 'Duruluk', 'A', 'Bir cümlede savunduğu düşünceyi birkaç cümle sonra inkar etmemek tutarlılıktır.');
    addQ(4, 19, 3, 'Metinde her okuyanın aynı anlamı çıkarması, çift anlamlılığa ve kapalılığa yer verilmemesi ilkesi hangisidir?', 'Açıklık', 'Duruluk', 'Yalınlık', 'Akıcılık', 'Yoğunluk', 'A', 'Noktalama eksikliği veya sözcüğün yanlış yerde kullanımı kapalılık yaratır; netlik açıklıktır.');
    addQ(4, 19, 3, 'Paragrafta tümdengelim (tümden gelim) yöntemi kullanıldığında ana fikir genellikle nerede yer alır?', 'Paragrafın ilk (giriş) cümlesinde', 'Tam ortasında', 'Son cümlesinde', 'Paragrafta hiç yer almaz', 'Örneklerin içinde', 'A', 'Genel kural başa konur (ana fikir), ardından ayrıntılar ve örnekler sıralanır.');
    addQ(4, 19, 3, 'Tümevarım yönteminin izlendiği bir paragrafta ana fikir kural olarak nerede bulunur?', 'Paragrafın son (sonuç) cümlesinde', 'Giriş cümlesinde', 'İkinci cümlede', 'Bağlaçtan önce', 'İlk örnekte', 'A', 'Özel olaylar ve örnekler anlatılır, en sonunda "Özetle, sonuç olarak, öyleyse" diyerek ana fikir çıkarılır.');

    // -------------------------------------------------------------------------
    // Subcat 20: Dil Bilgisi ve Cümlenin Ögeleri
    // -------------------------------------------------------------------------
    // Level 1: Temel Dil Bilgisi
    addQ(4, 20, 1, 'Bir cümlenin temel yargısını taşıyan ve diğer tüm ögelerin kendisine bağlandığı ana öge hangisidir?', 'Yüklem', 'Özne', 'Nesne', 'Tümleç', 'Edat', 'A', 'Cümlenin motoru yüklemdir; tüm sorular yükleme sorularak ögeler bulunur.');
    addQ(4, 20, 1, 'Yükleme sorulan "Kim?" ve "Ne?" sorularına ilk olarak cevap veren temel öge hangisidir?', 'Özne', 'Belirtili Nesne', 'Zarf Tümleci', 'Dolaylı Tümleç', 'Edat Tümleci', 'A', 'İşi yapan veya yargının konusu olan varlık öznedir.');
    addQ(4, 20, 1, 'Yükleme sorulan "Kimi?" ve "Neyi?" soruları cümlenin hangi ögesini buldurur?', 'Belirtili Nesne', 'Belirtisiz Nesne', 'Özne', 'Yer Tamlayıcısı', 'Zarf Tümleci', 'A', 'İsmin -i belirtme hal ekini alan nesne belirtili nesnedir.');
    addQ(4, 20, 1, 'İsmin "-e, -de, -den" hal eklerini alarak yüklemi yer ve yön bakımından tamamlayan ögeye ne ad verilir?', 'Dolaylı Tümleç (Yer Tamlayıcısı)', 'Zarf Tümleci', 'Nesne', 'Özne', 'Yüklem', 'A', '"Kime, kimde, kimden / Nereye, nerede, nereden" sorularına cevap verir.');
    addQ(4, 20, 1, 'Yükleme sorulan "Nasıl, ne zaman, ne kadar, niçin, neden?" sorularına cevap veren öge hangisidir?', 'Zarf Tümleci (Zarf Tamlayıcısı)', 'Dolaylı Tümleç', 'Belirtili Nesne', 'Sözde Özne', 'Yüklem', 'A', 'Eylemin zamanını, durumunu, miktarını ve sebebini belirten öge zarf tümlecidir.');
    addQ(4, 20, 1, '"Ali dün akşam bize güzel bir hediye getirdi." cümlesinin öge sıralanışı nasıldır?', 'Özne - Zarf Tümleci - Yer Tamlayıcısı - Belirtisiz Nesne - Yüklem', 'Zarf - Özne - Nesne - Yüklem', 'Özne - Nesne - Yüklem', 'Yer Tamlayıcısı - Özne - Yüklem', 'Özne - Yüklem', 'A', 'Ali (Özne), dün akşam (ZT), bize (DT), güzel bir hediye (Belirtisiz Nesne), getirdi (Yüklem).');
    addQ(4, 20, 1, 'Aşağıdaki cümlelerin hangisinde "gizli özne" kullanılmıştır?', 'Yarın sabah erken saatte yola çıkacağız.', 'Ahmet yarın erkenden gelecek.', 'Güneş erkenden doğdu.', 'Kuşlar ağaçta ötüyor.', 'Çocuklar bahçede top oynuyor.', 'A', '"Çıkacağız" yüklemindeki "-k" şahıs eki öznenin "Biz" olduğunu gösterir.');
    addQ(4, 20, 1, 'Edilgen çatılı fiillerin bulunduğu cümlelerde işi yapan belli olmadığında nesnenin özne görevini üstlenmesine ne denir?', 'Sözde Özne', 'Gerçek Özne', 'Örtülü Özne', 'Gizli Özne', 'Ortak Özne', 'A', '"Okul tatil edildi" cümlesinde tatil edilen "okul" sözde öznedir.');
    addQ(4, 20, 1, 'Fiilden türeyen ancak fiil gibi çekimlenemeyen, cümlede isim, sıfat ve zarf görevinde kullanılan sözcüklere ne denir?', 'Fiilimsi (Eylemsi)', 'Çekimli Fiil', 'Zamir', 'Edat', 'Bağlaç', 'A', 'Fiilimsiler isim-fiil (-ma,-ış,-mak), sıfat-fiil (-an,-ası,-mez,-ar,-dik,-ecek,-miş) ve zarf-fiildir.');
    addQ(4, 20, 1, '"Kitap okumak insanı dinlendirir." cümlesindeki "okumak" sözcüğü hangi tür fiilimsidir?', 'İsim-Fiil (Mastar)', 'Sıfat-Fiil (Ortaç)', 'Zarf-Fiil (Ulaç)', 'Çekimli Fiil', 'Bağ Fiil', 'A', '"-mak/-mek" eki isim-fiil ekidir.');

    // Level 2: Orta Düzey
    addQ(4, 20, 2, '"Ağaran saçlarını aynada uzun uzun inceledi." cümlesindeki "ağaran" sözcüğü hangi fiilimsi türüdür?', 'Sıfat-Fiil (Ortaç)', 'İsim-Fiil', 'Zarf-Fiil', 'Zamir', 'Edat', 'A', '"Ağaran saç" tamlamasında "-an" sıfat-fiil ekidir (An-ası-mez-ar-dik-ecek-miş).');
    addQ(4, 20, 2, 'Aşağıdaki cümlelerin hangisinde fiilimsi (eylemsi) kullanılmamıştır?', 'Dün akşam eve çok geç saatte geldi.', 'Koşarak yanımıza geldi.', 'Görülecek hesaplarımız var.', 'Gülüşü herkesi etkiledi.', 'Gidip onu hemen uyardı.', 'A', '"Geldi" çekimli fiildir; cümlede hiç fiilimsi yoktur.');
    addQ(4, 20, 2, 'Geçişli fiil nesne alabilen fiildir (başına "onu" sözcüğü gelir). Aşağıdakilerden hangisi geçişli bir fiildir?', 'Okumak (Onu okumak)', 'Uyumak (Onu uyumak olmaz)', 'Ağlamak', 'Gülmek', 'Koşmak', 'A', '"Onu okudu / kitabı okudu" nesne alabildiği için geçişlidir; uyumak, ağlamak geçişsizdir.');
    addQ(4, 20, 2, 'Fiilin kök veya gövdesine "-l" veya "-n" ekleri getirilerek işi yapanın belirsiz kılındığı çatıya ne ad verilir?', 'Edilgen Çatı', 'Etken Çatı', 'Dönüşlü Çatı', 'İşteş Çatı', 'Ettirgen Çatı', 'A', '"Cam kırıldı / Yollar temizlendi" edilgendir, işi yapan gizlidir.');
    addQ(4, 20, 2, 'Öznenin hem işi yaptığı hem de yaptığı işten bizzat kendisinin etkilendiği çatı türü hangisidir?', 'Dönüşlü Çatı (Kendi kendine)', 'Edilgen Çatı', 'Etken Çatı', 'İşteş Çatı', 'Oldurgan Çatı', 'A', '"Ahmet yıkandı / süslendi / tarandı" eylemlerinde özne işi bizzat kendi üzerinde yapar.');
    addQ(4, 20, 2, 'Birden fazla öznenin eylemi "birlikte" veya "karşılıklı" yaptığını belirten "-ş" ekli çatı türü nedir?', 'İşteş Çatı', 'Etken Çatı', 'Edilgen Çatı', 'Dönüşlü Çatı', 'Ettirgen Çatı', 'A', '"Mektuplaşmak / selamlaşmak" (karşılıklı), "kaçışmak / uçuşmak" (birlikte) işteş çatıdır.');
    addQ(4, 20, 2, 'Yüklemi isim soylu bir sözcük olan cümlelere ne denir?', 'İsim Cümlesi', 'Fiil Cümlesi', 'Kurallı Cümle', 'Devrik Cümle', 'Birleşik Cümle', 'A', '"Hava bugün çok güzeldi." cümlesinde "güzel" isimdir, ek fiil alarak yüklem olmuştur.');
    addQ(4, 20, 2, 'Yüklemi cümlenin sonunda bulunmayan, başta veya ortada olan cümlelere ne ad verilir?', 'Devrik Cümle', 'Kurallı (Düz) Cümle', 'Eksiltili Cümle', 'Şartlı Cümle', 'Bağlı Cümle', 'A', '"Açtı kapıyı ansızın." cümlesinde yüklem başta olduğu için devriktir.');
    addQ(4, 20, 2, 'Yüklemi yazılmamış, tamamlanması okuyucunun zihnine bırakılmış ve sonuna üç nokta konulan cümlelere ne denir?', 'Eksiltili Cümle', 'Basit Cümle', 'Devrik Cümle', 'Sıralı Cümle', 'Olumsuz Cümle', 'A', '"Karşımızda masmavi bir deniz..." cümlesinde yüklem söylenmemiştir (eksiltili).');
    addQ(4, 20, 2, 'Tek bir yüklemi olan ve içinde en az bir fiilimsi (yan cümle) barındıran cümle türü hangisidir?', 'Girişik Birleşik Cümle', 'Basit Cümle', 'Sıralı Cümle', 'Bağlı Cümle', 'Şartlı Birleşik', 'A', 'Fiilimsi içeren cümleler girişik birleşiktir; fiilimsi sayısı kadar yan cümle vardır.');

    // Level 3: Zor & Detay
    addQ(4, 20, 3, 'Birden çok bağımsız cümlenin birbirine virgül (,) veya noktalı virgülle (;) bağlanmasıyla oluşan cümlelere ne denir?', 'Sıralı Cümle', 'Bağlı Cümle', 'Birleşik Cümle', 'Basit Cümle', 'Karma Cümle', 'A', '"At ölür, meydan kalır; yiğit ölür, şan kalır." tipik bir sıralı cümledir.');
    addQ(4, 20, 3, 'Birden çok cümlenin birbirine "ve, ama, fakat, ancak, çünkü" gibi bağlaçlarla bağlandığı cümle yapısı nedir?', 'Bağlı Cümle', 'Sıralı Cümle', 'Girişik Cümle', 'Basit Cümle', 'İç İçe Cümle', 'A', '"Eve geldi VE hemen ders çalışmaya başladı." bağlaçla bağlanan bağlı cümledir.');
    addQ(4, 20, 3, 'Aşağıdaki ses olaylarından hangisinde sözcüğe ünlüyle başlayan bir ek geldiğinde kökteki ünlü düşer?', 'Ünlü Düşmesi (Hece Düşmesi)', 'Ünsüz Benzeşmesi', 'Ünsüz Türemesi', 'Ünlü Daralması', 'Kaynaşma', 'A', 'Akıl -> Aklı, Burun -> Burnu, Gönül -> Gönlü (Ünlü düşmesi).');
    addQ(4, 20, 3, 'Sert ünsüzle (FıSTıKÇı ŞaHaP) biten bir sözcüğe "c, d, g" ile başlayan bir ek geldiğinde bu eklerin "ç, t, k"ye dönüşmesine ne ad verilir?', 'Ünsüz Benzeşmesi (Sertleşmesi)', 'Ünsüz Yumuşaması', 'Ünlü Düşmesi', 'Ulama', 'Küçülme', 'A', 'Kitap-da -> Kitapta, Sınıf-ca -> Sınıfça, Türk-ce -> Türkçe.');
    addQ(4, 20, 3, '"a, e" geniş ünlüleriyle biten bir fiile "-yor" şimdiki zaman eki geldiğinde bu ünlülerin "ı, i, u, ü" dar ünlülerine dönüşmesine ne denir?', 'Ünlü Daralması', 'Ünlü Düşmesi', 'Ünsüz Türemesi', 'Ünsüz Düşmesi', 'Yumuşama', 'A', 'Başla-yor -> Başlıyor, Bekle-yor -> Bekliyor, Ye-yor -> Yiyor, De-yor -> Diyor.');

    // -------------------------------------------------------------------------
    // Subcat 21: Yazım Kuralları ve Noktalama İşaretleri
    // -------------------------------------------------------------------------
    // Level 1: Temel Kurallar
    addQ(4, 21, 1, 'Aşağıdaki cümlelerin hangisinde "de / da" bağlacının yazımıyla ilgili bir yanlışlık yapılmıştır?', 'Sende bizimle toplantıya katılacak mısın?', 'Evde kimse yoktu.', 'Kitap da masada unutulmuş.', 'Sen de mi bu fikri savunuyorsun?', 'Okulda dersler bitti.', 'A', '"Sen de" ayrı yazılmalıdır; bağlaç olan de/da cümleden çıkarılınca anlam bozulmaz ve her zaman ayrı yazılır.');
    addQ(4, 21, 1, 'Aşağıdaki cümlelerin hangisinde "ki" bağlacının yazımı YANLIŞTIR?', 'Evdeki hesap çarşıya uymadı.', 'Sen ki beni en iyi tanıyan insansın.', 'Öyle bir bağırdı ki herkes sustu.', 'Mademki gelmeyecektin neden haber vermedin?', 'Duydumki unutmuşsun gözlerimin rengini.', 'E', '"Duydum ki" ayrı yazılmalıdır (Fiilden sonra gelen "ki"ler istisnasız ayrı yazılır).');
    addQ(4, 21, 1, 'Sözcük durumundaki "ki" bağlacı hangi kalıplaşmış sözcüklerde istisna olarak BİTİŞİK yazılır?', 'SOMBAHÇEMİ (Sanki, Oysaki, Mademki, Belki, Halbuki, Çünkü, Meğerki, İllaki)', 'Yalnızca belki', 'Bütün fiillerde', 'Hiçbirinde', 'Sadece Türkçede', 'A', 'SOMBAHÇEMİ formülü kalıplaşmış bitişik yazılan ki bağlaçlarıdır.');
    addQ(4, 21, 1, 'Soru eki olan "mı / mi / mu / mü"nün yazımıyla ilgili doğru kural hangisidir?', 'Kendisinden önceki sözcükten daima ayrı yazılır, kendisine gelen ekler ise bitişik yazılır', 'Her zaman bitişik yazılır', 'Yalnızca soru sorarken ayrı yazılır', 'Fiillerden sonra bitişik yazılır', 'Kesme işaretiyle ayrılır', 'A', '"Gelecek misiniz? / Güzel mi güzel bir gün" daima ayrı yazılır.');
    addQ(4, 21, 1, 'Özel adlara getirilen iyelik, durum ve bildirme ekleri hangi noktalama işaretiyle ayrılır?', 'Kesme İşareti (\')', 'Virgül (,)', 'Noktalı Virgül (;)', 'İki Nokta (:)', 'Tırnak İşareti', 'A', 'Türkiye\'nin, Atatürk\'e, Ankara\'da örneklerinde olduğu gibi kesme işaretiyle ayrılır.');
    addQ(4, 21, 1, 'Özel adlara getirilen yapım ekleri ve çokluk eki (-lar/-ler) kesme işaretiyle ayrılır mı?', 'Ayrılmaz; bunlardan sonra gelen çekim ekleri de ayrılmaz', 'Her zaman ayrılır', 'Sadece Türk sözcüğünde ayrılır', 'İsteğe bağlıdır', 'Kısaltmalarda ayrılır', 'A', 'Türkçenin, Ankaralılar, Ahmetler, Müslümanlıkta sözcüklerinde kesme işareti ASLA kullanılmaz.');
    addQ(4, 21, 1, 'Aşağıdaki cümlelerin hangisinde büyük harflerin yazımıyla ilgili bir yanlışlık yapılmıştır?', 'Dün akşam Van gölü kıyısında yürüyüş yaptık.', 'Kurtuluş Savaşı milletin azmiyle kazanıldı.', 'Türkiye Büyük Millet Meclisi Ankara\'dadır.', 'Galata Köprüsü İstanbul\'un simgelerindendir.', 'Ağrı Dağı Türkiye\'nin çatısıdır.', 'A', '"Van Gölü" şeklinde göl, deniz, dağ, nehir adları büyük harfle başlar.');
    addQ(4, 21, 1, 'Tarihlerin yazılışında belirli bir günü ve ayı belirten resmi tarihler nasıl yazılır?', '29 Ekim 1923 (Ay adı büyük yazılır)', '29 ekim 1923', 'ekim 1923', 'salı günü', 'her ay büyük yazılır', 'A', 'Önünde veya arkasında kesin bir rakam olan ay ve gün adları büyük yazılır (29 Ekim, 15 Temmuz Pazartesi).');
    addQ(4, 21, 1, 'Aşağıdaki birleşik sözcüklerden hangisinin yazımı DOĞRUDUR?', 'Hukuk kuralları gereği "terk etmek" ayrı yazılır.', 'Terketmek', 'Farketmek', 'Ayırtetmek', 'Vaz geçmek', 'A', 'Ses düşmesi veya türemesi olmayan yardımcı eylemler (etmek, olmak) ayrı yazılır: Terk etmek, fark etmek, arz etmek.');
    addQ(4, 21, 1, 'Ses düşmesi veya ünsüz türemesi meydana gelen yardımcı eylemli sözcükler nasıl yazılır?', 'Bitişik yazılır (Hissetmek, kaybolmak, affetmek, sabretmek)', 'Ayrı yazılır', 'Tire ile bağlanır', 'Kesmeyle ayrılır', 'Yalnızca tek heceliler bitişik yazılır', 'A', 'His + etmek -> Hissetmek (türeme), Kayıp + olmak -> Kaybolmak (düşme) olduğu için bitişik yazılır.');

    // Level 2: Orta Düzey
    addQ(4, 21, 2, 'Cümle içinde virgüllerle ayrılmış tür veya takımları birbirinden ayırmak için hangi noktalama işareti kullanılır?', 'Noktalı Virgül (;)', 'İki Nokta (:)', 'Üç Nokta (...)', 'Kısa Çizgi (-)', 'Tırnak İşareti', 'A', '"Erkek çocuklara Doğan, Tuğrul, Aslan; kız çocuklara İnci, Çiçek, Gönül adları verilir." örneğinde noktalı virgül kullanılır.');
    addQ(4, 21, 2, 'Kendisiyle ilgili açıklama verilecek veya örnek gösterilecek cümlenin sonuna hangi noktalama işareti konur?', 'İki Nokta (:)', 'Noktalı Virgül (;)', 'Virgül (,)', 'Nokta (.)', 'Üç Nokta (...)', 'A', 'Açıklama ve örnekten önce mutlaka iki nokta (:) konur.');
    addQ(4, 21, 2, 'Aşağıdaki cümlelerin hangisinde noktalama yanlışı yapılmıştır?', 'Gözlerini açıp, etrafına şaşkınlıkla baktı.', 'Evden çıktı, arabaya bindi.', 'Ders çalıştı; ancak sınavı kazanamadı.', 'Bunu bana neden söylemedin?', 'Ali, Veli ve Can geldiler.', 'A', 'Metin içinde "-ıp/-ip, -erek/-arak, -ınca/-ince" gibi tek bir zarf-fiil ekinden sonra ASLA virgül konmaz.');
    addQ(4, 21, 2, 'Şart ekinden (-se / -sa) sonra virgül konur mu?', 'Hayır, tek bir şart ekinden sonra asla virgül konmaz', 'Evet, her zaman konur', 'Sadece şiirlerde konur', 'Yüklemden önce konur', 'İsteğe bağlıdır', 'A', 'Tıpkı zarf-fiil gibi şart ekinden (-se/-sa) sonra da virgül konulması kural hatasıdır.');
    addQ(4, 21, 2, 'Aşağıdaki sözcüklerden hangisinin yazımı DOĞRUDUR?', 'Kravat', 'Kıravat', 'Traş', 'Kirpik değil kiprik', 'Labaratuvar', 'A', 'Doğru yazılışları: Kravat, Tıraş, Kirpik, Laboratuvar, Egzoz.');
    addQ(4, 21, 2, '"Şey" sözcüğü kendisinden önceki sözcüklerle nasıl yazılır?', 'Daima AYRI yazılır (Her şey, bir şey, hiçbir şey, çok şey)', 'Her zaman bitişik', 'Yalnızca "birşey" bitişik', 'Sadece sonda bitişik', 'Cümleye göre değişir', 'A', '"Şey" zamir olduğu için her zaman ayrı yazılır: Her şey, hiçbir şey, bir şey.');
    addQ(4, 21, 2, 'Aşağıdaki birleşik sözcüklerden hangisi BİTİŞİK yazılır?', 'Birtakım (Bazı anlamındaki belgisiz sözcük)', 'Bir takım elbise', 'Bir gün', 'Her gün', 'Pek çok', 'A', '"Birtakım sorunlar" (belgisiz ise bitişik), sayı sıfatı ise "bir takım elbise" (ayrı yazılır).');
    addQ(4, 21, 2, 'Kurum, kuruluş ve kurul adlarına gelen ekler kesme işaretiyle ayrılır mı?', 'Ayrılmaz (Türk Dil Kurumuna, Türkiye Büyük Millet Meclisinde)', 'Ayrılır', 'Sadece üniversitelerde ayrılır', 'Kısaltmalarda ayrılmaz', 'Yalnızca bakanlıklarda ayrılır', 'A', 'Kurum ve kuruluş adlarına gelen ekler (TDK hariç açılımında) kesmeyle ayrılmaz: Bakanlar Kurulunun, İstanbul Üniversitesine.');
    addQ(4, 21, 2, 'Küçük harflerle yapılan kısaltmalara getirilen eklerde ne esas alınır?', 'Kelimenin okunuşu esas alınır (kg\'dan, cm\'yi, mm\'ye)', 'Son harfin okunuşu', 'Büyük harf kuralı', 'Nokta konması', 'Hiçbiri', 'A', 'Küçük harfli kısaltmalarda kelimenin açılışı (kilogramdan); büyük harfli kısaltmalarda ise son harfin sesi (TBMM\'ye, TDK\'ye) esas alınır.');
    addQ(4, 21, 2, 'Büyük harfli kısaltmalarda "TDK" kısaltmasının eki nasıl olmalıdır?', 'TDK\'ye (Türkçede "ka" sesi yoktur, "ke" sesi vardır)', 'TDK\'ya', 'TDK\'na', 'TDK\'da', 'TDK\'nın', 'A', 'Türk alfabesinde "K" harfi "ke" olarak okunur; dolayısıyla "TDK\'ye" yazımı doğrudur.');

    // Level 3: Zor & Detay
    addQ(4, 21, 3, 'Gelenekleşmiş olarak sonunda nokta bulunan kısaltmalara gelen ekler nasıl yazılır?', 'Kesme işareti kullanılmaz, doğrudan noktanın yanına eklenir (vb.leri, mad.si, vb.nin)', 'Kesmeyle ayrılır', 'Ayrı yazılır', 'Büyük harfle yazılır', 'Tire ile ayrılır', 'A', 'Sonunda nokta olan kısaltmalarda kesme işareti kullanılmaz (Alm.dan, İng.yi).');
    addQ(4, 21, 3, 'Aşağıdaki cümlelerin hangisinde alt ve üst sözcüklerinin yazımıyla ilgili kurala uyulmuştur?', 'Akşamüstü ve bilinçaltı sözcükleri somut bir yer bildirmediği için BİTİŞİK yazılır.', 'Akşam üstü ayrı', 'Bilinç altı ayrı', 'Yer altı bitişik', 'Su altı bitişik', 'A', '"Alt, üst, üzeri" sözcükleri somut yer bildirmiyorsa bitişik (akşamüstü, suçüstü, bilinçaltı); somut yer bildiriyorsa ayrı (su altı, yer altı) yazılır.');
    addQ(4, 21, 3, 'Aşağıdaki unvan ve saygı sözcüklerinden hangisinin yazımı DOĞRUDUR?', 'Ahmet Bey, Ayşe Hanım, Doktor Mehmet, Avukat Ali (Unvanlar ve lakaplar büyük harfle başlar)', 'ahmet bey', 'doktor mehmet', 'avukat ali', 'hemşire fatma', 'A', 'Kişi adlarından önce ve sonra gelen unvanlar, saygı sözleri, meslek ve lakaplar büyük harfle başlar.');
    addQ(4, 21, 3, 'Para ile ilgili senet, çek vb. ticari belgelerde geçen sayıların yazımı nasıldır?', 'Araya başka rakam eklenmesini önlemek için BİTİŞİK yazılır (#yüzellibinTL#)', 'Ayrı yazılır', 'Rakamla yazılmaz', 'Tireyle yazılır', 'Noktayla yazılır', 'A', 'Senet ve çeklerde sahteciliği önlemek için sayılar bitişik yazılır; normal metinlerde ise sayılar daima ayrı yazılır (on beş, yüz yirmi).');
    addQ(4, 21, 3, 'Düşünce, hayat tarzı, politika anlamı bildiren "doğu" ve "batı" sözcükleri nasıl yazılır?', 'Büyük harfle başlar (Batı medeniyeti, Doğu felsefesi)', 'Küçük harfle başlar', 'Kesmeyle ayrılmaz', 'İtalik yazılır', 'Tırnak içinde yazılır', 'A', 'Yön bildirmeyip medeniyet, kültür veya ülke grubu kastettiğinde Doğu ve Batı büyük harfle yazılır.');

    // -------------------------------------------------------------------------
    // Subcat 22: Sözel Mantık ve Muhakeme
    // -------------------------------------------------------------------------
    // Level 1: Temel Mantık
    addQ(4, 22, 1, 'Sözel mantık sorularında çözüm yaparken kurulması gereken en temel yapı nedir?', 'Sabit değişkenleri (örneğin günler veya sıralar) başa yazıp tablo oluşturmak', 'Soruyu ezberlemek', 'Şıkları tek tek okumak', 'Metni baştan sona çizmek', 'Hemen tahmin yürütmek', 'A', 'Sözel mantıkta değişmeyen unsurları (günler, katlar, sıra numaraları) sütun yaparak tablo kurmak çözümü kesinleştirir.');
    addQ(4, 22, 1, 'Ahmet, Burak, Cemil bir yarışta ilk üçe girmiştir. Ahmet birinci değildir, Burak Cemil\'den hemen sonra gelmiştir. Yarışı kim kazanmıştır?', 'Cemil', 'Ahmet', 'Burak', 'Cemil ve Burak berabere', 'Belli değildir', 'A', 'Ahmet 1. değilse, Burak da Cemil\'den hemen sonraysa: 1. Cemil, 2. Burak, 3. Ahmet olmak zorundadır.');
    addQ(4, 22, 1, 'A, B, C, D harfleri soldan sağa dizilmiştir. B harfi C\'nin sağında, A harfi B\'nin sağında, D ise en soldadır. Soldan 2. harf hangisidir?', 'C', 'B', 'A', 'D', 'Belli değil', 'A', 'Sıralama: D (en sol) - C - B - A şeklindedir. Soldan 2. C\'dir.');
    addQ(4, 22, 1, 'Bir raftaki kitaplardan Tarih kitabı Coğrafya kitabının üstünde, Türkçe kitabı ise Tarih kitabının üstündedir. En altta hangi kitap vardır?', 'Coğrafya Kitabı', 'Tarih Kitabı', 'Türkçe Kitabı', 'Matematik Kitabı', 'Felsefe Kitabı', 'A', 'Üstten alta sıralama: Türkçe -> Tarih -> Coğrafya. En altta Coğrafya vardır.');
    addQ(4, 22, 1, 'Pazartesi, Salı ve Çarşamba günleri Ali, Veli ve Selami nöbet tutacaktır. Ali Salı günü tutmamıştır. Selami Çarşamba günü tutmuştur. Pazartesi günü kim nöbet tutmuştur?', 'Ali', 'Veli', 'Selami', 'Belli değil', 'Nöbetçi yoktur', 'A', 'Çarşamba Selami. Geriye Pazartesi ve Salı kaldı. Ali Salı değilse mecburen Pazartesi tutmuştur.');
    addQ(4, 22, 1, '5 katlı bir binada Ayşe Fatma\'nın bir üst katında, Mehmet ise Ayşe\'nin iki üst katındadır. Fatma 1. katta oturduğuna göre Mehmet kaçıncı kattadır?', '4. Katta', '2. Katta', '3. Katta', '5. Katta', 'Çatı katında', 'A', 'Fatma 1. kat -> Ayşe 2. kat -> Mehmet 2+2=4. kattadır.');
    addQ(4, 22, 1, 'Bir doktor haftanın tek günlerinde (Pzt, Çar, Cuma), bir diş hekimi ise haftanın çift günlerinde (Salı, Perşembe) hasta kabul etmektedir. Hangi gün ikisi de aynı anda hasta bakmaz?', 'Haftanın hiçbir gününde aynı anda bakmazlar', 'Pazartesi', 'Salı', 'Çarşamba', 'Cuma', 'A', 'Biri tek günlerde, diğeri çift günlerde baktığı için kesişim kümeleri boştur.');
    addQ(4, 22, 1, 'K, L, M, N araçları otoparka yan yana park etmiştir. K aracı M\'nin sağında, N aracı L\'nin solundadır. M en solda ise N nerede olamaz?', 'En solda (1. sırada) olamaz', 'Ortada olabilir', 'Sağda olabilir', 'Park edemez', 'Garajda olamaz', 'A', 'M en solda ise başka hiçbir araç 1. sıraya gelemez.');
    addQ(4, 22, 1, 'Her doğru bilginin kesin bir öncüle dayandığı sistemde "Kesinlikle Yanlıştır" sorusu ne anlama gelir?', 'Öncüllere ve kurulan tabloya göre gerçekleşmesi imkânsız olan çelişkili seçenek', 'Doğru olma ihtimali olan', 'Yarı doğru olan', 'Emin olunamayan', 'Öncüllerde yazmayan', 'A', 'Tüm olasılıklarda kesinlikle çelişki yaratan ve asla gerçekleşemeyecek seçenek aranır.');
    addQ(4, 22, 1, 'Sözel mantık sorularında "Ali\'nin bindiği otobüse Veli de binmiştir" ifadesi neyi gerektirir?', 'Ali ve Veli\'nin aynı grupta/araçta birlikte yer aldığını', 'Ali\'nin önce bindiğini', 'Veli\'nin şoför olduğunu', 'Farklı araçta olduklarını', 'Tek başına olduklarını', 'A', 'İki kişinin aynı küme içinde paketlendiğini gösterir (Ali+Veli bloku).');

    // Level 2: Orta Düzey
    addQ(4, 22, 2, 'Bir sinema salonunda A, B, C, D, E adlı 5 kişi yan yana oturmaktadır. C tam ortadadır. A ile E yan yana değildir. D, C\'nin hemen solundadır. B nerede oturmaktadır?', 'Sağ tarafta (4 veya 5. sırada)', 'En solda', 'Ortada', 'D ile C arasında', 'Belli değildir', 'A', 'Koltuklar: 1, 2, 3(C), 4, 5. D hemen soldaysa 2. koltuk D\'dir. B ise 4 veya 5. koltuktadır.');
    addQ(4, 22, 2, 'Bir lokantada çorba, kebap ve tatlı siparişi veren 3 arkadaşla ilgili olarak: Ahmet tatlı yememiştir, Mehmet çorba içmemiştir. Herkes farklı bir şey yediğine göre kebap yiyen kimdir?', 'Belli olan verilere göre Ahmet kebap veya çorba yemiştir', 'Mehmet', 'Can', 'Garson', 'Lokantacı', 'A', 'Verilen kısıtlamalar eşleştirilerek seçenek analizi yapılır.');
    addQ(4, 22, 2, 'Sözel mantıkta "ya... ya da..." bağlacı seçeneklerden kaç tanesinin doğru olduğunu belirtir?', 'Yalnızca bir tanesinin doğru olduğunu, ikisinin aynı anda olamayacağını', 'İkisinin de doğru olduğunu', 'İkisinin de yanlış olduğunu', 'Hepsinin doğru olduğunu', 'Fark etmez', 'A', '"Ya A ya B" ifadesi karşılıklı dışlayan (biri varken diğeri yok) kesin kuraldır.');
    addQ(4, 22, 2, 'Bir turnuvada 4 takım (A, B, C, D) lig usulü birbiriyle birer maç yapacaktır. Toplam kaç maç oynanır?', '6 maç', '4 maç', '12 maç', '8 maç', '10 maç', 'A', 'Kombinasyon C(4,2) = (4 x 3) / 2 = 6 maç oynanır.');
    addQ(4, 22, 2, 'Bir mülakatta adaylar 1\'den 5\'e kadar puan almıştır. Ali, Burak\'tan yüksek, Can\'dan düşük almıştır. Can 4 puan aldığına göre Ali\'nin alabileceği tek puan kaçtır?', '3 puan', '1 puan', '2 puan', '5 puan', '4 puan', 'A', 'Burak < Ali < Can (4). Burak en az 1 veya 2 olacağına göre Ali ancak 3 veya 2 olabilir; Burak\'tan yüksek olması için Ali=3, Burak=2 veya 1\'dir.');

    // Level 3: Zor & Detay
    addQ(4, 22, 3, 'Bir şirkette Pazarlama, Finans ve İK departmanlarına 6 kişi (K, L, M, N, O, P) eşit sayıda (her birine 2 kişi) dağıtılacaktır. K Finans\'tadır. L ile M aynı departmandadır. L ve M nereye gidemez?', 'Finans departmanına gidemez (çünkü orada sadece 1 kişilik yer kalmıştır)', 'Pazarlamaya gidemez', 'İK\'ya gidemez', 'Hiçbir yere gidemez', 'Belli değil', 'A', 'Finans\'ta K olduğu için 1 kişi kalmıştır, 2 kişilik L-M bloku sadece Pazarlama veya İK\'ya gidebilir.');
    addQ(4, 22, 3, 'Sözel mantıkta çapraz tablo (matris) hangi durumlarda kurulur?', 'İki veya daha fazla bağımsız özelliğin (örneğin kişi, gidilen şehir ve ulaşım aracı) eşleştirilmesinde', 'Sadece tek kişi varken', 'Sadece sayılarda', 'Şiir incelemesinde', 'Zaman olmadığında', 'A', 'Çoklu değişkenli sorularda satır-sütun matrisi kurularak olasılıklar elenir.');
    addQ(4, 22, 3, 'Öncüllerde "X gerçekleşirse Y de gerçekleşir; ancak Y gerçekleşmezse Z gerçekleşir" dendiğinde Y gerçekleşmemişse kesin sonuç nedir?', 'Z kesinlikle gerçekleşmiştir ve X gerçekleşmemiştir', 'X gerçekleşmiştir', 'Hiçbiri olmamıştır', 'Y gerçekleşmiştir', 'Bilinemez', 'A', 'Mantıkta p => q önermesinde q yanlışsa p de yanlıştır (~q => ~p). Y yoksa Z vardır.');
    addQ(4, 22, 3, 'Bir kuyrukta Ahmet baştan 12., Mehmet ise sondan 15. sıradadır. Aralarında 3 kişi vardır ve Ahmet gişeye daha yakındır. Kuyrukta kaç kişi vardır?', '22 kişi', '30 kişi', '28 kişi', '25 kişi', '32 kişi', 'A', 'Ahmet baştan 12. Aralarında 3 kişi var -> Mehmet baştan 12 + 3 + 1 = 16. sıradadır. Mehmet sondan 15. ise: 16 + 15 - 1 = 30 kişi (Ahmet öndeyse 12 + 3 + 15 = 30).');
    addQ(4, 22, 3, 'Sözel mantıkta ihtimalli durumlarda adayın yapması gereken en doğru strateji nedir?', 'Tek tabloda iki farklı ihtimali yan yana çatallandırarak çizmek', 'Rastgele birini seçip devam etmek', 'Soruyu boş bırakmak', 'Tüm şıkları C yapmak', 'En uzun seçeneği işaretlemek', 'A', 'Olasılık 2\'ye indiğinde çift tablo (İhtimal 1 ve İhtimal 2) çizmek soruların tamamını saniyeler içinde çözdürür.');
};
