// KPSS Vatandaşlık Complete Bank (150 Questions - 5 Subcategories, 3 Levels, 10 Q per level)
module.exports = function (addQ) {
// KPSS Vatandaşlık & Anayasa Authentic Questions Bank (150 Questions - 5 Subcategories, 3 Levels, 10 Q per level)
// Category: 3 (Vatandaşlık)


    // -------------------------------------------------------------------------
    // Subcat 13: Temel Hukuk Kavramları
    // -------------------------------------------------------------------------
    // Level 1: Temel Bilgiler
    addQ(3, 13, 1, 'Toplumsal düzen kuralları arasında yaptırımı "maddi" (devlet gücüyle desteklenen) olan tek kural türü hangisidir?', 'Hukuk Kuralları', 'Din Kuralları', 'Ahlak Kuralları', 'Görgü Kuralları', 'Örf ve Adetler', 'A', 'Hukuk kurallarını diğer toplumsal kurallardan ayıran en temel fark devlet yaptırımlı (maddi yaptırımlı) olmasıdır.');
    addQ(3, 13, 1, 'Kişinin hak sahibi olabilme ve borç altına girebilme ehliyetine ne ad verilir?', 'Hak Ehliyeti', 'Fiil Ehliyeti', 'Vesayet', 'Kaza-i Rüşt', 'Ayırt Etme Gücü', 'A', 'Hak ehliyeti sağ ve tam doğumla başlar; pasif bir ehliyettir.');
    addQ(3, 13, 1, 'Kişinin kendi fiil ve eylemleriyle hak kazanabilmesi ve borç altına girebilmesi ehliyetine ne denir?', 'Fiil Ehliyeti', 'Hak Ehliyeti', 'Tüzel Kişilik', 'Velayet', 'Hısımlık', 'A', 'Fiil ehliyeti için ergin olmak, ayırt etme gücüne sahip olmak ve kısıtlı olmamak şarttır.');
    addQ(3, 13, 1, 'Türk Medeni Kanunu\'na göre normal erginlik (rüşt) yaşı kaçtır?', '18 yaşın doldurulması', '17 yaş', '16 yaş', '21 yaş', '15 yaş', 'A', '18 yaşını dolduran her birey kanunen ergindir.');
    addQ(3, 13, 1, 'Evlenme yoluyla erginlikte olağan evlenme yaşı kaçtır?', '17 yaşını doldurmak', '18 yaş', '16 yaş', '15 yaş', '20 yaş', 'A', 'Medeni Kanun\'a göre 17 yaşını dolduran erkek ve kadın yasal temsilcisinin izniyle evlenebilir.');
    addQ(3, 13, 1, 'Mahkeme kararıyla ergin kılınma (Kaza-i Rüşt) için kişinin en az kaç yaşını doldurmuş olması şarttır?', '15 yaşını doldurmuş olmak', '14 yaş', '16 yaş', '17 yaş', '12 yaş', 'A', '15 yaşını dolduran küçüğün kendi isteği, velisinin izni ve mahkeme kararıyla ergin kılınması mümkündür.');
    addQ(3, 13, 1, 'Hukuk kuralları hiyerarşisinde (Normlar Hiyerarşisi) en üstte yer alan norm hangisidir?', 'Anayasa', 'Kanun', 'Cumhurbaşkanlığı Kararnamesi', 'Yönetmelik', 'Genelge', 'A', 'Hans Kelsen\'in normlar piramidinde en üstte Anayasa yer alır; hiçbir kanun anayasaya aykırı olamaz.');
    addQ(3, 13, 1, 'Bir ülkede yetkili makamlar tarafından konulmuş olan ve halen yürürlükte bulunan yazılı hukuk kurallarının tümüne ne ad verilir?', 'Mevzu Hukuk', 'Pozitif Hukuk', 'Tarihi Hukuk', 'İdeal (Tabii) Hukuk', 'Örfi Hukuk', 'A', 'Sadece yazılı kurallar "Mevzu Hukuk", yazılı + yazısız yürürlükteki kurallar ise "Pozitif (Müspet) Hukuk"tur.');
    addQ(3, 13, 1, 'Bir hukuki işlemde kanunun aradığı kurucu unsurların (örneğin evlendirme memuru olmadan evlenme) bulunmaması halinde işlemin tabi olduğu yaptırım nedir?', 'Yokluk', 'Mutlak Butlan', 'Nisbi Butlan', 'İptal', 'Fesih', 'A', 'Kurucu unsuru eksik olan hukuki işlem baştan itibaren hiç doğmamış sayılır (Yokluk).');
    addQ(3, 13, 1, 'Kanunun emredici hükümlerine, kamu düzenine veya genel ahlaka aykırı olarak yapılan sözleşmeler hangi yaptırıma tabidir?', 'Mutlak Butlan (Geçersizlik)', 'Nisbi Butlan', 'Tazminat', 'Hapis', 'Askıda Hükümsüzlük', 'A', 'Kurucu unsurları tam olsa bile emredici kanun hükümlerine aykırı işlemler mutlak butlanla sakattır.');

    // Level 2: Orta Düzey
    addQ(3, 13, 2, 'Yetkili temsilcinin izni olmadan yapılan bir sözleşmenin tabi olduğu geçersizlik hali hangisidir?', 'Tek Taraflı Bağlamazlık (Askıda Hükümsüzlük)', 'Yokluk', 'Mutlak Butlan', 'Cebr-i İcra', 'Gasp', 'A', 'Temsilci onay verirse sözleşme geçerli olur, vermezse baştan itibaren geçersiz kalır.');
    addQ(3, 13, 2, 'Borçlar Kanunu\'na göre borcun kaynakları aşağıdakilerden hangileridir?', 'Hukuki İşlemler (Sözleşmeler), Haksız Fiiller, Sebepsiz Zenginleşme', 'Ceza davaları', 'Vasiyetname', 'Miras', 'Vergi tahakkuku', 'A', 'Borcun 3 temel kaynağı: Sözleşme, haksız fiil (zarar verme) ve sebepsiz zenginleşmedir.');
    addQ(3, 13, 2, 'Kişinin kendisine veya başkasına yönelik haksız bir saldırıyı o anda orantılı bir güçle savuşturması haline ne denir?', 'Meşru Müdafaa (Haklı Savunma)', 'Zaruret (Zorda Kalma) Hali', 'Kuvvet Kullanma', 'Hakkın Kötüye Kullanılması', 'İhkak-ı Hak', 'A', 'Meşru müdafaada saldırgana verilen zarardan dolayı fail ceza almaz ve tazminat ödemez.');
    addQ(3, 13, 2, 'Kişinin kendisini veya yakınını ağır bir tehlikeden kurtarmak için tehlikeyle ilgisi olmayan masum üçüncü bir kişinin malına zarar vermesi durumuna ne ad verilir?', 'Zaruret (Iztırar) Hali', 'Meşru Müdafaa', 'Kuvvet Kullanma', 'Kusurlu Fiil', 'Gabin', 'A', 'Iztırar halinde ceza verilmez ancak verilen maddi zarar hakkaniyet gereği tazmin edilir.');
    addQ(3, 13, 2, 'Kanunda yazılı veya yazısız hiçbir kuralın bulunmaması durumuna ne ad verilir?', 'Hukuk Boşluğu', 'Kanun Boşluğu', 'Açık Boşluk', 'Örtülü Boşluk', 'Hüküm Uyuşmazlığı', 'A', 'Yazılı kural yoksa Kanun Boşluğu; ne yazılı ne yazısız (örf-adet) hiçbir kural yoksa Hukuk Boşluğu vardır. Hakim burada hukuk yaratır.');
    addQ(3, 13, 2, 'Kanunda somut bir olaya uygulanacak kuralın bulunmasına rağmen kanun koyucunun bilerek ve isteyerek ayrıntıyı hakimin takdirine bıraktığı duruma ne denir?', 'Kural İçi Boşluk', 'Kural Dışı Boşluk', 'Örtülü Boşluk', 'Açık Boşluk', 'Gaflet Boşluğu', 'A', 'Kural içi boşlukta hakim takdir yetkisini (Medeni Kanun m. 4) kullanır.');
    addQ(3, 13, 2, 'Ayırt etme gücüne sahip ancak 18 yaşından küçük veya kısıtlı olan kişilerin fiil ehliyeti grubu hangisidir?', 'Sınırlı Ehliyetsizler', 'Tam Ehliyetliler', 'Sınırlı Ehliyetliler', 'Tam Ehliyetsizler', 'Mümeyyiz Olmayanlar', 'A', 'Ayırt etme gücü olan küçükler sınırlı ehliyetsizdir; veli/vasilerinin onayı olmadan borç altına giremezler.');
    addQ(3, 13, 2, 'Ayırt etme gücü hiç bulunmayan (akıl hastası) kişilerin fiil ehliyeti grubu hangisidir?', 'Tam Ehliyetsizler', 'Sınırlı Ehliyetsizler', 'Sınırlı Ehliyetliler', 'Yarım Ehliyetliler', 'Geçici Ehliyetsizler', 'A', 'Ayırt etme gücü olmayanların işlemleri hukuken mutlak olarak hükümsüzdür.');
    addQ(3, 13, 2, 'Kişinin ölümüne kesin gözle bakılacak bir durumda kaybolması halinde (örneğin düşen uçakta bulunması) cesedi bulunamasa bile mülki amir kararıyla öldü sayılmasına ne denir?', 'Ölüm Karinesi', 'Gaiplik', 'Birlikte Ölüm Karinesi', 'Vesayet', 'Terk', 'A', 'Ölümüne kesin gözle bakılan halde en büyük mülki amir kütüğe ölüm kaydı düşer (Ölüm karinesi).');
    addQ(3, 13, 2, 'Ölüm tehlikesi içinde kaybolan bir kimse için gaiplik davası en erken ne kadar süre sonra açılabilir?', 'Olayın üzerinden en az 1 yıl geçtikten sonra', '5 yıl sonra', '6 ay sonra', '10 yıl sonra', '3 yıl sonra', 'A', 'Ölüm tehlikesinde 1 yıl; uzun süredir haber alınamama durumunda ise son haber tarihinden itibaren 5 yıl sonra gaiplik istenebilir.');

    // Level 3: Zor & Detay
    addQ(3, 13, 3, 'Ceza hukukunda suçun kanuniliği ve cezanın şahsiliği ilkeleri gereğince aşağıdakilerden hangisi Anayasal güvence altındadır?', 'Kimse işlendiği zaman kanunun suç saymadığı bir fiilden dolayı cezalandırılamaz ve cezalar şahsidir', 'Ölüm cezası uygulanabilir', 'Genel müsadere uygulanabilir', 'Geriye yürüyen aleyhe ceza konabilir', 'Kolektif ceza verilebilir', 'A', 'Anayasa m. 38: Ceza sorumluluğu şahsidir; genel müsadere ve ölüm cezası verilemez.');
    addQ(3, 13, 3, 'Hukuk kurallarının tarafların serbest iradesiyle aksini kararlaştırabildikleri kurallara ne ad verilir?', 'Yedek (Tamamlayıcı ve Yorumlayıcı) Hukuk Kuralları', 'Emredici Hukuk Kuralları', 'Tanımlayıcı Kurallar', 'Müeyyideli Kurallar', 'İlga Kuralları', 'A', 'Aksini kararlaştırabildiğimiz kurallara yedek hukuk kuralları denir (örneğin borcun ifa yeri belirlenmemişse kanun tamamlar).');
    addQ(3, 13, 3, 'Kanunun açıkça emrettiği ve aksine sözleşme yapılması kesinlikle yasak olan hukuk kurallarına ne denir?', 'Emredici Hukuk Kuralları', 'Yedek Kurallar', 'Yorumlayıcı Kurallar', 'Örfi Kurallar', 'Tavsiye Kurallar', 'A', 'Kamu düzenini ve zayıfları korumak için konulan emredici kuralların aksine hiçbir işlem yapılamaz.');
    addQ(3, 13, 3, 'Bir şahsın bir eşya üzerindeki doğrudan ve herkese karşı ileri sürebildiği mutlak ayni hak hangisidir?', 'Mülkiyet Hakkı', 'Alacak Hakkı', 'İrtifak Hakkı', 'Rehin Hakkı', 'İntifa Hakkı', 'A', 'Mülkiyet hakkı kullanma, yararlanma ve tasarrufta bulunma yetkilerini tam veren ayni haktır.');
    addQ(3, 13, 3, 'Kişiye sıkı sıkıya bağlı haklar (örneğin boşanma davası açma, evlenme, tanıma, vasiyet yapma) kural olarak kim tarafından kullanılır?', 'Yalnızca hak sahibi tarafından bizzat kullanılır, temsilci aracılığıyla kullanılamaz', 'Vasi tarafından', 'Avukat tarafından', 'Hakim tarafından', 'Anne-baba tarafından', 'A', 'Kişiye sıkı sıkıya bağlı haklar bizzat kullanılır, irade devredilemez.');

    addQ(3, 13, 3, 'Haksız fiilin unsurlarından biri olan illiyet bağını (nedensellik bağı) kesen durumlar aşağıdakilerin hangisinde tam olarak verilmiştir?', 'Mücbir sebep, zarar görenin ağır kusuru, üçüncü kişinin ağır kusuru', 'Haksız fiil, rıza, meşru müdafaa', 'Zarar, kusur, hukuka aykırılık', 'Gaiplik, ölüm karinesi, zamanaşımı', 'Defi, itiraz, temerrüt', 'A', 'İlliyet bağı; mücbir sebep, zarar görenin veya üçüncü kişinin kusuru ile kesilir ve sorumluluk kalkar.');
    addQ(3, 13, 3, 'Hukuk düzeninin gerçekleşmesini bir kimsenin iradesine bağladığı ve hukuki sonuç doğuran fiillere ne denir?', 'Hukuki İşlem', 'Hukuki Olay', 'Maddi Fiil', 'Haksız Fiil', 'Gabin', 'A', 'Kişinin iradesiyle hukuki sonuç doğurması hukuki işlemdir (sözleşme, vasiyetname vb.).');
    addQ(3, 13, 3, 'Bir hukuki işlemin kurucu unsurları tam olmasına rağmen kanunun emredici hükümlerine aykırı yapılması sebebiyle baştan itibaren hükümsüz olmasına ne ad verilir?', 'Mutlak Butlan', 'Yokluk', 'Nisbi Butlan', 'Askıda Hükümsüzlük', 'Fesih', 'A', 'Mutlak butlanda işlem ölü doğmuştur; kamu düzenini ilgilendirdiği için hakim re\'sen gözetir.');
    addQ(3, 13, 3, 'Tarafların gerçek iradelerini gizleyerek üçüncü kişileri aldatmak amacıyla görünüşte başka bir işlem yapmaları durumuna ne denir?', 'Muvazaa', 'Hata', 'Hile', 'İkrah (Korkutma)', 'Gabin', 'A', 'Muvazaada taraflar üçüncü kişileri aldatma kastıyla gizli bir anlaşma yaparlar; görünürdeki işlem butlanla sakattır.');
    addQ(3, 13, 3, 'Türk Medeni Kanunu\'na göre bir hakkın kazanılmasında iyi niyet aranırken, bir hakkın kullanılmasında ve borçların ifasında hangi ilke geçerlidir?', 'Dürüstlük Kuralı (Objektif İyiniyet)', 'Sübjektif İyiniyet', 'Ahde Vefa İlkesi', 'Hakkaniyet İlkesi', 'Kusursuz Sorumluluk', 'A', 'TMK m. 2 uyarınca herkes haklarını kullanırken ve borçlarını ifa ederken dürüstlük kuralına uymak zorundadır.');


    // -------------------------------------------------------------------------
    // Subcat 14: 1982 Anayasası ve Temel Esaslar
    // -------------------------------------------------------------------------
    // Level 1: Temel Esaslar
    addQ(3, 14, 1, '1982 Anayasası\'nın 1. maddesine göre Türkiye Devleti bir...', 'Cumhuriyettir', 'Federasyondur', 'Monarşidir', 'Oligarşidir', 'Konfederasyondur', 'A', 'Madde 1: "Türkiye Devleti bir Cumhuriyettir."');
    addQ(3, 14, 1, '1982 Anayasası\'nın 2. maddesinde sayılan Cumhuriyetin temel nitelikleri arasında aşağıdakilerden hangisi yer almaz?', 'Teokratik devlet', 'Demokratik devlet', 'Laik devlet', 'Sosyal devlet', 'Hukuk devleti', 'A', 'Cumhuriyet: Atatürk milliyetçiliğine bağlı, demokratik, laik, sosyal bir hukuk devletidir.');
    addQ(3, 14, 1, '1982 Anayasası\'nın 3. maddesine göre Türkiye Devleti\'nin başkenti neresidir ve milli marşı nedir?', 'Ankara - İstiklal Marşı', 'İstanbul - Mehter Marşı', 'İzmir - İzmir Marşı', 'Konya - Gençlik Marşı', 'Bursa - İstiklal Marşı', 'A', 'Başkenti Ankara, dili Türkçe, marşı İstiklal Marşı, bayrağı al yıldızlı al bayraktır.');
    addQ(3, 14, 1, '1982 Anayasası\'nın 4. maddesine göre anayasanın hangi maddeleri değiştirilemez ve değiştirilmesi teklif dahi edilemez?', 'İlk 3 maddesi', 'İlk 10 maddesi', 'İlk 5 maddesi', 'Bütün maddeleri', 'Sadece 1. maddesi', 'A', 'Madde 4: Anayasanın 1, 2 ve 3. maddeleri değiştirilemez ve değiştirilmesi teklif edilemez.');
    addQ(3, 14, 1, 'Anayasa Mahkemesi (AYM) kaç üyeden oluşur?', '15 üye', '12 üye', '17 üye', '21 üye', '11 üye', 'A', '2017 anayasa değişikliği ile Askeri Yüksek Mahkemeler kapatılınca AYM üye sayısı 17\'den 15\'e indirilmiştir.');
    addQ(3, 14, 1, '1982 Anayasası\'na göre egemenliğin sahibi kimdir ve egemenlik kime aittir?', 'Egemenlik kayıtsız şartsız Milletindir', 'Cumhurbaşkanına aittir', 'Meclise aittir', 'Orduya aittir', 'Hükümete aittir', 'A', 'Madde 6: Egemenlik, kayıtsız şartsız Milletindir. Türk Milleti, egemenliğini yetkili organları eliyle kullanır.');
    addQ(3, 14, 1, 'Türk vatandaşlığına ilişkin hükümlere göre Türk vatandaşı anne veya babadan doğan çocuk hangi statüyü kazanır?', 'Doğumla doğrudan Türk vatandaşı olur', '18 yaşında seçer', 'Yalnızca babası Türk ise olur', 'Bakanlar Kurulu izni gerekir', 'Sınavla alır', 'A', 'Soybağı esasına göre Türk ana veya babadan doğan çocuk doğum anından itibaren Türk vatandaşıdır.');
    addQ(3, 14, 1, 'Temel hak ve hürriyetlerin sınırlandırılmasında anayasanın 13. maddesine göre aşağıdakilerden hangisi şarttır?', 'Sınırlamanın ancak KANUNLA yapılması ve Anayasa\'nın sözüne, özüne, demokratik toplum düzenine aykırı olmaması', 'Cumhurbaşkanlığı Kararnamesi ile sınırlanması', 'Vali genelgesiyle sınırlanması', 'Yönetmelikle sınırlanması', 'Sınırsız olması', 'A', 'Temel hak ve hürriyetler ancak kanunla ve ölçülülük ilkesine uygun olarak sınırlanabilir.');
    addQ(3, 14, 1, 'Kişinin dokunulmazlığı, maddi ve manevi varlığı (yaşama hakkı), din ve vicdan hürriyeti, masumiyet karinesi ve suçların geçmişe yürümezliği hangi tür haklardır?', 'Savaş ve OHAL\'de dahi dokunulamayan "Çekirdek Haklar"', 'Siyasi haklar', 'Sosyal haklar', 'Ekonomik haklar', 'Kamu hakları', 'A', 'Anayasa m. 15 kapsamında sayılan bu haklar savaş ve olağanüstü hallerde dahi durdurulamaz.');
    addQ(3, 14, 1, 'Kişi hak ve ödevleri (Negatif Statü / Koruyucu Haklar) arasında aşağıdakilerden hangisi yer alır?', 'Konut dokunulmazlığı ve kişi hürriyeti', 'Seçme ve seçilme hakkı', 'Çalışma hakkı', 'Sağlık hakkı', 'Dilekçe hakkı', 'A', 'Konut dokunulmazlığı, haberleşme hürriyeti, mülkiyet hakkı negatif statü (koruyucu) haklarıdır.');

    // Level 2: Orta Düzey
    addQ(3, 14, 2, 'Jellinek\'in haklar tasnifine göre "İsteme Hakları" olarak da bilinen ve devletten hizmet talep etmeyi içeren haklar grubu hangisidir?', 'Sosyal ve Ekonomik Haklar (Pozitif Statü Hakları)', 'Kişi Hakları', 'Siyasi Haklar', 'Aktif Statü Hakları', 'Doğal Haklar', 'A', 'Eğitim hakkı, sağlık hakkı, çalışma hakkı devlete ödev yükleyen pozitif statü haklarıdır.');
    addQ(3, 14, 2, 'Vatandaşın devlet yönetimine katılmasını sağlayan "Aktif Statü Hakları" (Katılma Hakları) arasında hangisi yer alır?', 'Seçme-seçilme hakkı, siyasi parti kurma, dilekçe hakkı, kamu hizmetine girme', 'Yaşama hakkı', 'Din hürriyeti', 'Mülkiyet hakkı', 'Seyahat hürriyeti', 'A', 'Siyasi hak ve ödevler kişinin yönetime katılmasını temin eder.');
    addQ(3, 14, 2, 'Türk hukuk sisteminde "kamulaştırma" (istimlak) ne anlama gelir?', 'Devletin kamu yararı amacıyla özel mülkiyetteki taşınmazı bedelini peşin ödeyerek zorla alması', 'Taşınır mallara el koyma', 'Madenlerin işletilmesi', 'Vergi affı', 'Belediye cezası', 'A', 'Kamulaştırma kamu yararı için gayrimenkulün mülkiyetinin kamuya geçirilmesidir.');
    addQ(3, 14, 2, 'Olağanüstü hallerde devletin özel mülkiyetteki taşınır malları bedelini ödemek kaydıyla kullanması veya almasına ne denir?', 'İstimval', 'Kamulaştırma', 'Müsadere', 'Özelleştirme', 'Devletleştirme', 'A', 'Taşınmazlar için kamulaştırma, taşınırlar için istimval kavramı kullanılır.');
    addQ(3, 14, 2, 'Siyasi partilerin kapatılması davası kim tarafından ve nerede açılır?', 'Yargıtay Cumhuriyet Başsavcısı tarafından Anayasa Mahkemesi\'nde', 'Danıştay Başsavcısı', 'Adalet Bakanı', 'TBMM Başkanı', 'Cumhurbaşkanı', 'A', 'Siyasi partilerin temelli kapatılmasına Yargıtay Başsavcısının davası üzerine Anayasa Mahkemesi karar verir.');
    addQ(3, 14, 2, 'Anayasa Mahkemesi bir siyasi partinin kapatılmasına üye tamsayısının kaçta kaç çoğunluğuyla karar verebilir?', '3/5 çoğunluğuyla (en az 10 üye)', 'Salt çoğunluk', '2/3 çoğunluk', 'Oybirliği', '4/5 çoğunluk', 'A', 'Siyasi parti kapatma ve anayasa değişikliği iptalinde 3/5 nitelikli çoğunluk (15 üyenin 10\'u) aranır.');
    addQ(3, 14, 2, 'Türkiye\'de vatandaşların kamu kurumlarıyla ilgili şikayetlerini inceleyen, TBMM\'ye bağlı çalışan "Halk Denetçiliği" kurumu hangisidir?', 'Kamu Denetçiliği Kurumu (Ombudsmanlık)', 'Danıştay', 'Sayıştay', 'Devlet Denetleme Kurulu', 'RTÜK', 'A', '2010 anayasa değişikliği ile getirilen Kamu Denetçiliği Kurumu idarenin eylemlerini insan hakları yönünden denetler.');
    addQ(3, 14, 2, 'Kamu Başdenetçisi (Ombudsman) kim tarafından ve kaç yıllığına seçilir?', 'TBMM tarafından 4 yıllığına seçilir', 'Cumhurbaşkanı tarafından 5 yıl', 'Anayasa Mahkemesi tarafından', 'Adalet Bakanı tarafından', 'Halkoyuyla', 'A', 'Kamu Başdenetçisi TBMM tarafından gizli oyla 4 yıl için seçilir.');
    addQ(3, 14, 2, 'Türkiye\'de genel seçimler kural olarak kaç yılda bir ve hangi organın seçimleriyle birlikte yapılır?', '5 yılda bir - TBMM ve Cumhurbaşkanlığı seçimleri birlikte', '4 yılda bir', '3 yılda bir', '6 yılda bir', '2 yılda bir', 'A', '2017 değişikliğiyle TBMM ve Cumhurbaşkanlığı seçimleri 5 yılda bir aynı gün yapılır.');
    addQ(3, 14, 2, 'Seçimlerde oy kullanma hakkı bakımından aşağıdakilerden hangisi oy kullanamaz?', 'Silah altında bulunan er ve erbaşlar ile askeri öğrenciler', 'Tutuklular', 'Yurt dışındaki Türk vatandaşları', 'Memurlar', '18 yaşını dolduran üniversite öğrencileri', 'A', 'Er ve erbaşlar, askeri öğrenciler ve taksirli suçlar hariç cezaevindeki hükümlüler oy kullanamaz.');

    // Level 3: Zor & Detay
    addQ(3, 14, 3, 'Anayasa değişiklik teklifi TBMM üye tamsayısının en az kaçta kaçı tarafından yazılı olarak verilebilir?', 'En az 1/3 (200 milletvekili)', '1/2', '3/5', '2/3', '1/10', 'A', 'Anayasa değişikliği teklifi için TBMM üye tamsayısının (600) en az 1/3\'ünün (200 vekil) yazılı teklifi şarttır.');
    addQ(3, 14, 3, 'TBMM\'de kabul edilen anayasa değişikliği 3/5 ile 2/3 (360 ile 399 arası) oy almışsa Cumhurbaşkanı ne yapmak ZORUNDADIR?', 'Halkoyuna (Referanduma) sunmak zorundadır', 'Doğrudan onaylar', 'Anayasa Mahkemesi\'ne havale eder', 'İptal eder', 'Geri gönderemez', 'A', '360-399 arası kabul edilen değişiklik doğrudan onaylanamaz; ya veto edilir (meclise iade) ya da zorunlu referanduma götürülür.');
    addQ(3, 14, 3, 'Anayasa değişiklikleri TBMM\'de görüşülürken iki oylama arasında geçmesi zorunlu olan en az 48 saatlik bekleme süresine ne denir?', 'Serinleme (İr規範) Süresi', 'Görüşme Molası', 'Tadil Süresi', 'Nadas Süresi', 'Blokaj', 'A', 'Aceleye getirilmemesi için anayasa değişiklik teklifleri iki defa görüşülür ve araya en az 48 saat serinleme süresi konur.');
    addQ(3, 14, 3, 'Anayasa Mahkemesi anayasa değişikliklerini YALNIZCA hangi yönden denetleyebilir?', 'Yalnızca Şekil (Biçim) bakımından', 'Esas bakımından', 'Hem şekil hem esas', 'Yerindelik bakımından', 'Denetleyemez', 'A', 'AYM anayasa değişikliklerini asla esas (içerik) yönünden denetleyemez; sadece teklif ve oylama çoğunlukları gibi şekil şartlarını denetler.');
    addQ(3, 14, 3, 'Bireysel Başvuru hakkı (Anayasa Şikayeti) Türkiye\'de hangi yıl yapılan anayasa değişikliği ile kabul edilmiştir?', '2010 Anayasa Değişikliği', '1982', '1999', '2004', '2017', 'A', '2010 referandumuyla temel hakları kamu gücü tarafından ihlal edilen bireylere AYM\'ye bireysel başvuru hakkı tanınmıştır.');

    addQ(3, 14, 3, '1982 Anayasası\'na göre siyasi partilerin kapatılması davası kim tarafından ve nerede açılır?', 'Yargıtay Cumhuriyet Başsavcısı tarafından Anayasa Mahkemesi\'nde açılır', 'Adalet Bakanı tarafından Danıştay\'da', 'İçişleri Bakanı tarafından İdare Mahkemesi\'nde', 'TBMM Başkanı tarafından Yargıtay\'da', 'Cumhurbaşkanı tarafından AYM\'de', 'A', 'Siyasi partilerin kapatılması davasını Yargıtay Cumhuriyet Başsavcısı açar; kararı AYM üye tamsayısının 2/3 çoğunluğuyla verir.');
    addQ(3, 14, 3, '1982 Anayasası\'nda \'Sosyal ve Ekonomik Haklar\'ın yerine getirilmesinde devletin sorumluluğunun sınırı Anayasa\'da nasıl belirlenmiştir?', 'Mali kaynaklarının yeterliliği ölçüsünde', 'Sınırsız ve mutlak olarak', 'Yalnızca uluslararası yardımlarla', 'Mahkeme kararları doğrultusunda', 'Seçim dönemlerine bağlı olarak', 'A', 'Anayasa m. 65: Devlet, sosyal ve ekonomik ödevlerini mali kaynaklarının yeterliliği ölçüsünde yerine getirir.');
    addQ(3, 14, 3, '1982 Anayasası\'na göre Cumhurbaşkanlığı Kararnameleri (CBK) kanun ile çatıştığında hangi kural geçerlidir?', 'Kanun hükümleri uygulanır', 'CBK hükümleri uygulanır', 'AYM\'ye başvuruluncaya kadar ikisi de durur', 'Cumhurbaşkanının tercihi geçerli olur', 'Son tarihli olan uygulanır', 'A', 'Anayasa m. 104 uyarınca kanun ile CBK aynı konuda farklı hükümler içerirse kanun hükümleri uygulanır.');
    addQ(3, 14, 3, 'Temel hak ve hürriyetlerin yabancılar için sınırlandırılması Anayasa\'nın 16. maddesine göre neye uygun olarak yapılabilir?', 'Milletlerarası hukuka uygun olarak ancak kanunla', 'Valilik genelgesiyle', 'Yalnızca Dışişleri Bakanı kararıyla', 'Sınırlandırılamaz', 'Yönetmelikle', 'A', 'Anayasa m. 16: Temel hak ve hürriyetler, yabancılar için, milletlerarası hukuka uygun olarak kanunla sınırlanabilir.');
    addQ(3, 14, 3, '1982 Anayasası\'na göre vatandaşlıktan çıkarma ile ilgili karar ve işlemlere karşı hangi kanun yolu kesinlikle kapatılamaz?', 'Yargı yolu (Danıştay denetimi)', 'İdari başvuru', 'TBMM dilekçe komisyonu', 'Sayıştay incelemesi', 'Ombudsman incelemesi', 'A', 'Anayasa m. 66: Vatandaşlıktan çıkarma ile ilgili karar ve işlemlere karşı yargı yolu kapatılamaz.');


    // -------------------------------------------------------------------------
    // Subcat 15: Yasama, Yürütme ve Yargı Organları
    // -------------------------------------------------------------------------
    // Level 1: Temel Organlar
    addQ(3, 15, 1, 'Türkiye Büyük Millet Meclisi\'nin (TBMM) toplam milletvekili sayısı kaçtır?', '600 milletvekili', '550 milletvekili', '450 milletvekili', '500 milletvekili', '650 milletvekili', 'A', '2017 anayasa değişikliğiyle milletvekili sayısı 550\'den 600\'e çıkarılmıştır.');
    addQ(3, 15, 1, 'Milletvekili seçilme yaşı 2017 anayasa değişikliği ile kaça indirilmiştir?', '18 yaş', '21 yaş', '25 yaş', '30 yaş', '17 yaş', 'A', 'Milletvekili seçilme yaşı 25\'ten 18\'e indirilmiştir.');
    addQ(3, 15, 1, 'Cumhurbaşkanı seçilebilmek için kaç yaşını doldurmuş olmak ve hangi eğitim düzeyine sahip olmak şarttır?', '40 yaşını doldurmuş olmak ve Yükseköğrenim (Üniversite) mezunu olmak', '30 yaş - Lise', '35 yaş - Lisans', '50 yaş - Doktora', '40 yaş - İlkokul', 'A', 'Cumhurbaşkanı: 40 yaşını doldurmuş, yükseköğrenim mezunu ve milletvekili seçilme yeterliliğine sahip Türk vatandaşı olmalıdır.');
    addQ(3, 15, 1, 'Cumhurbaşkanı halk tarafından en fazla kaç dönem için ve kaç yıllığına seçilebilir?', '5 yıllığına - En fazla 2 dönem', '4 yıllığına - 3 dönem', '7 yıllığına - 1 dönem', '5 yıllığına - Sınırsız', '6 yıllığına - 2 dönem', 'A', 'Cumhurbaşkanının görev süresi 5 yıldır, bir kimse en fazla iki defa Cumhurbaşkanı seçilebilir.');
    addQ(3, 15, 1, 'Cumhurbaşkanlığı makamının herhangi bir nedenle boşalması halinde yenisi seçilene kadar Cumhurbaşkanlığına kim vekalet eder?', 'Cumhurbaşkanı Yardımcısı', 'TBMM Başkanı', 'Adalet Bakanı', 'En yaşlı milletvekili', 'Genelkurmay Başkanı', 'A', '2017 değişikliğiyle TBMM Başkanının vekalet görevi kaldırılmış, vekalet yetkisi Cumhurbaşkanı Yardımcısına verilmiştir.');
    addQ(3, 15, 1, 'TBMM toplantı yeter sayısı ve karar yeter sayısı kural olarak en az kaç milletvekilidir?', 'Toplantı: 200 vekil (1/3) - Karar: En az 151 vekil (1/4\'ün 1 fazlası)', 'Toplantı: 301 - Karar: 200', 'Toplantı: 150 - Karar: 100', 'Toplantı: 400 - Karar: 300', 'Toplantı: 600 - Karar: 301', 'A', 'Toplantı yeter sayısı üye tamsayısının üçte biri (200); karar yeter sayısı ise toplantıya katılanların salt çoğunluğu olup 151\'den az olamaz.');
    addQ(3, 15, 1, 'Kanun teklif etmeye kimler yetkilidir?', 'Yalnızca Milletvekilleri', 'Cumhurbaşkanı', 'Bakanlar', 'Yargıtay', 'Vatandaşlar', 'A', '2017 anayasa değişikliği ile Bütçe Kanunu hariç (bütçeyi CB teklif eder) kanun teklif etme yetkisi sadece milletvekillerine aittir.');
    addQ(3, 15, 1, 'TBMM tarafından kabul edilen kanunları yayımlamak veya veto ederek meclise geri göndermek için Cumhurbaşkanına tanınan süre kaç gündür?', '15 gün', '30 gün', '7 gün', '60 gün', '10 gün', 'A', 'Cumhurbaşkanı kanunları 15 gün içinde Resmi Gazete\'de yayımlar veya aynı sürede meclise geri gönderir.');
    addQ(3, 15, 1, 'Cumhurbaşkanı aşağıdaki kanunlardan hangisini veto edemez (meclise geri gönderemez)?', 'Bütçe Kanunu', 'Af Kanunu', 'Vergi Kanunu', 'Seçim Kanunu', 'Ceza Kanunu', 'A', 'Cumhurbaşkanı Bütçe Kanunu\'nu veto edemez; onaylamak zorundadır ancak AYM\'ye iptal davası açabilir.');
    addQ(3, 15, 1, 'Milletvekillerinin meclis çalışmalarındaki oy, söz ve düşüncelerinden dolayı hiçbir zaman yargılanamaması güvencesine ne denir?', 'Yasama Sorumsuzluğu (Mutlak Koruma)', 'Yasama Dokunulmazlığı', 'Yargı Muafiyeti', 'Diplomatik Ayrıcalık', 'Bakan Dokunulmazlığı', 'A', 'Yasama sorumsuzluğu ömür boyu sürer ve kaldırılamaz; yasama dokunulmazlığı ise nisbidir ve meclisçe kaldırılabilir.');

    // Level 2: Orta Düzey
    addQ(3, 15, 2, 'Milletvekili dokunulmazlığı kaldırılan bir milletvekili kaç gün içinde Anayasa Mahkemesi\'ne itiraz edebilir ve AYM kaç günde karar verir?', '7 gün içinde itiraz eder - AYM 15 gün içinde kesin karara bağlar', '15 gün - 30 gün', '10 gün - 10 gün', '3 gün - 7 gün', '30 gün - 60 gün', 'A', 'Milletvekili veya başka bir vekil 7 gün içinde AYM\'ye başvurur, AYM 15 günde iptal başvurusunu karara bağlar.');
    addQ(3, 15, 2, 'Hakimler ve Savcılar Kurulu (HSK) kaç üyeden oluşur ve başkanı kimdir?', '13 üyeden oluşur - Başkanı Adalet Bakanı\'dır', '15 üye - AYM Başkanı', '22 üye - Başsavcı', '11 üye - Yargıtay Başkanı', '7 üye - Cumhurbaşkanı', 'A', 'HSK 13 üyeden oluşur; Adalet Bakanı başkan, Adalet Bakan Yardımcısı tabii üyedir. 4 üyeyi CB, 7 üyeyi TBMM seçer.');
    addQ(3, 15, 2, 'Adli yargı kolunun en yüksek temyiz mahkemesi aşağıdakilerden hangisidir?', 'Yargıtay', 'Danıştay', 'Uyuşmazlık Mahkemesi', 'Anayasa Mahkemesi', 'Sayıştay', 'A', 'Adli yargının temyiz mercii Yargıtay, idari yargının temyiz mercii ise Danıştay\'dır.');
    addQ(3, 15, 2, 'Adli ve idari yargı mercileri arasındaki görev ve hüküm uyuşmazlıklarını kesin olarak çözen yüksek mahkeme hangisidir?', 'Uyuşmazlık Mahkemesi', 'Anayasa Mahkemesi', 'Yargıtay', 'Danıştay', 'Sayıştay', 'A', 'Uyuşmazlık Mahkemesi adli ve idari yargı arasındaki uyuşmazlıkları çözer; başkanı AYM üyeleri arasından seçilir.');
    addQ(3, 15, 2, 'TBMM adına kamu kurumlarının tüm gelir, gider ve mallarını denetleyen anayasal mali denetim organı hangisidir?', 'Sayıştay', 'Devlet Denetleme Kurulu', 'Maliye Müfettişliği', 'Merkez Bankası', 'BDDK', 'A', 'Sayıştay yüksek mahkeme sayılmamakla birlikte kararları kesindir ve TBMM adına bütçe denetimi yapar.');
    addQ(3, 15, 2, 'Cumhurbaşkanlığına doğrudan bağlı olan ve Türk Silahlı Kuvvetleri dahil tüm kamu kurumlarında inceleme, araştırma ve denetleme yapan organ hangisidir?', 'Devlet Denetleme Kurulu (DDK)', 'MİT', 'Sayıştay', 'Kamu Denetçiliği', 'MGK', 'A', 'DDK üyelerini ve başkanını Cumhurbaşkanı atar; sadece yargı organlarını denetleyemez.');
    addQ(3, 15, 2, 'Milli Güvenlik Kurulu (MGK) Cumhurbaşkanının başkanlığında kural olarak ne kadar sürede bir toplanır?', '2 ayda bir', 'Her ay', '3 ayda bir', '6 ayda bir', '15 günde bir', 'A', 'MGK iki ayda bir toplanır ve kararları tavsiye niteliğindedir.');
    addQ(3, 15, 2, 'Olağanüstü Hal (OHAL) ilan etme yetkisi kime aittir ve en fazla ne kadar süre için ilan edilebilir?', 'Cumhurbaşkanı ilan eder - En fazla 6 ay için', 'TBMM - 1 yıl', 'İçişleri Bakanı - 3 ay', 'MGK - 6 ay', 'Genelkurmay Başkanı - 3 ay', 'A', 'Cumhurbaşkanı yurdun tamamında veya bir bölgesinde en çok 6 ay süreyle OHAL ilan edebilir ve aynı gün TBMM onayına sunar.');
    addQ(3, 15, 2, 'Cumhurbaşkanının ilan ettiği OHAL süresini uzatma, kısaltma veya kaldırma yetkisi kime aittir?', 'TBMM (Her defasında en fazla 4 ay uzatabilir)', 'Cumhurbaşkanı', 'Anayasa Mahkemesi', 'MGK', 'Bakanlar', 'A', 'TBMM Cumhurbaşkanının talebiyle OHAL süresini her defasında en fazla 4 ayı geçmemek üzere uzatabilir.');
    addQ(3, 15, 2, 'Cumhurbaşkanı hakkında bir suç işlediği iddiasıyla TBMM üye tamsayısının salt çoğunluğunun (301) teklifiyle başlayan süreçte Yüce Divan\'a sevk için kaç oy gerekir?', '2/3 çoğunluk (400 milletvekili)', 'Salt çoğunluk (301)', '3/5 çoğunluk (360)', '3/4 çoğunluk', 'Oybirliği', 'A', 'Teklif: 301, Soruşturma açılması: 360 (3/5), Yüce Divan\'a sevk: 400 (2/3) oy ile gizli oylamayla yapılır.');

    // Level 3: Zor & Detay
    addQ(3, 15, 3, 'Yüce Divan sıfatıyla yargılama yapma görevi hangi yüksek yargı organına aittir?', 'Anayasa Mahkemesi', 'Yargıtay Ceza Genel Kurulu', 'Danıştay', 'Uyuşmazlık Mahkemesi', 'Hakimler ve Savcılar Kurulu', 'A', 'Cumhurbaşkanı, bakanlar, milletvekilleri, kuvvet komutanları görevleriyle ilgili suçlardan AYM\'de Yüce Divan sıfatıyla yargılanır.');
    addQ(3, 15, 3, 'Kanunların Anayasa\'ya şekil ve esas bakımından aykırılığı iddiasıyla doğrudan AYM\'de iptal davası (Soyut Norm Denetimi) açma süresi Resmi Gazete\'de yayımdan itibaren kaç gündür?', '60 gün', '30 gün', '15 gün', '90 gün', '10 gün', 'A', 'İptal davası açma süresi kanunun yayımından itibaren 60 gündür (kanunların şekil bozukluğunda ise süre sadece 10 gündür).');
    addQ(3, 15, 3, 'Anayasa Mahkemesi\'nde doğrudan iptal davası (Soyut Norm Denetimi) açmaya kimler yetkilidir?', 'Cumhurbaşkanı, TBMM\'de en fazla üyeye sahip iki siyasi parti grubu ve TBMM üye tamsayısının en az 1/5\'i (120 vekil)', 'Bütün milletvekilleri', 'Barolar Birliği', 'Yargıtay Başsavcısı', 'Her vatandaş', 'A', 'Anayasa m. 150 uyarınca iptal davası açma tekeli bu üç aktöre aittir.');
    addQ(3, 15, 3, 'Görülmekte olan bir davada mahkemenin uygulayacağı kanun maddesini Anayasa\'ya aykırı bulması veya tarafların iddiasını ciddi bulması üzerine AYM\'ye başvurması yoluna ne denir?', 'Somut Norm Denetimi (İtiraz Yolu / Defi Yolu)', 'Soyut Norm Denetimi', 'Bireysel Başvuru', 'Temyiz', 'İstinaf', 'A', 'İtiraz yolunda mahkeme davayı 5 ay süreyle durdurur ve AYM kararını bekler.');
    addQ(3, 15, 3, 'Cumhurbaşkanlığı Kararnameleri (CBK) hangi konularda kesinlikle ÇIKARILAMAZ?', 'Anayasa\'da münhasıran kanunla düzenlenmesi öngörülen konularda ve kanunda açıkça düzenlenen konularda', 'Üst kademe kamu yöneticisi atamalarında', 'Bakanlıkların kurulmasında', 'Milli Güvenlik Kurulu Genel Sekreterliği teşkilatında', 'Sosyal haklarda', 'A', 'Kanunun açıkça düzenlediği yerde CBK çıkarılamaz; kanun ile CBK çatışırsa kanun hükümleri uygulanır.');

    addQ(3, 15, 3, 'TBMM seçimleri hangi gerekçeyle ve en fazla ne kadar süreyle geriye bırakılabilir (ertelenebilir)?', 'Savaş sebebiyle TBMM kararıyla en fazla 1 yıl süreyle', 'Doğal afet sebebiyle Cumhurbaşkanı kararıyla 6 ay', 'Ekonomik kriz sebebiyle 2 yıl', 'Seçim komisyonu kararıyla 3 ay', 'OHAL sebebiyle 1 yıl', 'A', 'Anayasa m. 78: Savaş sebebiyle yeni seçimlerin yapılmasına imkân görülmezse TBMM seçimlerin 1 yıl geriye bırakılmasına karar verebilir.');
    addQ(3, 15, 3, 'Anayasa Mahkemesi kaç üyeden oluşur ve üyelerin görev süresi kaç yıldır?', '15 üyeden oluşur - Görev süresi 12 yıldır (bir kimse iki defa üye seçilemez)', '11 üye - Ömür boyu', '17 üye - 5 yıl', '12 üye - 10 yıl', '20 üye - 6 yıl', 'A', 'AYM 15 üyeden oluşur (3 üyeyi TBMM, 12 üyeyi CB seçer). Üyeler 12 yıl için seçilir, 65 yaşında emekli olurlar.');
    addQ(3, 15, 3, 'Danıştay üyelerinin seçim dağılımı aşağıdakilerin hangisinde doğru verilmiştir?', 'Üçte üçünü HSK, dörtte birini Cumhurbaşkanı seçer', 'Tamamını HSK seçer', 'Yarısını TBMM, yarısını CB seçer', 'Tamamını Cumhurbaşkanı seçer', 'Dörtte üçünü TBMM seçer', 'A', 'Danıştay üyelerinin 3/4\'ünü Hakimler ve Savcılar Kurulu (HSK), 1/4\'ünü ise Cumhurbaşkanı doğrudan seçer.');
    addQ(3, 15, 3, 'Anayasa Mahkemesi\'ne Bireysel Başvuru için iç hukuk yollarının tüketildiği tarihten itibaren kaç gün içinde başvuru yapılmalıdır?', '30 gün içinde', '60 gün içinde', '15 gün içinde', '90 gün içinde', '6 ay içinde', 'A', 'Temel hak ve özgürlükleri ihlal edilen herkes nihai kararın öğrenilmesinden itibaren 30 gün içinde AYM\'ye bireysel başvuruda bulunabilir.');
    addQ(3, 15, 3, 'Cumhurbaşkanının Yüce Divan\'da yargılanması süreci TBMM\'de en az kaç milletvekilinin teklifiyle başlatılabilir?', 'Üye tamsayısının salt çoğunluğunun (301 vekil) önergesiyle', '150 vekil', '200 vekil', '360 vekil', '400 vekil', 'A', 'Teklif: 301 vekil, Soruşturma açılması kararı: 360 vekil (3/5), Yüce Divan\'a sevk kararı: 400 vekil (2/3) ile alınır.');


// KPSS Vatandaşlık Part 2 (Subcategories 16, 17 - 60 Questions)
// Category: 3 (Vatandaşlık)


    // -------------------------------------------------------------------------
    // Subcat 16: İdare Hukuku ve Türkiye İdari Teşkilatı
    // -------------------------------------------------------------------------
    // Level 1: Temel İdare
    addQ(3, 16, 1, 'Türkiye\'de illerin ve ilçelerin kurulması, kaldırılması, adlarının ve merkezlerinin değiştirilmesi ne ile yapılır?', 'Kanunla', 'Cumhurbaşkanlığı Kararnamesi ile', 'İçişleri Bakanı genelgesiyle', 'Vali kararıyla', 'Yönetmelikle', 'A', 'İller ve ilçeler Anayasa m. 126 uyarınca ancak KANUNLA kurulur ve kaldırılır.');
    addQ(3, 16, 1, 'İl genel idaresinin başında bulunan, hem devletin hem de Cumhurbaşkanının ildeki temsilcisi olan mülki amir kimdir?', 'Vali', 'Kaymakam', 'Belediye Başkanı', 'İl Genel Meclisi Başkanı', 'Garnizon Komutanı', 'A', 'Vali ilde Cumhurbaşkanının ve devletin temsilcisi olup istisnai memurdur ve Cumhurbaşkanı kararıyla atanır.');
    addQ(3, 16, 1, 'İlçede Cumhurbaşkanının idari yürütme vasıtası olan mülki idare amiri kimdir?', 'Kaymakam', 'Vali', 'Belediye Başkanı', 'Muhtar', 'Yazı İşleri Müdürü', 'A', 'Kaymakam güvenceli meslek memurudur ve Cumhurbaşkanı onayı ile atanır.');
    addQ(3, 16, 1, 'Aşağıdakilerden hangisi "Mahalli İdareler" (Yerel Yönetimler) arasında yer alır?', 'İl Özel İdaresi, Belediye, Büyükşehir Belediyesi, Köy', 'Valilik', 'Kaymakamlık', 'Bakanlıklar', 'Bölge Müdürlükleri', 'A', 'Anayasa m. 127\'de sayılan 4 yerel yönetim: İl Özel İdaresi, Belediye, Büyükşehir Belediyesi ve Köydür.');
    addQ(3, 16, 1, 'Belediye kurulabilmesi için bir yerleşim yerinin nüfusunun en az kaç olması kanunen zorunludur?', '5.000', '2.000', '10.000', '50.000', '750.000', 'A', '5393 sayılı Belediye Kanunu\'na göre nüfusu 5.000 ve üzerinde olan yerleşim yerlerinde Cumhurbaşkanı kararıyla belediye kurulabilir.');
    addQ(3, 16, 1, 'Köy kurulabilmesi için nüfus sınırları hangi aralıkta olmalıdır?', 'Nüfusu 150 ile 2.000 arasında olan yerleşim yerleri', '0-100', '2.000-5.000', '5.000-10.000', '100-500', 'A', 'Köy Kanunu\'na göre nüfusu 2.000\'den az, 150\'den fazla olan yerleşim yerleri köydür.');
    addQ(3, 16, 1, 'Bir köyün kurulması, sınırlarının tespiti veya ayrılması hangi makamın kararıyla gerçekleşir?', 'İçişleri Bakanlığı kararıyla', 'Kanunla', 'Vali kararıyla', 'Kaymakam kararıyla', 'Muhtar kararıyla', 'A', 'Köyler İçişleri Bakanlığı\'nın idari kararı ile kurulur ve sınırları belirlenir.');
    addQ(3, 16, 1, 'Köyün karar organı olup köyün tüm seçmenlerinden oluşan doğrudan demokrasi organı hangisidir?', 'Köy Derneği', 'İhtiyar Meclisi', 'Muhtarlık', 'Salma Komisyonu', 'Encümen', 'A', 'Köy Derneği köydeki kadın-erkek tüm seçmenlerden oluşur; muhtarı ve ihtiyar heyetini seçer.');
    addQ(3, 16, 1, '657 sayılı Devlet Memurları Kanunu\'na göre aday memurluk süresi en az ve en çok ne kadar olabilir?', 'En az 1 yıl - En çok 2 yıl', 'En az 6 ay - En çok 1 yıl', 'En az 2 yıl - En çok 3 yıl', 'Süre sınırı yoktur', '6 ay', 'A', 'Aday memurluk süresi 1 yıldan az, 2 yıldan çok olamaz.');
    addQ(3, 16, 1, 'Devlet memurlarına uygulanan disiplin cezaları arasında aşağıdakilerden hangisi yer almaz?', 'Hapis cezası veya maaştan para kesme dışı para cezası', 'Uyarma', 'Kınama', 'Aylıktan Kesme', 'Kademe İlerlemesinin Durdurulması', 'A', '657 m. 125\'te 5 disiplin cezası vardır: Uyarma, Kınama, Aylıktan Kesme, Kademe İlerlemesinin Durdurulması, Devlet Memurluğundan Çıkarma.');

    // Level 2: Orta Düzey
    addQ(3, 16, 2, 'Merkezi idarenin taşradaki amirlerine (Valiye) merkeze danışmadan devlet adına doğrudan karar alıp uygulama yetkisi tanıyan anayasal ilke hangisidir?', 'Yetki Genişliği İlkesi', 'Yerinden Yönetim', 'İdarenin Bütünlüğü', 'Hiyerarşi', 'İdari Vesayet', 'A', 'Yetki genişliği sadece İl İdaresine ve yalnızca VALİYE tanınmış bir anayasal ayrıcalıktır.');
    addQ(3, 16, 2, 'Devlet tüzel kişiliği içinde üst makamın alt makama emir ve talimat verme yetkisine ne ad verilir?', 'Hiyerarşi', 'İdari Vesayet', 'Yetki Genişliği', 'Yetki Devri', 'İmza Devri', 'A', 'Aynı kamu tüzel kişiliği içindeki ast-üst ilişkisi Hiyerarşi ilişkisidir (Bakan-Vali, Rektör-Dekan).');
    addQ(3, 16, 2, 'Merkezi idarenin yerel yönetimler üzerindeki kanunla sınırlı denetim ve gözetim yetkisine ne ad verilir?', 'İdari Vesayet', 'Hiyerarşik Denetim', 'Yargısal Denetim', 'Mali Teftiş', 'İç Denetim', 'A', 'Farklı kamu tüzel kişilikleri arasındaki denetime İdari Vesayet denir (İçişleri Bakanı\'nın Belediye Başkanını denetlemesi).');
    addQ(3, 16, 2, 'İçişleri Bakanı görevleriyle ilgili bir suç sebebiyle hakkında soruşturma açılan bir belediye başkanını ne yapabilir?', 'Geçici bir tedbir olarak görevden uzaklaştırabilir', 'Belediye başkanlığını kesin olarak düşürür', 'Hapse atar', 'Belediyeyi kapatır', 'Hiçbir şey yapamaz', 'A', 'İçişleri Bakanı sadece geçici olarak görevden uzaklaştırabilir; başkanlığın kesin düşmesine Danıştay karar verir.');
    addQ(3, 16, 2, 'Kamu kurumu niteliğindeki meslek kuruluşlarına (Barolar, Tabip Odaları, Ticaret Odaları) aşağıdakilerden hangisi örnek gösterilebilir?', 'Türkiye Barolar Birliği ve TMMOB', 'Siyasi partiler', 'Dernekler', 'Vakıflar', 'Sendikalar', 'A', 'Kamu tüzel kişiliğine sahip, kanunla kurulan meslek örgütleri anayasal kamu kurumu niteliğindedir.');
    addQ(3, 16, 2, 'İdare mahkemelerinin yetki sınırlarını aşan veya ülke çapında uygulanan yönetmelik ve idari işlemlerin ilk derece mahkemesi ve temyiz mercii neresidir?', 'Danıştay', 'Yargıtay', 'Sayıştay', 'Anayasa Mahkemesi', 'Bölge İdare Mahkemesi', 'A', 'Ülke çapında uygulanan düzenleyici işlemlere karşı davalar doğrudan Danıştay\'da açılır.');
    addQ(3, 16, 2, 'İdarenin hukuka aykırı eylem ve işlemlerinden dolayı hakları ihlal edilenlerin açtığı, zararın tazminini talep eden davaya ne denir?', 'Tam Yargı Davası (Tazminat Davası)', 'İptal Davası', 'Tespit Davası', 'Ceza Davası', 'Alacak Davası', 'A', 'İdari işlemin ortadan kaldırılması için İptal Davası; maddi-manevi zararın ödenmesi için Tam Yargı Davası açılır.');
    addQ(3, 16, 2, 'İdarenin kusuru olmasa dahi kamu hizmetinin yürütülmesi sırasında bireylerin uğradığı özel ve olağandışı zararları karşılamak zorunda olması ilkesine ne denir?', 'Kusursuz Sorumluluk (Fedakarlığın Denkleştirilmesi / Sosyal Risk)', 'Kusur Sorumluluğu', 'Hizmet Kusuru', 'Mücbir Sebep', 'Gabin', 'A', 'Terör eylemleri veya riskli kamu faaliyetlerinde idare kusursuz sorumluluk ilkesi gereği zararı tazmin eder.');
    addQ(3, 16, 2, 'Devlet Denetleme Kurulu (DDK) başkan ve üyeleri kim tarafından atanır?', 'Cumhurbaşkanı tarafından', 'TBMM tarafından', 'Danıştay tarafından', 'Sayıştay tarafından', 'Bakanlar Kurulu', 'A', 'DDK Cumhurbaşkanlığına bağlıdır; başkan ve üyelerini doğrudan Cumhurbaşkanı belirler.');
    addQ(3, 16, 2, 'Kamusal bir malın (örneğin yol, köprü, orman) özel mülkiyete konu olamaması ve zaman aşımıyla kazanılamaması bu malların hangi niteliğindendir?', 'Kamu Mallarının Dokunulmazlığı ve Devredilemezliği', 'Özel mülkiyet olması', 'Haczedilebilir olması', 'Vergilendirilebilir olması', 'İpotek konabilmesi', 'A', 'Kamu malları haczedilemez, satılamaz, tapu tesciline tabi değildir ve zaman aşımıyla kazanılamaz.');

    // Level 3: Zor & Detay
    addQ(3, 16, 3, 'Üst kademe kamu yöneticilerinin (Bakan yardımcıları, Valiler, Rektörler, Büyükelçiler) görev süresi kural olarak ne kadardır?', 'Atandıkları Cumhurbaşkanının görev süresini aşamaz (Cumhurbaşkanıyla birlikte biter)', 'Ömür boyu', '65 yaşına kadar', '10 yıl', '3 yıl', 'A', '3 sayılı CBK uyarınca üst kademe kamu yöneticilerinin görev süresi atayan Cumhurbaşkanının görev süresiyle sınırlıdır.');
    addQ(3, 16, 3, 'İdare hukukunda "Fonksiyon Gaspı" ne anlama gelir?', 'İdarenin yasama veya yargı organının görev alanına giren bir konuda karar alması', 'Bir memurun başka memurun yetkisini kullanması', 'Sürenin aşılması', 'Yetki tecavüzü', 'Şekil bozukluğu', 'A', 'İdare meclisin yerine kanun koyar veya mahkemenin yerine ceza keserse işlem yoklukla sakattır (Fonksiyon Gaspı).');
    addQ(3, 16, 3, 'Bir idari işlemin unsurları (Yetki, Şekil, Sebep, Konu, Amaç) arasında "Amaç" unsuru daima ne olmak zorundadır?', 'Kamu Yararı', 'Hazine geliri', 'Bürokrasiyi hızlandırmak', 'Kişisel menfaat', 'Mülkiyet hakkı', 'A', 'Bütün idari işlemlerin genel ve nihai amacı istisnasız kamu yararıdır; aksi takdirde amaç yönünden iptal edilir.');
    addQ(3, 16, 3, 'Kamu Denetçiliği Kurumu (Ombudsman) hangi kurumların eylemlerini denetleme yetkisine sahip DEĞİLDİR?', 'Cumhurbaşkanının tek başına yaptığı işlemler ile Yargı yetkisinin kullanılmasına ilişkin kararlar', 'Belediyeler', 'Bakanlıklar', 'Üniversiteler', 'İl Özel İdareleri', 'A', 'Ombudsmanlık kanununa göre yargı organlarının kararları ve TSK\'nın askeri operasyonları denetim dışındadır.');
    addQ(3, 16, 3, 'Türkiye Radyo ve Televizyon Üst Kurulu (RTÜK) üyeleri kim tarafından seçilir?', 'TBMM tarafından (siyasi parti gruplarının güç oranına göre)', 'Cumhurbaşkanı tarafından', 'Danıştay tarafından', 'İletişim Başkanlığı tarafından', 'TRT tarafından', 'A', 'RTÜK\'ün 9 üyesi TBMM Genel Kurulu\'nda siyasi parti gruplarının milletvekili sayısıyla orantılı olarak seçilir.');

    addQ(3, 16, 3, 'Merkezi idarenin taşra teşkilatında yalnızca il idaresine (vali) tanınan, merkeze danışmadan devlet adına karar alabilme yetkisine ne ad verilir?', 'Yetki Genişliği (Tevsi-i Mezuniyet)', 'Yetki Devri', 'İmza Devri', 'İdari Vesayet', 'Hiyerarşik Yetki', 'A', 'Yetki genişliği sadece İl İdaresinde Valiye tanınmıştır. Vali harcama yapamaz, gelir toplayamaz ama kamu düzeni kararlarını merkez adına re\'sen alır.');
    addQ(3, 16, 3, 'Devlet veya kamu tüzel kişilerinin kamu yararı amacıyla özel mülkiyette bulunan taşınmaz mallara bedelini peşin ödemek kaydıyla el koymasına ne ad verilir?', 'Kamulaştırma (İstimlak)', 'İstimval', 'Devletleştirme', 'Müsadere', 'Kamulaştırmasız El Atma', 'A', 'Kamulaştırma taşınmazlara peşin bedelle el koymadır. Taşınır mallara el koymaya ise istimval denir.');
    addQ(3, 16, 3, 'İdarenin hukuki sorumluluğunda idarenin hiçbir kusuru bulunmasa dahi ortaya çıkan zararı tazmin etmesini gerektiren ilkelere ne ad verilir?', 'Kusursuz Sorumluluk (Risk ve Fedakarlığın Denkleştirilmesi)', 'Hizmet Kusuru', 'Kişisel Kusur', 'Ağır İhmal', 'Görev Kusuru', 'A', 'İdarenin tehlike yaratan faaliyetlerinde (risk) veya kamu yararına fedakarlık durumunda kusuru olmasa da zarar tazmin edilir.');
    addQ(3, 16, 3, 'İdari yargıda kural olarak genel iptal ve tam yargı davası açma süresi İdare Mahkemelerinde ve Danıştay\'da kaç gündür?', '60 gün', '30 gün', '15 gün', '90 gün', '1 yıl', 'A', 'İYUK m. 7 uyarınca dava açma süresi Danıştay ve İdare Mahkemelerinde 60 gün, Vergi Mahkemelerinde ise 30 gündür.');
    addQ(3, 16, 3, 'Kamu Denetçiliği Kurumu (Ombudsmanlık) kime bağlı olarak çalışır ve Başdenetçiyi kim seçer?', 'TBMM Başkanlığına bağlıdır - Başdenetçiyi TBMM seçer', 'Cumhurbaşkanlığına bağlıdır - CB seçer', 'Adalet Bakanlığına bağlıdır - HSK seçer', 'Danıştay\'a bağlıdır - Danıştay seçer', 'İçişleri Bakanlığına bağlıdır', 'A', 'Kamu Denetçiliği TBMM Başkanlığına bağlı olup idarenin her türlü eylem ve işlemini insan hakları yönünden inceler.');


    // -------------------------------------------------------------------------
    // Subcat 17: Güncel Bilgiler ve Uluslararası Kuruluşlar
    // -------------------------------------------------------------------------
    // Level 1: Temel Bilgiler
    addQ(3, 17, 1, 'Birleşmiş Milletler (BM) Teşkilatı\'nın genel merkezi hangi şehirdedir?', 'New York (ABD)', 'Cenevre', 'Brüksel', 'Paris', 'Londra', 'A', '1945\'te kurulan BM\'nin ana merkezi New York\'tadır.');
    addQ(3, 17, 1, 'Birleşmiş Milletler Güvenlik Konseyi\'nde (BMGK) veto yetkisine sahip 5 daimi üye ülke (FİRÇA) hangileridir?', 'Fransa, İngiltere, Rusya, Çin, ABD', 'Almanya, Japonya, İtalya, Türkiye, Kanada', 'Hindistan, Brezilya, Rusya, Çin, Güney Afrika', 'ABD, Almanya, İngiltere, Fransa, Japonya', 'Türkiye, Rusya, Çin, ABD, İngiltere', 'A', 'BMGK daimi üyeleri FİRÇA şifresiyle: Fransa, İngiltere, Rusya, Çin ve ABD\'dir.');
    addQ(3, 17, 1, 'Kuzey Atlantik Savunma Paktı\'nın (NATO) genel merkezi neresidir?', 'Brüksel (Belçika)', 'Washington', 'Paris', 'Berlin', 'Strazburg', 'A', 'NATO\'nun siyasi ve askeri merkezi Belçika\'nın başkenti Brüksel\'dedir.');
    addQ(3, 17, 1, 'Türk Devletleri Teşkilatı\'nın (eski adıyla Türk Keneşi) daimi sekretaryası hangi şehirdedir?', 'İstanbul (Türkiye)', 'Ankara', 'Bakü', 'Taşkent', 'Astana', 'A', '2009 Nahçıvan Anlaşması ile kurulan Türk Devletleri Teşkilatı genel sekreterliği İstanbul\'dadır.');
    addQ(3, 17, 1, 'UNESCO (Birleşmiş Milletler Eğitim, Bilim ve Kültür Örgütü) genel merkezi neresidir?', 'Paris (Fransa)', 'Roma', 'Cenevre', 'Viyana', 'Madrid', 'A', 'Dünya kültür mirası listesini belirleyen UNESCO\'nun merkezi Paris\'tedir.');
    addQ(3, 17, 1, 'Avrupa İnsan Hakları Mahkemesi (AİHM) hangi şehirde bulunmaktadır ve hangi örgüte bağlıdır?', 'Strazburg (Fransa) - Avrupa Konseyi\'ne bağlıdır', 'Brüksel - Avrupa Birliği', 'Lahey - BM', 'Lüksemburg - NATO', 'Cenevre - Kızılhaç', 'A', 'AİHM Avrupa Konseyi bünyesinde çalışır ve merkezi Strazburg\'dadır.');
    addQ(3, 17, 1, 'Petrol İhraç Eden Ülkeler Örgütü\'nün (OPEC) genel merkezi hangi şehirdedir?', 'Viyana (Avusturya)', 'Riyad', 'Bağdat', 'Kuveyt', 'Dubai', 'A', 'OPEC üyesi olmamasına rağmen örgütün genel merkezi Avusturya Viyana\'dadır.');
    addQ(3, 17, 1, 'İslam İşbirliği Teşkilatı\'nın (İİT) genel merkezi neresidir?', 'Cidde (Suudi Arabistan)', 'Mekke', 'Kahire', 'Riyad', 'İstanbul', 'A', '1969 Mescid-i Aksa kundaklaması sonrası kurulan İİT\'nin merkezi Cidde\'dir.');
    addQ(3, 17, 1, 'Dünya Sağlık Örgütü (WHO), Dünya Ticaret Örgütü (WTO) ve Uluslararası Çalışma Örgütü (ILO) gibi BM uzmanlık kuruluşlarının ortak merkezi neresidir?', 'Cenevre (İsviçre)', 'New York', 'Paris', 'Brüksel', 'Londra', 'A', 'İsviçre Cenevre kenti uluslararası örgütlerin diplomasi merkezidir.');
    addQ(3, 17, 1, 'Türkiye\'nin kurucusu olduğu ve 8 gelişmekte olan Müslüman ülkenin ekonomik iş birliği için kurduğu örgüt (D-8) nerede kurulmuştur?', 'İstanbul (1997)', 'Tahran', 'Kahire', 'Cakarta', 'Kuala Lumpur', 'A', 'Necmettin Erbakan öncülüğünde 1997\'de Çırağan Sarayı\'nda D-8 kurulmuştur.');

    // Level 2: Orta Düzey
    addQ(3, 17, 2, 'Avrupa Birliği\'nin yürütme organı olan ve başkanı üye ülkelerce seçilen organ hangisidir?', 'Avrupa Komisyonu', 'Avrupa Parlamentosu', 'Avrupa Konseyi', 'Avrupa Adalet Divanı', 'Avrupa Merkez Bankası', 'A', 'Avrupa Komisyonu AB\'nin kanun tasarılarını hazırlayan ve bütçeyi yöneten icra organıdır.');
    addQ(3, 17, 2, '2024 yılında Avrupa Birliği dönem başkanlığını yürüten ve AB\'nin son genişleme ülkesi olan 28. (Brexit sonrası 27.) üye kimdir?', 'Hırvatistan', 'Sırbistan', 'Kuzey Makedonya', 'Karadağ', 'Arnavutluk', 'A', 'Hırvatistan 2013\'te AB\'ye katılan son ülkedir; İngiltere 2020\'de ayrılmıştır.');
    addQ(3, 17, 2, 'Türkiye\'nin ilk yerli ve milli haberleşme uydusu hangisidir?', 'Türksat 6A', 'Türksat 5A', 'Türksat 5B', 'Göktürk-1', 'Rasat', 'A', 'TÜBİTAK UZAY ve ASELSAN öncülüğünde üretilen Türksat 6A 2024\'te uzaya fırlatılmıştır.');
    addQ(3, 17, 2, 'Türkiye\'nin uzaya giden ilk Türk astronotu kimdir ve hangi görevde yer almıştır?', 'Alper Gezeravcı - Axiom-3 (Ax-3) Görevi', 'Tuva Cihangir Atasever', 'Vecihi Hürkuş', 'Selçuk Bayraktar', 'Nuri Demirağ', 'A', 'Alper Gezeravcı Ocak 2024\'te Uluslararası Uzay İstasyonu\'nda (ISS) 13 bilimsel deney yapmıştır.');
    addQ(3, 17, 2, 'UNESCO Dünya Mirası Listesi\'ne Türkiye\'den kaydedilen "Tarihin Sıfır Noktası" kabul edilen dünyanın en eski kült yapısı hangisidir?', 'Şanlıurfa Göbeklitepe', 'Çatalhöyük', 'Hattuşa', 'Nemrut Dağı', 'Efes', 'A', 'MÖ 10.000\'lere dayanan Göbeklitepe yerleşik inanç sisteminin ilk anıtsal tapınağıdır.');
    addQ(3, 17, 2, '2023 yılında UNESCO Dünya Mirası Listesi\'ne Türkiye\'den 20. ve 21. varlık olarak dahil edilen yerler hangileridir?', 'Gordion Antik Kenti (Ankara) ve Anadolu\'nun Ahşap Hipostil Camileri', 'Göbeklitepe ve Efes', 'Troya ve Bergama', 'Afrodisias ve Ani Harabeleri', 'Arslantepe ve Nemrut', 'A', 'Ankara Polatlı\'daki Gordion 20., 5 ahşap camimiz ise 21. mirasımız olmuştur.');
    addQ(3, 17, 2, 'Nobel Kimya Ödülü\'nü 2015 yılında DNA onarımı mekanizmaları üzerine yaptığı çalışmalarla kazanan ilk Türk bilim insanı kimdir?', 'Prof. Dr. Aziz Sancar', 'Prof. Dr. Oktay Sinanoğlu', 'Prof. Dr. Cahit Arf', 'Prof. Dr. Gazi Yaşargil', 'Prof. Dr. Celal Şengör', 'A', 'Aziz Sancar Nobel Kimya Ödülü\'nü alarak Türk bayrağını gururla dalgalandırmıştır.');
    addQ(3, 17, 2, 'Beyin cerrahisi alanında yüzyılın cerrahı seçilen ve mikrocerrahinin kurucusu kabul edilen Türk tıp insanı kimdir?', 'Prof. Dr. Gazi Yaşargil', 'Prof. Dr. Mehmet Öz', 'Prof. Dr. Canan Dağdeviren', 'Prof. Dr. İhsan Doğramacı', 'Prof. Dr. Münci Kalayoğlu', 'A', 'Gazi Yaşargil mikronöroşirürjinin babası kabul edilmektedir.');
    addQ(3, 17, 2, 'Türkiye\'nin ilk milli fırkateyni olan ve MİLGEM projesi kapsamında denize indirilen TCG İstanbul hangi sınıf gemidir?', 'İ Sınıfı Fırkateyn', 'Ada Sınıfı Korvet', 'TF-2000 Muhrip', 'Barbaros Sınıfı', 'Yavuz Sınıfı', 'A', 'TCG İstanbul MİLGEM projesinin 5. gemisi ve ilk yerli fırkateynidir.');
    addQ(3, 17, 2, 'Türk Silahlı Kuvvetleri\'nin en büyük savaş gemisi ve dünyanın ilk SİHA gemisi kabul edilen amfibi hücum gemisi hangisidir?', 'TCG Anadolu', 'TCG Derya', 'TCG İstanbul', 'TCG Bayraktar', 'TCG Heybeliada', 'A', 'TCG Anadolu Bayraktar TB3 ve Kızılelma gibi insansız hava araçlarının konuşlanabildiği sancak gemimizdir.');

    // Level 3: Zor & Detay
    addQ(3, 17, 3, '2024 yılında NATO\'ya 31. ve 32. üye olarak katılan İskandinav ülkeleri sırasıyla hangileridir?', '31. Üye Finlandiya - 32. Üye İsveç', 'İsveç - Norveç', 'Ukrayna - Gürcistan', 'Finlandiya - Danimarka', 'Avusturya - İsviçre', 'A', 'Rusya-Ukrayna savaşı sonrası Finlandiya Nisan 2023\'te 31., İsveç ise Mart 2024\'te 32. NATO üyesi olmuştur.');
    addQ(3, 17, 3, 'Uluslararası Para Fonu (IMF) ve Dünya Bankası hangi uluslararası konferans sonucu kurulmuştur?', '1944 Bretton Woods Konferansı', '1945 Yalta', '1919 Versailles', '1975 Helsinki', '1992 Rio Zirvesi', 'A', 'Küresel mali sistemi düzenlemek için ABD New Hampshire\'da toplanan Bretton Woods ikizleri kurmuştur.');
    addQ(3, 17, 3, 'Avrupa Konseyi\'nin en üst karar organı olan ve üye ülkelerin Dışişleri Bakanlarından oluşan organ hangisidir?', 'Bakanlar Komitesi', 'Parlamenterler Meclisi', 'Kongre', 'Divan', 'AİHM', 'A', 'Bakanlar Komitesi Avrupa Konseyi\'nin karar alma organıdır ve AİHM kararlarının uygulanmasını denetler.');
    addQ(3, 17, 3, 'Karadeniz Ekonomik İşbirliği Örgütü (KEİ) hangi bildiriyle ve hangi ülkede kurulmuştur?', '1992 İstanbul Zirve Bildirisi ile Türkiye öncülüğünde', 'Atina', 'Moskova', 'Bükreş', 'Kiev', 'A', 'Turgut Özal öncülüğünde 1992\'de kurulan KEİ\'nin daimi sekretaryası İstanbul\'dadır.');
    addQ(3, 17, 3, 'Şanghay İşbirliği Örgütü\'nde (ŞİÖ) Türkiye\'nin resmi statüsü nedir?', 'Diyalog Ortağı', 'Tam Üye', 'Gözlemci Üye', 'Aday Üye', 'Onursal Üye', 'A', 'Türkiye 2012 yılında Şanghay İşbirliği Örgütü\'ne "Diyalog Ortağı" olarak kabul edilmiştir.');

    addQ(3, 17, 3, 'Birleşmiş Milletler (BM) Güvenlik Konseyi\'nde veto yetkisine sahip 5 daimi üye ülke (FÇİRA) aşağıdakilerin hangisinde tam olarak verilmiştir?', 'Fransa, Çin, İngiltere, Rusya, ABD', 'Almanya, Çin, Rusya, ABD, Japonya', 'Türkiye, ABD, Rusya, İngiltere, Fransa', 'Fransa, İtalya, İngiltere, Çin, ABD', 'Kanada, ABD, Rusya, İngiltere, Çin', 'A', 'BM Güvenlik Konseyi\'nin veto hakkı bulunan 5 daimi üyesi FÇİRA kısaltmasıyla bilinen Fransa, Çin, İngiltere, Rusya ve ABD\'dir.');
    addQ(3, 17, 3, 'Kuzey Atlantik Antlaşması Örgütü (NATO) genel merkezi nerede bulunmaktadır ve Türkiye hangi yıl örgüte üye olmuştur?', 'Brüksel (Belçika) - 1952 yılında', 'Cenevre - 1949 yılında', 'New York - 1950 yılında', 'Londra - 1955 yılında', 'Paris - 1960 yılında', 'A', 'NATO 1949\'da kurulmuş, genel merkezi Brüksel\'dedir. Türkiye Kore Savaşı\'ndaki başarısının ardından 1952 yılında Yunanistan ile birlikte üye olmuştur.');
    addQ(3, 17, 3, 'Avrupa İnsan Hakları Mahkemesi (AİHM) hangi uluslararası kuruluşun bünyesinde faaliyet gösterir ve merkezi neresidir?', 'Avrupa Konseyi bünyesindedir - Strazburg (Fransa)', 'Avrupa Birliği bünyesinde - Brüksel', 'Birleşmiş Milletler bünyesinde - Cenevre', 'Lahey Adalet Divanı - Hollanda', 'UNESCO - Paris', 'A', 'AİHM, 1949\'da kurulan Avrupa Konseyi\'nin yargı organıdır ve Strazburg\'da bulunur.');
    addQ(3, 17, 3, 'Türkiye\'nin ev sahipliğinde İstanbul\'da kurulan ve 8 gelişmekte olan Müslüman ülkenin oluşturduğu ekonomik işbirliği örgütü hangisidir?', 'D-8 (Gelişen Sekiz Ülke)', 'G-20', 'OPEC', 'Şanghay İşbirliği Örgütü', 'Arap Birliği', 'A', 'D-8, 1997 yılında Necmettin Erbakan öncülüğünde İstanbul\'da kurulmuştur (Türkiye, İran, Pakistan, Bangladeş, Malezya, Endonezya, Mısır, Nijerya).');
    addQ(3, 17, 3, 'UNESCO Dünya Kültür Mirası Listesi\'nde yer alan ve \'Tarihin Sıfır Noktası\' olarak adlandırılan dünyanın en eski tapınak kompleksi Göbeklitepe hangi ilimizdedir?', 'Şanlıurfa', 'Gaziantep', 'Mardin', 'Diyarbakır', 'Adıyaman', 'A', 'Göbeklitepe MÖ 10.000\'e dayanan ve Klaus Schmidt tarafından kazılan Şanlıurfa ilimizdeki neolitik tapınak kompleksidir.');


};
