// KPSS Coğrafya Complete Bank (150 Questions - 5 Subcategories, 3 Levels, 10 Q per level)
module.exports = function (addQ) {
// KPSS Coğrafya Authentic Questions Bank (150 Questions - 5 Subcategories, 3 Levels, 10 Q per level)
// Category: 2 (Coğrafya)


    // -------------------------------------------------------------------------
    // Subcat 8: Türkiye Coğrafi Konumu ve Etkileri
    // -------------------------------------------------------------------------
    // Level 1: Temel Bilgiler
    addQ(2, 8, 1, 'Türkiye hangi matematiksel koordinatlar (paralel ve meridyen) arasında yer alır?', '36°-42° Kuzey paralelleri, 26°-45° Doğu meridyenleri', '26°-45° Kuzey, 36°-42° Doğu', '30°-40° Güney, 20°-40° Batı', '36°-42° Güney, 26°-45° Doğu', '10°-20° Kuzey, 30°-50° Doğu', 'A', 'Türkiye 36°-42° Kuzey paralelleri ile 26°-45° Doğu meridyenleri arasında yer alır.');
    addQ(2, 8, 1, 'Türkiye\'nin en doğusu (Iğdır-Dilucu) ile en batısı (Gökçeada-İnceburun) arasında kaç dakikalık yerel saat farkı vardır?', '76 dakika', '60 dakika', '45 dakika', '90 dakika', '19 dakika', 'A', '45 - 26 = 19 meridyen farkı vardır. 19 x 4 = 76 dakika yerel saat farkı bulunur.');
    addQ(2, 8, 1, 'Türkiye\'de güneyden kuzeye doğru gidildikçe çizgisel hızın azalması ve yerçekiminin artması neyin sonucudur?', 'Dünyanın küresel şeklinin (Enlem etkisi)', 'Özel konumun', 'Yükseltinin', 'Dağların uzanış yönünün', 'Denizelliğin', 'A', 'Ekvatordan kutuplara gidildikçe çizgisel hız azalır, kutuplardan basık olduğu için yerçekimi artar.');
    addQ(2, 8, 1, 'Türkiye\'de dağların güneye bakan yamaçlarının kuzey yamaçlarına göre daha sıcak olması durumu aşağıdakilerden hangisidir?', 'Bakı etkisi', 'Karasallık', 'Yükselti', 'Nemlilik', 'Basınç', 'A', 'Türkiye Kuzey Yarımküre Yengeç Dönencesi\'nin kuzeyinde olduğu için güney yamaçlar daima güneşi daha dik alır.');
    addQ(2, 8, 1, '21 Haziran tarihinde Türkiye\'de en uzun gündüz süresi hangi ilimizde yaşanır?', 'Sinop', 'Hatay', 'İzmir', 'Hakkari', 'Ankara', 'A', '21 Haziran\'da kuzeye gidildikçe gündüz süresi uzar; Türkiye\'nin en kuzey noktası Sinop\'tur.');
    addQ(2, 8, 1, '21 Aralık tarihinde Türkiye\'de en uzun gündüz süresi ve en kısa gece hangi ilimizde görülür?', 'Hatay', 'Sinop', 'Edirne', 'Kars', 'Trabzon', 'A', '21 Aralık\'ta güneye gidildikçe gündüz uzar; Türkiye\'nin en güney ili Hatay\'dır.');
    addQ(2, 8, 1, 'Türkiye\'de tüm yıl boyunca ulusal saat olarak hangi meridyenin yerel saati (+3. saat dilimi) kullanılmaktadır?', '45° Doğu Meridyeni (Iğdır)', '30° Doğu (İzmit)', '33° Doğu (Ankara)', '26° Doğu (Çanakkale)', '36° Doğu (Sivas)', 'A', 'Türkiye 2016 yılından itibaren sürekli yaz saati uygulamasıyla 45° Doğu Iğdır saatini kullanır.');
    addQ(2, 8, 1, 'Türkiye\'nin dört mevsimi belirgin olarak yaşaması doğrudan aşağıdakilerden hangisinin sonucudur?', 'Orta Kuşak\'ta (Ilıman Kuşak) yer almasının', 'Üç tarafının denizlerle çevrili olmasının', 'Yükseltisinin fazla olmasının', 'Asya ile Avrupa arasında köprü olmasının', 'Jeopolitik konumunun', 'A', 'Dört mevsimin belirgin yaşanması matematik konumun (orta kuşakta olmanın) sonucudur.');
    addQ(2, 8, 1, 'Aynı anda bir bölgede kar yağarken diğer bölgede denize girilebilmesi neyin sonucudur?', 'Kısa mesafelerde yer şekilleri ve yükseltinin değişmesinin (Özel konum)', 'Matematik konumun', 'Boylam derecelerinin', 'Dünyanın eksen eğikliğinin', 'Güneş ışınlarının geliş açısının', 'A', 'Aynı anda farklı mevsim özelliklerinin yaşanması özel konum (yükselti, engebe, denizellik) ile açıklanır.');
    addQ(2, 8, 1, 'Gece ve gündüz sürelerinin tüm dünyada eşit olduğu ekinoks tarihleri hangileridir?', '21 Mart ve 23 Eylül', '21 Haziran ve 21 Aralık', '1 Ocak ve 1 Temmuz', '23 Nisan ve 29 Ekim', '15 Şubat ve 15 Ağustos', 'A', '21 Mart ve 23 Eylül ekinokslarında Güneş ışınları Ekvator\'a dik düşer, gece ve gündüz 12 saat eşittir.');

    // Level 2: Orta Düzey
    addQ(2, 8, 2, 'Aşağıdaki illerden hangisinde yerel saat ile ulusal saat arasındaki zaman farkı en azdır?', 'Iğdır', 'İzmir', 'Edirne', 'Çanakkale', 'Muğla', 'A', 'Ulusal saat 45° Doğu Iğdır\'a göre ayarlı olduğu için Iğdır ve çevresinde fark neredeyse sıfırdır.');
    addQ(2, 8, 2, 'Türkiye\'de gölge boyunun hiçbir zaman sıfır olmamasının temel sebebi nedir?', 'Dönencelerin dışında (Kuzeyinde) yer alması', 'Orta kuşakta bulunması', 'Yükseltisinin fazla olması', 'Dağların doğu-batı uzanması', 'Saat dilimi', 'A', 'Güneş ışınları dönenceler dışına hiçbir zaman 90° dik açıyla düşmez, bu nedenle gölge sıfır olmaz.');
    addQ(2, 8, 2, 'Türkiye\'de gölge yönünün öğle vaktinde daima kuzeyi göstermesinin nedeni nedir?', 'Yengeç Dönencesi\'nin kuzeyinde yer alması', 'Ekvator\'da bulunması', 'Başlangıç meridyeninin doğusunda olması', 'Yer şekillerinin engebeli olması', 'Rüzgarların yönü', 'A', 'Güneş daima güneyden vurduğu için öğle vakti cisimlerin gölgesi daima kuzeye düşer.');
    addQ(2, 8, 2, 'İki meridyen arasındaki 4 dakikalık zaman farkı dünyanın neresinde olursa olsun değişmezken, ardışık iki meridyen arasındaki kuş uçuşu mesafenin Ekvatordan Kutuplara daralmasının sebebi nedir?', 'Meridyenlerin kutuplarda birleşmesi', 'Dünyanın dönüş hızı', 'Yörüngenin elips olması', 'Eksen eğikliği', 'Yerçekimi', 'A', 'Dünyanın küresel şekli nedeniyle meridyenler kutuplara doğru birbirine yaklaşır.');
    addQ(2, 8, 2, 'Aşağıdakilerden hangisi Türkiye\'nin özel (göreceli) konumunun bir sonucudur?', 'Bor madeni rezervinde dünyada birinci olması', 'Güneş ışınlarının hiçbir zaman dik gelmemesi', 'Güneye bakan yamaçların daha sıcak olması', 'Kuzeyden esen rüzgarların sıcaklığı düşürmesi', '2. ve 3. saat dilimlerinde yer alması', 'A', 'Maden çeşitliliği, yer altı zenginlikleri, yükselti ve boğazlar özel konumun sonucudur.');
    addQ(2, 8, 2, 'Çanakkale ve İstanbul Boğazlarına sahip olmak Türkiye\'ye özellikle hangi alanda küresel bir üstünlük sağlar?', 'Jeopolitik ve jeostratejik ticaret kontrolü', 'İklim çeşitliliği', 'Matematik konum netliği', 'Karasallık', 'Güneşlenme süresi', 'A', 'Karadeniz\'e kıyısı olan ülkelerin açık denizlere tek çıkış kapısı Türk Boğazlarıdır.');
    addQ(2, 8, 2, 'Türkiye ile Yunanistan arasındaki doğal sınırı oluşturan nehir hangisidir?', 'Meriç Nehri', 'Tunca Nehri', 'Arda Nehri', 'Asi Nehri', 'Fırat Nehri', 'A', 'Meriç Nehri Türkiye-Yunanistan sınırının büyük kısmını çizer.');
    addQ(2, 8, 2, 'Türkiye\'nin en uzun kara sınırı hangi ülke iledir ve en kısa kara sınırı hangi ülke iledir?', 'En uzun Suriye - En kısa Nahçıvan (Azerbaycan)', 'En uzun İran - En kısa Gürcistan', 'En uzun Irak - En kısa Ermenistan', 'En uzun Bulgaristan - En kısa Suriye', 'En uzun Yunanistan - En kısa Nahçıvan', 'A', 'Suriye sınırımız yaklaşık 911 km ile en uzun, Nahçıvan sınırımız ise yaklaşık 18 km ile en kısadır.');
    addQ(2, 8, 2, 'Türkiye\'de doğuya doğru gidildikçe sıcaklıkların azalmasının, tarım ürünlerinin daha geç olgunlaşmasının ve karın yerde kalma süresinin uzamasının temel nedeni nedir?', 'Ortalama yükseltinin artması', 'Enlem farkı', 'Boylam farkı', 'Rüzgar yönü', 'Toprak türü', 'A', 'Batıdan doğuya doğru ortalama yükselti arttığı için sıcaklıklar düşer.');
    addQ(2, 8, 2, 'Aşağıdaki şehir çiftlerinden hangisinde Güneş aynı anda doğar ve aynı anda batar?', 'Aynı meridyen üzerinde yer alan ve ekinoks (21 Mart-23 Eylül) tarihindeki iki şehir', 'Aynı paralel üzerindeki şehirler', 'Doğu-Batı yönlü şehirler', 'Deniz kıyısındaki şehirler', 'Başkent ve liman kentleri', 'A', 'Aynı boylam üzerinde sadece ekinoks günlerinde güneş aynı anda doğar ve aynı anda batar.');

    // Level 3: Zor & Detay
    addQ(2, 8, 3, 'Türkiye üzerinden geçen uluslararası enerji boru hatlarından Bakü-Tiflis-Ceyhan (BTC) ve TANAP hangi stratejik kaynağın taşınmasını sağlar?', 'Hazar petrolleri ve Azerbaycan doğalgazı', 'Kömür', 'Elektrik', 'Uranyum', 'İçme suyu', 'A', 'BTC petrol, TANAP ise Şahdeniz doğalgazını Türkiye üzerinden Avrupa\'ya taşır.');
    addQ(2, 8, 3, 'Güneş ışınlarının tutulma oranının Türkiye\'de güneyden kuzeye doğru artmasının temel nedeni nedir?', 'Güneş ışınlarının atmosferde kat ettiği yolun uzaması (Açının küçülmesi)', 'Yükseltinin azalması', 'Nemliliğin artması', 'Orman varlığı', 'Bulutluluk oranı', 'A', 'Kuzeye gidildikçe açı küçülür, ışınlar atmosferde daha uzun yol alır ve enerji kaybı (tutulma) artar.');
    addQ(2, 8, 3, '21 Mart ekinoksunda 36° Kuzey paralelindeki Hatay\'a Güneş ışınları öğle vakti kaç derecelik açıyla gelir?', '54°', '90°', '36°', '48°', '60°', 'A', 'Ekinoksta Ekvatora 90° ile gelir. Geliş açısı = 90° - Enlem. 90° - 36° = 54° dir.');
    addQ(2, 8, 3, 'Türkiye\'de dağların genel olarak doğu-batı doğrultulu uzanması aşağıdakilerden hangisi üzerinde etkili OLMAMIŞTIR?', 'Maden çeşitliliğinin dağılışında', 'Karadeniz ve Akdeniz\'de kıyı ile iç kesimler arasında ulaşımın zor olmasında', 'Ege\'de denizel havanın iç kesimlere sokulabilmesinde', 'Kuzey ve güney kıyılarımızda boyuna kıyı tipinin görülmesinde', 'Akarsuların genelde doğu-batı yönlü akmasında', 'A', 'Madenlerin dağılışı jeolojik yapıyla ilgilidir, dağların uzanışıyla doğrudan ilgisi yoktur.');
    addQ(2, 8, 3, 'Türkiye\'de buzul aşındırma ve biriktirme şekillerinin (sirk gölleri, morenler) sadece yüksek dağ zirvelerinde görülmesi neyle açıklanır?', 'Matematik konumu gereği orta kuşakta yer alması ve yükseltinin fazla olması', 'Denizlerle çevrili olması', 'Karasallık', 'Bitki örtüsü', 'Toprak türü', 'A', 'Kutup kuşağında olmadığı için buzullar deniz seviyesine inemez, sadece 2000-2500m üzerindeki dağlarda görülür.');
    addQ(2, 8, 3, 'Türkiye\'nin sınır kapılarından Kapıkule hangi ülkeyle, Sarp hangi ülkeyle ve Habur hangi ülkeyle demiryolu veya karayolu bağlantısı sağlar?', 'Kapıkule-Bulgaristan, Sarp-Gürcistan, Habur-Irak', 'Kapıkule-Yunanistan, Sarp-Ermenistan', 'Kapıkule-İran, Sarp-Rusya', 'Sarp-İran, Habur-Suriye', 'Kapıkule-Romanya, Habur-İran', 'A', 'Kapıkule en işlek sınır kapımız olup Bulgaristan\'a, Sarp Gürcistan\'a, Habur ise Irak\'a açılır.');
    addQ(2, 8, 3, 'Aşağıdaki geçitlerden hangisi Akdeniz\'i İç Anadolu\'ya bağlayan tarihi ve stratejik geçitlerden biridir?', 'Gülek Boğazı', 'Zigana Geçidi', 'Kop Geçidi', 'Ilgaz Geçidi', 'Ovit Tüneli', 'A', 'Gülek Geçidi Çukurova\'yı İç Anadolu\'ya bağlayan en önemli doğal boğazdır. Zigana ve Kop Karadeniz\'dedir.');
    addQ(2, 8, 3, 'Doğu Karadeniz Dağları\'nı aşarak Trabzon Limanı\'nı İran transit ticaret yoluna bağlayan geçit hangisidir?', 'Zigana (Kalkanlı) Geçidi', 'Gülek Geçidi', 'Belen Geçidi', 'Sertavul Geçidi', 'Çubuk Geçidi', 'A', 'Tarihi İpek Yolu güzergahında yer alan Zigana Geçidi Trabzon-Gümüşhane arasındadır.');
    addQ(2, 8, 3, 'Türkiye\'nin jeolojik olarak "genç oluşumlu" bir ülke olduğunu kanıtlayan en temel göstergeler hangileridir?', 'Fay hatlarının, depremlerin, jeotermal kaynakların yaygın ve ortalama yükseltinin fazla olması', 'Kömür yataklarının olmaması', 'Düzlüklerin çok olması', 'Göl sayısının az olması', 'İklimin ılıman olması', 'A', 'III. ve IV. jeolojik zamanda (Alp-Himalaya orojenezi) toptan yükseldiği için aktif kırıklar ve depremler fazladır.');
    addQ(2, 8, 3, 'Türkiye\'de gerçek alan ile izdüşüm alan arasındaki farkın en fazla olduğu bölge ve en az olduğu bölge sırasıyla hangileridir?', 'En fazla Doğu Karadeniz / Doğu Anadolu - En az Marmara / Güneydoğu Anadolu', 'En fazla Marmara - En az Ege', 'En fazla İç Anadolu - En az Karadeniz', 'En fazla Akdeniz - En az Doğu Anadolu', 'Fark her yerde aynıdır', 'A', 'Engebe ve eğim arttıkça gerçek alan ile izdüşüm alan arasındaki fark artar. Marmara düz olduğu için fark azdır.');

    // -------------------------------------------------------------------------
    // Subcat 9: Türkiye Yer Şekilleri, Dağlar ve Platolar
    // -------------------------------------------------------------------------
    // Level 1: Temel Şekiller
    addQ(2, 9, 1, 'Türkiye\'nin en yüksek dağı aşağıdakilerden hangisidir?', 'Ağrı Dağı (5137 m)', 'Cilo Dağı', 'Erciyes Dağı', 'Kaçkar Dağı', 'Süphan Dağı', 'A', 'Ağrı Dağı 5.137 metre zirvesiyle Türkiye\'nin en yüksek volkanik dağıdır.');
    addQ(2, 9, 1, 'Ege Bölgesi\'nde kırılma (faylanma) sonucu oluşan çöküntü ovalarına (graben) aşağıdakilerden hangisi örnek verilemez?', 'Çukurova', 'Gediz Ovası', 'Büyük Menderes Ovası', 'Küçük Menderes Ovası', 'Bakırçay Ovası', 'A', 'Çukurova Seyhan ve Ceyhan nehirlerinin oluşturduğu bir delta ovasıdır; graben değildir.');
    addQ(2, 9, 1, 'Akarsuların taşıdığı alüvyonları denize döküldükleri yerde biriktirmesiyle oluşan Türkiye\'nin en büyük delta ovası hangisidir?', 'Çukurova', 'Bafra Ovası', 'Çarşamba Ovası', 'Silifke Ovası', 'Menemen Ovası', 'A', 'Çukurova Akdeniz kıyısında Seyhan ve Ceyhan nehirlerinin oluşturduğu devasa deltadır.');
    addQ(2, 9, 1, 'Kızılırmak Nehri\'nin Karadeniz\'e döküldüğü yerde oluşturduğu delta ovası hangisidir?', 'Bafra Ovası', 'Çarşamba Ovası', 'Sakarya Ovası', 'Balat Ovası', 'Dikili Ovası', 'A', 'Kızılırmak Bafra\'yı, Yeşilırmak ise Çarşamba deltasını oluşturur.');
    addQ(2, 9, 1, 'Kalker (kireçtaşı), jips ve kayatuzu gibi suda kolay çözünebilen kayaçların oluşturduğu yer şekillerine ne denir?', 'Karstik şekiller', 'Volkanik şekiller', 'Buzul şekilleri', 'Rüzgar şekilleri', 'Fluvial şekiller', 'A', 'Karstik şekiller özellikle Akdeniz ve Göller Yöresi\'nde çok yaygındır.');
    addQ(2, 9, 1, 'Yaz yağmurlarıyla yeşeren çayırların altında oluşan ve verimli büyükbaş hayvancılık yapılan Erzurum-Kars platosundaki toprak türü nedir?', 'Çernezyom (Kara Toprak)', 'Terra Rossa', 'Laterit', 'Podzol', 'Alüvyal', 'A', 'Çernezyom dünyanın en verimli yerli (zonal) toprağıdır.');
    addQ(2, 9, 1, 'Türkiye\'nin en büyük gölü hangisidir ve suları sodalıdır?', 'Van Gölü', 'Tuz Gölü', 'Beyşehir Gölü', 'İznik Gölü', 'Eğirdir Gölü', 'A', 'Van Gölü nemrut volkanizması sonucu oluşan volkanik set gölü olup sodalıdır.');
    addQ(2, 9, 1, 'İç Anadolu Bölgesi\'nde rüzgar aşındırma ve biriktirme şekillerinin (kumullar, mantarkaya) yaygın olmasının temel nedeni nedir?', 'Bitki örtüsünün cılız olması ve kuraklık', 'Yükseltinin çok fazla olması', 'Akarsu debilerinin yüksek olması', 'Deprem bölgesi olması', 'Orman yangınları', 'A', 'Rüzgar kurak ve bitki örtüsünden yoksun gevşek topraklı arazilerde en etkili dış kuvvettir.');
    addQ(2, 9, 1, 'Bir ada ile karanın kıyı oku veya kordonuyla birleşmesi sonucu oluşan yarımadalara (tombolo) Türkiye\'deki en belirgin örnek hangisidir?', 'Kapıdağ Yarımadası ve Sinop İnceburun', 'Gelibolu Yarımadası', 'Datça Yarımadası', 'Bodrum Yarımadası', 'Çeşme Yarımadası', 'A', 'Balıkesir Kapıdağ Yarımadası dalga biriktirmesiyle oluşan tipik bir tombolodur.');
    addQ(2, 9, 1, 'Türkiye\'nin tatlı su gölleri arasında en geniş alana sahip olan gölümüz hangisidir?', 'Beyşehir Gölü', 'Tuz Gölü', 'Van Gölü', 'Burdur Gölü', 'Acıgöl', 'A', 'Gideğeni (ayağı) olduğu için suları tatlı olan en büyük gölümüz Beyşehir Gölü\'dür.');

    // Level 2: Orta Düzey
    addQ(2, 9, 2, 'Kırılma ile oluşan dağlık kütlelere "horst", aradaki çöküntülere "graben" denir. Aşağıdaki dağlardan hangisi horst özelliği taşır?', 'Kaz Dağı, Madra Dağı, Yunt Dağı, Bozdağlar, Aydın Dağları', 'Ağrı Dağı', 'Erciyes Dağı', 'Toros Dağları', 'Kaçkar Dağları', 'A', 'Ege\'deki kırıklı dağlar (Kaz, Madra, Yunt, Boz, Aydın, Menteşe) horsttur.');
    addQ(2, 9, 2, 'İç püskürük bir kütle (Batolit) olan ve Marmara Bölgesi\'nin en yüksek noktasını oluşturan dağ hangisidir?', 'Uludağ', 'Yıldız Dağları', 'Samanlı Dağları', 'Koru Dağları', 'Biga Dağları', 'A', 'Bursa Uludağ derinlik volkanizması (batolit kütlesi) sonucu oluşmuş bir dağdır.');
    addQ(2, 9, 2, 'Türkiye\'de karstik platolar (kalker yapılı) denilince ilk akla gelen Akdeniz platoları hangileridir?', 'Teke ve Taşeli Platoları', 'Haymana ve Cihanbeyli', 'Bozok ve Obruk', 'Yazılıkaya ve Ardahan', 'Şanlıurfa ve Gaziantep', 'A', 'Teke ve Taşeli platoları karstik ve engebeli olduğu için nüfus yoğunluğu çok düşüktür.');
    addQ(2, 9, 2, 'Lav örtüsü platosu olan ve bazaltik yapısıyla volkanizmanın eseri olan platolarımız hangileridir?', 'Erzurum-Kars ve Ardahan Platoları', 'Çatalca-Kocaeli', 'Bozok Platosu', 'Taşeli Platosu', 'Obruk Platosu', 'A', 'Doğu Anadolu\'daki Erzurum-Kars platoları lav akıntılarının birikmesiyle oluşmuştur.');
    addQ(2, 9, 2, 'Türkiye\'nin tek aşınım (peneplen) platosu kabul edilen, sanayi ve nüfusun en yoğun olduğu platosu hangisidir?', 'Çatalca-Kocaeli Platosu', 'Haymana Platosu', 'Cihanbeyli Platosu', 'Bozok Platosu', 'Taşeli Platosu', 'A', 'Çatalca-Kocaeli peneplenleşmiş alçak aşınım platosu olup Türkiye\'nin en kalabalık yeridir.');
    addQ(2, 9, 2, 'Nemrut Dağı krater gölü, Meke Tuzlası maarı ve Gölcük maar gölü hangi göl oluşum türüne girer?', 'Volkanik Göller', 'Tektonik Göller', 'Karstik Göller', 'Heyelan Set Gölleri', 'Kıyı Set Gölleri', 'A', 'Volkanizma patlamaları sonucu oluşan krater, kaldera ve maar çukurlarına suların dolmasıyla oluşur.');
    addQ(2, 9, 2, 'Doğu Karadeniz\'de dağ yamaçlarından kopan kütlelerin vadi önünü tıkamasıyla oluşan heyelan set göllerine hangisi örnek gösterilemez?', 'Uzungöl', 'Tortum Gölü', 'Abant Gölü', 'Yedigöller', 'Beyşehir Gölü', 'E', 'Beyşehir tektonik-karstik bir göldür; heyelan set gölü değildir.');
    addQ(2, 9, 2, 'Türkiye\'de peri bacalarının (Kapadokya) oluşumunda iç kuvvet olarak volkanizma, dış kuvvet olarak hangisi etkilidir?', 'Akarsu ve sel suları aşındırması', 'Buzullar', 'Rüzgar biriktirmesi', 'Dalgalar', 'Heyelan', 'A', 'Volkanik tüf ve bazaltları akarsu ve sel suları aşındırır, rüzgar ise ikincil etkiye sahiptir.');
    addQ(2, 9, 2, 'Kuzey Anadolu Fay Hattı (KAF) nereden başlar ve nerede son bulur?', 'Saros Körfezi\'nden başlar - Van Gölü kuzeyi ve Aras Vadisi\'ne kadar uzanır', 'İskenderun\'dan başlar - Sinop\'a uzanır', 'İzmir\'den başlar - Hakkari\'ye uzanır', 'Antalya\'dan - Trabzon\'a', 'Mersin\'den - Artvin\'e', 'A', 'KAF Saros Körfezi, Marmara Denizi, Bolu, Tokat, Erzincan üzerinden Doğu Anadolu\'ya uzanan doğrultu atımlı tehlikeli bir faydır.');
    addQ(2, 9, 2, 'Türkiye\'de dağların kıyıya paralel uzandığı Karadeniz ve Akdeniz\'de görülen kıyı tipi hangisidir?', 'Boyuna Kıyı Tipi', 'Enine Kıyı Tipi', 'Ria Kıyı Tipi', 'Dalmaçya Kıyı Tipi', 'Kalanklı Kıyı Tipi', 'A', 'Dağların kıyıya paralel uzandığı yerlerde boyuna kıyı tipi görülür, falezler (yalıyar) çoktur.');

    // Level 3: Zor & Detay
    addQ(2, 9, 3, 'İstanbul Boğazı, Çanakkale Boğazı ve Haliç hangi kıyı tipine en güzel örnektir?', 'Ria Kıyı Tipi', 'Dalmaçya Kıyı Tipi', 'Fiyort Kıyı Tipi', 'Haff Kıyı Tipi', 'Limanlı Kıyı Tipi', 'A', 'Eski akarsu vadilerinin deniz suları altında kalmasıyla oluşan boğulmuş vadilere Ria tipi kıyı denir.');
    addQ(2, 9, 3, 'Antalya Kaş kıyılarında denize paralel uzanan adacıkların oluşturduğu kıyı tipi hangisidir?', 'Dalmaçya Kıyı Tipi', 'Boyuna', 'Enine', 'Ria', 'Watt', 'A', 'Adriyatik Denizi\'ndeki gibi kıyıya paralel dağların sular altında kalması Dalmaçya kıyı tipidir.');
    addQ(2, 9, 3, 'Türkiye kıyılarında Fiyort ve Skyer tipi kıyıların görülmemesinin temel sebebi nedir?', 'Matematik konum (Kutup kuşağında olmamamız, buzulların deniz seviyesine inmemesi)', 'Özel konum', 'Gelgit genliğinin az olması', 'Dağların uzanışı', 'Akarsuların rejimleri', 'A', 'Fiyort ve Skyer buzulların deniz seviyesine indiği yüksek enlemlerde (Norveç, Kanada) görülür.');
    addQ(2, 9, 3, 'Türkiye\'de gelgit genliğinin az olması nedeniyle okyanus kıyılarında görülen Haliç ve Watt tipi kıyılar neden görülmez?', 'İç deniz ülkesi olması ve okyanusa doğrudan kıyısı bulunmaması', 'Yükseltinin fazla olması', 'Sıcak su akıntıları', 'Tuzluluk oranı', 'Boğazların varlığı', 'A', 'İç denizlerde gelgit genliği birkaç santimetredir; okyanuslardaki gibi devasa gelgit deltaları yıkıp haliç oluşturamaz.');
    addQ(2, 9, 3, 'Yeraltı suyunun kalker tabakasını eritmesiyle oluşan mağara tavanlarının çökmesi sonucu oluşan derin doğal kuyulara ne denir?', 'Obruk', 'Dolin', 'Uvala', 'Polye', 'Lapya', 'A', 'Konya Ovası ve Cennet-Cehennem çökükleri tipik obruk oluşumlarıdır.');
    addQ(2, 9, 3, 'Karstik aşınım şekillerinin en büyüğü olan ve içinde yerleşim kurulan karstik ovalara (Tefenni, Acıpayam, Korkuteli, Muğla, Elmalı - TAKKE) ne ad verilir?', 'Polye', 'Uvala', 'Dolin', 'Lapya', 'Kör Vadi', 'A', 'Polyeler karstik çöküntü alanları olup verimli karstik ovaları oluştururlar.');
    addQ(2, 9, 3, 'Türkiye\'de rüzgar erozyonunun en şiddetli olduğu yerleşim yerlerinden biri olan ve rüzgar erozyonunu önleme sahası bulunan ilçe hangisidir?', 'Konya - Karapınar', 'Şanlıurfa - Siverek', 'Iğdır - Aralık', 'Ankara - Polatlı', 'Nevşehir - Ürgüp', 'A', 'Karapınar Türkiye\'de rüzgar kumullarının ve çölleşme tehlikesinin en belirgin olduğu yerdir.');
    addQ(2, 9, 3, 'Büyük Menderes ve Gediz nehirlerinin yatak eğiminin azalması sonucu oluşturduğu kıvrımlı akarsu şekillerine ne ad verilir?', 'Menderes', 'Kanyon Vadi', 'Çentik Vadi', 'Dev Kazanı', 'Taraça', 'A', 'Menderes hem aşındırma hem biriktirme şeklidir, akarsuyun boyu uzar ve akış hızı azalır.');
    addQ(2, 9, 3, 'Manavgat, Düden ve Kurşunlu şelalelerinin döküldükleri yerde oluşturdukları derin çukurlara ne denir?', 'Dev Kazanı', 'Kanyon', 'Menderes', 'Sirk', 'Traverten', 'A', 'Çağlayanların tabanında suyun çarparak oyduğu çukurluklara dev kazanı denir.');
    addQ(2, 9, 3, 'Denizli Pamukkale\'de kalsiyum bikarbonatlı termal suların yüzeye çıkıp karbondioksitin uçmasıyla çökelen basamaklı beyaz kalker yapılarına ne denir?', 'Traverten', 'Sarkıt', 'Dikit', 'Sütun', 'Lapya', 'A', 'Pamukkale travertenleri kimyasal tortul / karstik biriktirme şeklidir.');

// KPSS Coğrafya Part 2 (Subcategories 10, 11, 12 - 90 Questions)
// Category: 2 (Coğrafya)


    // -------------------------------------------------------------------------
    // Subcat 10: Türkiye İklimi ve Bitki Örtüsü
    // -------------------------------------------------------------------------
    // Level 1: Temel İklim
    addQ(2, 10, 1, 'Türkiye\'de yıllık yağış miktarının en fazla olduğu ilimiz aşağıdakilerden hangisidir?', 'Rize', 'Trabzon', 'Antalya', 'Muğla', 'Zonguldak', 'A', 'Rize yıllık 2400 mm\'yi aşan yağışıyla Türkiye\'nin en çok yağış alan ilidir.');
    addQ(2, 10, 1, 'Türkiye\'de yıllık yağış miktarının en az olduğu bölgemiz ve çevresi neresidir?', 'İç Anadolu (Tuz Gölü çevresi ve Konya Kapalı Havzası)', 'Güneydoğu Anadolu', 'Doğu Anadolu', 'Marmara', 'Ege', 'A', 'Etrafı dağlarla çevrili olduğu için nemli hava kütlelerinin giremediği Tuz Gölü çevresi en az yağış alan yerdir.');
    addQ(2, 10, 1, 'Akdeniz ikliminin tipik doğal bitki örtüsü aşağıdakilerden hangisidir?', 'Maki', 'Bozkır (Step)', 'Geniş yapraklı orman', 'Çayır', 'Tundra', 'A', 'Akdeniz ikliminde yaz kuraklığına dayanıklı bodur ağaççıklardan oluşan makiler hakimdir.');
    addQ(2, 10, 1, 'İç Anadolu ve Güneydoğu Anadolu\'da ilkbahar yağışlarıyla yeşeren, yazın kuruyan otsu bitkilerden oluşan bitki örtüsü nedir?', 'Bozkır (Step)', 'Maki', 'Savan', 'Tayga', 'Çayır', 'A', 'Karasal iklimin doğal bitki örtüsü bozkırdır (yavşan otu, geven, gelincik).');
    addQ(2, 10, 1, 'Türkiye\'yi kuzeybatıdan etkileyen, kışın soğuk ve kar yağışı getiren rüzgar hangisidir?', 'Karayel', 'Yıldız', 'Poyraz', 'Lodos', 'Samyeli', 'A', 'Kayıp Sakal şifresiyle: Karayel (KB), Yıldız (K), Poyraz (KD), Samyeli (GD), Kıble (G), Lodos (GB).');
    addQ(2, 10, 1, 'Güneybatıdan esen, ılık ve nemli hava getiren, kışın soba zehirlenmelerine yol açabilen rüzgar hangisidir?', 'Lodos', 'Poyraz', 'Karayel', 'Yıldız', 'Günbatısı', 'A', 'Lodos sıcak ve nemlidir, kışın karları hızla eritip su baskınlarına ve baca gazı zehirlenmelerine neden olabilir.');
    addQ(2, 10, 1, 'Doğu Karadeniz\'de dağları aşıp Rize ve Çoruh vadisine inen havanın sürtünmeyle ısınıp kurutucu etki yapması olayına ne denir?', 'Föhn rüzgarı', 'Etezien', 'Meltem', 'Bora', 'Mistral', 'A', 'Föhn rüzgarı dağdan aşağı inerken her 100 metrede 1°C ısınır; Rize\'de turunçgil yetişmesini sağlar.');
    addQ(2, 10, 1, 'Ilıman karasal iklimde ilkbaharda ısınan havanın yükselerek soğumasıyla oluşan "kırkikindi" yağışlarının türü nedir?', 'Konveksiyonel (Yükselim) Yağışları', 'Orografik (Yamaç) Yağışları', 'Cephe (Frontal) Yağışları', 'Siklonik Yağışlar', 'Muson Yağışları', 'A', 'İç Anadolu\'da ilkbahar aylarında öğleden sonra görülen yağışlar konveksiyoneldir.');
    addQ(2, 10, 1, 'Karadeniz dağlarının denize bakan yamaçlarında nemli hava kütlesinin dağ boyunca yükselip soğumasıyla oluşan yağış türü nedir?', 'Orografik (Yamaç) Yağışları', 'Konveksiyonel Yağışlar', 'Cephe Yağışları', 'Dinamik Yağışlar', 'Suni Yağışlar', 'A', 'Dağların kıyıya paralel uzandığı Doğu ve Batı Karadeniz ile Toroslar\'da orografik yağışlar yaygındır.');
    addQ(2, 10, 1, 'Türkiye\'de kış mevsiminde görülen yağışların büyük bir kısmını oluşturan, sıcak ve soğuk hava kütlelerinin karşılaşma alanlarında oluşan yağış hangisidir?', 'Cephe (Frontal) Yağışları', 'Yükselim Yağışları', 'Yamaç Yağışları', 'Tropikal Yağışlar', 'Konveksiyonel', 'A', 'Türkiye orta kuşakta yer aldığı için kutup havası ile tropikal havanın çarpışmasıyla cephe yağışları oluşur.');

    // Level 2: Orta Düzey
    addQ(2, 10, 2, 'Rize ve çevresinde turunçgil, Artvin Çoruh vadisinde zeytin, Alanya-Gazipaşa kıyılarında muz yetişmesi neyin göstergesidir?', 'Mikroklima (Dar alanlı özel iklim) alanı olmalarının', 'Geniş Akdeniz iklim bölgesinde olmalarının', 'Topraklarının aynı olmasının', 'Ekvatoral iklim yaşandığının', 'Tarımsal sulamanın', 'A', 'Çevrelerinden farklı özel iklim şartları gösteren dar alanlara mikroklima denir.');
    addQ(2, 10, 2, 'Kışın Sibirya Termik Yüksek Basıncı Türkiye\'yi etkisi altına aldığında ülkemizde hava nasıl olur?', 'Aşırı soğuk, ayaz, kar yağışlı ve durgun', 'Ilık ve yağmurlu', 'Sıcak ve kurak', 'Fırtınalı ve sisli', 'Sürekli sağanak yağışlı', 'A', 'Sibirya yüksek basıncı özellikle Doğu Anadolu ve İç Anadolu\'da kışın şiddetli ayaz ve dondurucu soğuk yapar.');
    addQ(2, 10, 2, 'Yazın Güneydoğu Anadolu Bölgesi\'nde sıcaklıkların ve buharlaşmanın aşırı yüksek olmasında etkili olan dinamik basınç merkezi hangisidir?', 'Basra Termik Alçak Basıncı', 'Asor Yüksek Basıncı', 'İzlanda Alçak Basıncı', 'Sibirya Yüksek Basıncı', 'Muson Alçak Basıncı', 'A', 'Basra Basıncı güneyden sıcak çöl havasını ülkemize taşıyarak Güneydoğu\'da kavurucu sıcaklık yapar.');
    addQ(2, 10, 2, 'Aşağıdaki bitki türlerinden hangisi "endemik" (dünyada yalnızca belirli bir yöreye özgü) bitkilerimize örnektir?', 'Köyceğiz Sığla (Günlük) Ağacı, Datça Hurması, Kazdağı Göknarı', 'Kızılçam', 'Meşe', 'Kavak', 'Söğüt', 'A', 'Muğla Köyceğiz\'deki Sığla ağacı relikt ve endemik bir türdür, eczacılıkta kullanılır.');
    addQ(2, 10, 2, 'Karadeniz ormanlarının tahrip edilmesiyle oluşan yalancı maki topluluklarına ne ad verilir?', 'Psödomaki', 'Garig', 'Antropojen Bozkır', 'Çayır', 'Maki', 'A', 'Karadeniz\'de ormanların yok edilmesiyle oluşan fındık, şimşir, böğürtlen gibi çalılara psödomaki denir.');
    addQ(2, 10, 2, 'İç Anadolu\'da insanların meşe ormanlarını tahrip etmesi sonucu ortaya çıkan bozkırlara ne denir?', 'Antropojen Bozkır', 'Doğal Bozkır', 'Maki', 'Garig', 'Tundra', 'A', 'İnsan müdahalesiyle açılan bozkırlara antropojen bozkır denir.');
    addQ(2, 10, 2, 'Marmara Bölgesi\'nde Karadeniz, Akdeniz ve Karasal iklimlerin bir arada görülmesi bölgeye hangi avantajı sağlamıştır?', 'Bitki örtüsü ve tarım ürünü çeşitliliğinin en fazla olduğu bölge olmasını', 'Yıllık yağışın en çok olduğu bölge olmasını', 'Yükseltinin en fazla olmasını', 'Buzul şekillerinin çok olmasını', 'Sıcak su kaynaklarının olmamasını', 'A', 'Marmara bir geçiş bölgesidir ve iklim çeşitliliği sayesinde çok farklı tarım ürünleri bir arada yetiştirilebilir.');
    addQ(2, 10, 2, 'Türkiye\'de bağıl nemin (nem oranının) yıl boyunca en yüksek olduğu bölge hangisidir?', 'Karadeniz Bölgesi (Özellikle Doğu Karadeniz)', 'Güneydoğu Anadolu', 'İç Anadolu', 'Doğu Anadolu', 'Ege', 'A', 'Yağış ve bulutluluğun en fazla olduğu Karadeniz\'de bağıl nem daima yüksektir, sıcaklık farkları azdır.');
    addQ(2, 10, 2, 'Türkiye\'de günlük ve yıllık sıcaklık farklarının en fazla olduğu bölge hangisidir?', 'Doğu Anadolu Bölgesi', 'Akdeniz Bölgesi', 'Karadeniz Bölgesi', 'Ege Bölgesi', 'Marmara Bölgesi', 'A', 'Nem azlığı (şiddetli karasallık) ve yüksek irtifa nedeniyle Doğu Anadolu\'da sıcaklık farkları çok büyüktür.');
    addQ(2, 10, 2, 'Ege kıyılarında yaz aylarında deniz ile kara arasındaki sıcaklık farkından doğan yerel rüzgara (deniz meltemi) halk arasında ne ad verilir?', 'İmbat', 'Lodos', 'Poyraz', 'Etezien', 'Keşişleme', 'A', 'İzmir ve Ege kıyılarında öğleden sonra denizden karaya esen serinletici melteme İmbat denir.');

    // Level 3: Zor & Detay
    addQ(2, 10, 3, 'Türkiye\'de orman yangını riskinin en yüksek olduğu bölgeler sırasıyla hangileridir?', 'Akdeniz ve Ege Bölgeleri', 'Karadeniz ve Marmara', 'İç Anadolu ve Doğu Anadolu', 'Güneydoğu Anadolu', 'Trakya', 'A', 'Yaz kuraklığının şiddetli olması, yüksek sıcaklık ve kızılçam varlığı nedeniyle Akdeniz ve Ege\'de yangın riski zirvededir.');
    addQ(2, 10, 3, 'Türkiye\'de ormanların deniz seviyesinden başlama sınırı (orman alt sınırı) en alçak olan bölge neresidir?', 'Karadeniz Bölgesi (0 metre)', 'Akdeniz Bölgesi', 'Ege Bölgesi', 'Marmara Bölgesi', 'İç Anadolu', 'A', 'Nem ve yağış yeterli olduğu için Karadeniz\'de ormanlar doğrudan deniz kıyısından (0 metreden) başlar.');
    addQ(2, 10, 3, 'Ormanların yetişebildiği en yüksek sınırı (orman üst sınırı) belirleyen temel faktör nedir?', 'Sıcaklık (ve yükselti)', 'Yağış miktarı', 'Toprak türü', 'Rüzgarlar', 'İnsan etkisi', 'A', 'Orman alt sınırını nem ve yağış belirlerken, orman üst sınırını sıcaklık yetersizliği belirler.');
    addQ(2, 10, 3, 'Akdeniz Bölgesi\'nde orman üst sınırının (yaklaşık 2000-2200 m) Karadeniz\'den (1800 m) daha yüksek olmasının nedeni nedir?', 'Akdeniz\'in ekvatora daha yakın ve daha sıcak olması (Enlem etkisi)', 'Yağışın daha çok olması', 'Nem oranının yüksekliği', 'Rüzgar yönü', 'Toprak yapısı', 'A', 'Enlem gereği Akdeniz daha sıcaktır, ağaçlar daha yüksek rakımlarda bile yaşayabilir.');
    addQ(2, 10, 3, 'Geçmiş jeolojik dönemlerdeki iklim koşullarından günümüze kadar varlığını koruyabilmiş kalıntı bitkilere ne ad verilir?', 'Relikt Bitki', 'Endemik Bitki', 'Maki', 'Bozkır', 'Halofit', 'A', 'Relikt bitkiler buzul çağlarından kalan ve sığınak alanlarda yaşamını sürdüren kalıntı türlerdir.');
    addQ(2, 10, 3, 'Türkiye\'de donlu gün sayısının en az olduğu kıyılarımız hangisidir?', 'Akdeniz kıyıları (0-1 gün)', 'Karadeniz kıyıları', 'Marmara kıyıları', 'Ege kıyıları', 'İç Anadolu', 'A', 'Akdeniz kıyılarında kışlar çok ılık geçtiği için don olayı neredeyse hiç görülmez, seracılık çok gelişmiştir.');
    addQ(2, 10, 3, 'Türkiye\'de güneş enerjisinden yararlanma potansiyelinin en yüksek olduğu bölge hangisidir?', 'Güneydoğu Anadolu ve Akdeniz', 'Karadeniz', 'Marmara', 'Doğu Anadolu', 'İç Anadolu', 'A', 'Güneydoğu ve Akdeniz\'de bulutluluk az, güneşlenme süresi yıllık 3000 saatin üzerindedir.');
    addQ(2, 10, 3, 'Aşağıdaki akarsularımızdan hangisi açık havza özelliğinde olup enerjisi en yüksek akarsularımızdandır ve hidroelektrik potansiyeli en fazladır?', 'Fırat ve Dicle Nehirleri', 'Tuz Gölü Havzası', 'Van Gölü Kapalı Havzası', 'Burdur Havzası', 'Akarçay', 'A', 'Fırat nehri üzerindeki Keban, Karakaya ve Atatürk Barajları Türkiye\'nin elektrik üretim omurgasıdır.');
    addQ(2, 10, 3, 'Türkiye sınırları dışından doğup Türkiye topraklarından denize dökülen nehirler hangileridir?', 'Meriç ve Asi Nehirleri', 'Fırat ve Dicle', 'Aras ve Kura', 'Kızılırmak ve Yeşilırmak', 'Seyhan ve Ceyhan', 'A', 'Meriç Bulgaristan\'dan, Asi ise Lübnan/Suriye\'den doğup ülkemizden denize dökülür.');
    addQ(2, 10, 3, 'Türkiye sınırları içinden doğup komşu ülkelerden Hazar Denizi\'ne dökülen kapalı havza nehirlerimiz hangileridir?', 'Aras ve Kura Nehirleri', 'Fırat ve Dicle', 'Çoruh', 'Asi', 'Meriç', 'A', 'Aras ve Kura Doğu Anadolu\'dan doğarak Azerbaycan üzerinden Hazar Kapalı Havzası\'na dökülür.');

    // -------------------------------------------------------------------------
    // Subcat 11: Türkiye Nüfus ve Yerleşme
    // -------------------------------------------------------------------------
    // Level 1: Temel Nüfus
    addQ(2, 11, 1, 'Cumhuriyet döneminde Türkiye\'de ilk genel nüfus sayımı hangi yılda yapılmıştır?', '1927', '1923', '1935', '1940', '1950', 'A', 'İlk nüfus sayımı 1927\'de yapılmış ve Türkiye nüfusu 13.6 milyon olarak tespit edilmiştir.');
    addQ(2, 11, 1, 'Türkiye\'de nüfus artış hızının tarihteki en düşük seviyeye gerilediği dönem hangi tarihi olayın yaşandığı yıllardır?', 'II. Dünya Savaşı yılları (1940-1945)', 'I. Dünya Savaşı', '1980 Askeri Darbesi', '1999 Depremi', '1974 Kıbrıs Barış Harekatı', 'A', 'Seferberlik ilanı ve erkeklerin silah altına alınması nedeniyle 1940-45 arası nüfus artış hızı binde 10.6\'ya inmiştir.');
    addQ(2, 11, 1, 'Türkiye\'de nüfusun ve sanayinin en yoğun olduğu coğrafi bölge hangisidir?', 'Marmara Bölgesi', 'Ege Bölgesi', 'İç Anadolu', 'Akdeniz', 'Karadeniz', 'A', 'İstanbul, Kocaeli, Bursa sanayi ve ticaret aksı nedeniyle Marmara nüfusun üçte birini barındırır.');
    addQ(2, 11, 1, 'Türkiye\'de aritmetik nüfus yoğunluğu en az olan ilimiz hangisidir?', 'Tunceli', 'Bayburt', 'Ardahan', 'Gümüşhane', 'Sinop', 'A', 'Yüzölçümüne düşen kişi sayısının en az olduğu il Tunceli\'dir.');
    addQ(2, 11, 1, 'Karadeniz Bölgesi\'nde arazinin aşırı dağınık ve engebeli, su kaynaklarının bol olması hangi kırsal yerleşme türünü doğurmuştur?', 'Dağınık Yerleşme', 'Toplu Yerleşme', 'Çizgisel Yerleşme', 'Dairesel Yerleşme', 'Kıyı Boyu Yerleşme', 'A', 'Karadeniz\'de evler birbirinden uzaktır (dağınık); İç Anadolu\'da ise su kuyusu etrafında toplu yerleşme görülür.');
    addQ(2, 11, 1, 'İç Anadolu ve Güneydoğu Anadolu\'da su kaynaklarının kıt, yer şekillerinin düz olması hangi yerleşme tipini zorunlu kılmıştır?', 'Toplu Yerleşme', 'Dağınık Yerleşme', 'Kıyı Yerleşmesi', 'Orman İçi Yerleşme', 'Dalgın Yerleşme', 'A', 'Su kaynaklarının sınırlı olduğu kurak bölgelerde köyler su kaynağı etrafında toplu kurulur.');
    addQ(2, 11, 1, 'Türkiye\'de nüfus artış hızının en yüksek olduğu (patlama yaptığı) dönem hangisidir?', '1955-1960 dönemi (Binde 28.5)', '1927-1935', '1940-1945', '2000-2005', '2015-2020', 'A', 'Savaş tehdidinin bitmesi, sağlık şartlarının iyileşmesiyle 1955-60 arası nüfus patlaması yaşanmıştır.');
    addQ(2, 11, 1, 'Türkiye\'de iç göçün en önemli ve belirleyici sebebi aşağıdakilerden hangisidir?', 'Ekonomik nedenler (İş imkanları ve sanayileşme)', 'Eğitim', 'Sağlık', 'Doğal afetler', 'Güvenlik', 'A', 'Kırsal alanda tarımda makineleşmeyle işsiz kalan nüfus sanayi kentlerine göç etmiştir.');
    addQ(2, 11, 1, 'Yaz mevsiminde tarım, inşaat veya turizm amacıyla başka şehirlere gidilip sonbaharda geri dönülen göç türüne ne ad verilir?', 'Mevsimlik (Geçici) Göç', 'Sürekli Göç', 'Mübadele Göçü', 'Beyin Göçü', 'Sığınmacı Göçü', 'A', 'Çukurova\'ya pamuk, Karadeniz\'e fındık, Akdeniz\'e turizm için giden işçiler mevsimlik göçmenlerdir.');
    addQ(2, 11, 1, 'Lozan Barış Antlaşması uyarınca Türkiye ile Yunanistan arasında gerçekleşen zorunlu nüfus değişimine ne ad verilir?', 'Etabli (Mübadele) Göçü', 'Beyin Göçü', 'İşçi Göçü', 'Mülteci Göçü', 'İltica', 'A', '1923 Türk-Yunan Mübadelesi ile Batı Trakya ve İstanbul hariç karşılıklı nüfus değişimi yapılmıştır.');

    // Level 2: Orta Düzey
    addQ(2, 11, 2, 'Aşağıdaki kırsal yerleşmelerden hangisi "köy altı geçici yerleşmeler" arasında yer alır?', 'Yayla, Kom, Ağıl, Oba, Dam', 'Divan, Mahalle, Çiftlik, Mezra', 'Kasaba', 'Belde', 'Köy', 'A', 'Yayla, kom, ağıl, oba hayvancılık amaçlı geçici yerleşmelerdir. Divan, mezra, mahalle, çiftlik ise süreklidir.');
    addQ(2, 11, 2, 'Batı Karadeniz\'e (Bolu, Sinop, Kastamonu) özgü olan, birkaç mahallenin bir araya gelmesiyle oluşan sürekli köy altı yerleşmesi hangisidir?', 'Divan', 'Mezra', 'Kom', 'Ağıl', 'Oba', 'A', 'Divan Batı Karadeniz\'de ormanlık alanlardaki sürekli köy altı yerleşmesidir.');
    addQ(2, 11, 2, 'Doğu Anadolu\'da yaygın olan, genellikle büyükbaş hayvancılık yapılan ve kışın terk edilen geçici yerleşmeye ne ad verilir?', 'Kom', 'Divan', 'Dalyan', 'Çiftlik', 'Mahalle', 'A', 'Kom Doğu Anadolu\'da taş binalı küçük hayvancılık yerleşmesidir.');
    addQ(2, 11, 2, 'Ege ve Akdeniz kıyılarında balık üretimi ve avcılığı amacıyla kurulan geçici kıyı yerleşmesine ne ad verilir?', 'Dalyan', 'Oba', 'Dam', 'Ağıl', 'Güzle', 'A', 'Dalyan deniz veya lagün kıyılarında kurulan balıkçılık yerleşmeleridir.');
    addQ(2, 11, 2, 'Tarımsal nüfus yoğunluğu tarımla uğraşan nüfusun tarım alanlarına bölünmesiyle bulunur. Aşağıdaki illerin hangisinde tarımsal nüfus yoğunluğu en fazladır?', 'Rize ve Hakkari', 'Konya', 'Şanlıurfa', 'Adana', 'Edirne', 'A', 'Tarım arazisi çok dar ve engebeli olduğu için Doğu Karadeniz ve Hakkari\'de tarımsal yoğunluk çok yüksektir.');
    addQ(2, 11, 2, 'Fizyolojik nüfus yoğunluğu toplam nüfusun tarım alanlarına bölünmesiyle bulunur. Türkiye\'de fizyolojik nüfus yoğunluğu nerede en yüksektir?', 'İstanbul ve Çatalca-Kocaeli', 'Konya', 'Sivas', 'Yozgat', 'Kars', 'A', 'İstanbul\'da toplam nüfus 16 milyonu aşarken tarım arazisi neredeyse yok denecek kadar azdır.');
    addQ(2, 11, 2, 'Türkiye\'de 65 yaş ve üzeri yaşlı nüfus oranının artması, ortanca yaşın yükselmesi neyin göstergesidir?', 'Nüfusun yaşlanmakta olduğunun ve gelişmişlik düzeyinin arttığının', 'Doğum oranlarının arttığının', 'Ölüm oranlarının patladığının', 'Eğitimin çöktüğünün', 'Tarıma dönüldüğünün', 'A', 'Sağlık koşullarının iyileşmesi ve ortalama ömrün uzamasıyla Türkiye demografik dönüşüm yaşamaktadır.');
    addQ(2, 11, 2, 'Aşağıdaki alanlardan hangisi Türkiye\'de yer şekillerinin engebeli veya karstik olması sebebiyle nüfus yoğunluğunun düşük olduğu yerlerden biridir?', 'Teke ve Taşeli Platoları ile Menteşe Yöresi', 'Çukurova', 'Kıyı Ege ovaları', 'Bursa Ovası', 'Adapazarı Ovası', 'A', 'Menteşe aşırı engebeli; Teke ve Taşeli ise karstik, çorak ve engebeli olduğu için nüfus tenhadır.');
    addQ(2, 11, 2, 'Türkiye\'de Adrese Dayalı Nüfus Kayıt Sistemi (ADNKS) hangi yıldan itibaren uygulanmaya başlanmıştır?', '2007', '1990', '2000', '1985', '2015', 'A', '2007 yılından itibaren sokağa çıkma yasaklı sayımlar terk edilmiş ve ADNKS\'ye geçilmiştir.');
    addQ(2, 11, 2, 'Türkiye\'nin yurt dışına ilk resmi kitlesel işçi göçü 1961 yılında hangi ülkeyle imzalanan anlaşmayla başlamıştır?', 'Almanya', 'Fransa', 'Avusturya', 'Hollanda', 'Belçika', 'A', '30 Ekim 1961\'de imzalanan Türk-Alman İşgücü Anlaşması ile yüz binlerce vatandaşımız Almanya\'ya gitmiştir.');

    // Level 3: Zor & Detay
    addQ(2, 11, 3, 'Tuz Gölü çevresi, Taşeli Platosu ve Yıldız Dağları\'nın nüfusunun seyrek olmasının ortak ve farklı sebepleri nelerdir?', 'Tuz Gölü kuraklık, Yıldız Dağları engebe ve ana yollara uzaklık, Taşeli karstik yapı', 'Hepsi engebedir', 'Hepsi sanayi bölgesidir', 'Hepsi maden bölgesidir', 'Hepsi heyelan alanıdır', 'A', 'Farklı coğrafi faktörler (iklim/kuraklık, litoloji/karstik, morfoloji/engebe) nüfusun tenhalaşmasına yol açar.');
    addQ(2, 11, 3, 'Büyükşehir statüsüne geçebilmek için bir ilin toplam nüfusunun en az ne kadar olması kanunen zorunludur?', '750.000', '500.000', '1.000.000', '250.000', '300.000', 'A', '5216 ve 6360 sayılı kanunlara göre büyükşehir belediyesi kurulması için toplam nüfusun en az 750 bin olması gerekir.');
    addQ(2, 11, 3, '6360 sayılı Büyükşehir Kanunu ile büyükşehir belediyesi olan illerde köy ve beldelerin tüzel kişiliği neye dönüştürülmüştür?', 'Mahalle', 'İlçe', 'Kasaba', 'Mezra', 'Bucak', 'A', 'Büyükşehir sınırları il mülki sınırı yapılmış, köyler mahalleye dönüştürülerek köy statüsü kaldırılmıştır.');
    addQ(2, 11, 3, 'Toros Dağları üzerinde konargöçer yaşayan Yörüklerin kıl çadırlardan oluşan geçici yerleşmelerine ne denir?', 'Oba', 'Kom', 'Divan', 'Ağıl', 'Çiftlik', 'A', 'Oba Yörük kültürünün geleneksel çadır yerleşmesidir.');
    addQ(2, 11, 3, 'Karadeniz\'de yayla yerleşmelerinin son yıllarda hayvancılık işlevinin yerini hangi ekonomik sektör almaya başlamıştır?', 'Eko-turizm ve yayla turizmi', 'Sanayi', 'Madencilik', 'Ticaret', 'Ormancılık', 'A', 'Ayder, Uzungöl gibi yaylalar yayla turizminin cazibe merkezine dönüşmüştür.');
    addQ(2, 11, 3, 'Türkiye nüfus piramidinin tabanının giderek daralması aşağıdakilerden hangisinin kesin kanıtıdır?', 'Doğum oranlarının azaldığının', 'Ölümlerin arttığının', 'Nüfusun azaldığının', 'Dış göç verildiğinin', 'Tarımın bittiğinin', 'A', 'Tabanın daralması 0-4 yaş çocuk sayısının azaldığını ve doğurganlığın düştüğünü gösterir.');
    addQ(2, 11, 3, 'Nüfus piramidinin üst kısmının (65+ yaş) genişlemesi neyi ifade eder?', 'Yaşam kalitesinin ve ortalama yaşam süresinin uzadığını', 'Savaş çıktığını', 'Genç nüfusun arttığını', 'İşsizliğin bittiğini', 'Emeklilik yaşının düştüğünü', 'A', 'Gelişmiş ülkelerdeki gibi yaşlı nüfus oranının artması sağlık ve refah koşullarının geliştiğini gösterir.');
    addQ(2, 11, 3, 'Türkiye\'de net göç hızı en yüksek olan ve sürekli dışarıdan nitelikli göç alan bölge hangisidir?', 'Marmara (Çatalca-Kocaeli alt bölgesi)', 'Doğu Anadolu', 'Güneydoğu Anadolu', 'Karadeniz', 'İç Anadolu', 'A', 'İş olanakları ve eğitim nedeniyle Marmara net göç hızında daima zirvededir.');
    addQ(2, 11, 3, 'Güneydoğu Anadolu Projesi (GAP) ile birlikte bölgeden batıya yapılan mevsimlik işçi göçünde nasıl bir değişim yaşanmıştır?', 'Sulu tarımla birlikte bölge içi istihdam artmış ve mevsimlik göç azalmıştır', 'Göç tamamen durmuştur', 'Dış göç patlamıştır', 'Göç iki katına çıkmıştır', 'Hiç değişmemiştir', 'A', 'GAP sulaması pamuk ve mısır üretimini Güneydoğu\'ya taşımış, işgücünü kendi bölgesinde tutmuştur.');
    addQ(2, 11, 3, 'İç Anadolu\'da kırsal meskenlerde yapı malzemesi olarak kerpiç, Karadeniz\'de ahşap, Akdeniz ve Güneydoğu\'da taş kullanılmasının temel nedeni nedir?', 'Doğal çevrede bulunan hakim yapı malzemesinin kullanılması', 'Kültürel zevkler', 'Deprem yönetmeliği', 'Gelir düzeyi', 'Padişah fermanları', 'A', 'Kırsal kesimde meskenler çevredeki doğal kaynaklara (orman varsa ahşap, kireçtaşı varsa taş, killi toprak varsa kerpiç) göre inşa edilir.');

    // -------------------------------------------------------------------------
    // Subcat 12: Türkiye Tarım, Hayvancılık ve Madenler
    // -------------------------------------------------------------------------
    // Level 1: Temel Ekonomik Coğrafya
    addQ(2, 12, 1, 'Türkiye\'de üretimi devlet kontrolünde olan, uyuşturucu yapımında kullanıldığı için izinle ekilen ürünler hangileridir?', 'Haşhaş ve Kenevir', 'Pamuk ve Mısır', 'Buğday ve Arpa', 'Çay ve Fındık', 'Zeytin ve Üzüm', 'A', 'Haşhaş (Afyon) ve Kenevir narkotik özellikleri nedeniyle TMO ve İçişleri izniyle ekilir.');
    addQ(2, 12, 1, 'Türkiye\'nin dünya üretiminde ve ihracatında açık ara birinci olduğu tarım ürünleri hangileridir?', 'Fındık, Kuru İncir, Kuru Kayısı, Kiraz', 'Buğday ve Pirinç', 'Muz ve Kahve', 'Pamuk ve Mısır', 'Soya ve Kakao', 'A', 'Türkiye fındık, incir, kayısı ve kiraz üretiminde dünya lideridir.');
    addQ(2, 12, 1, 'Türkiye\'de bozkır bitki örtüsünün yaygın olduğu İç Anadolu\'da en çok yapılan hayvancılık türü nedir?', 'Küçükbaş Hayvancılık (Koyun-Keçi)', 'Büyükbaş Hayvancılık', 'İpek Böcekçiliği', 'Kümes Hayvancılığı', 'Balıkçılık', 'A', 'Bozkır otları kısa boylu olduğu için küçükbaş koyun (özellikle Karaman koyunu) yetiştiriciliğine uygundur.');
    addQ(2, 12, 1, 'Erzurum-Kars platosunda yaz yağmurlarıyla yeşeren gür çayırlarda en yaygın yapılan hayvancılık faaliyeti nedir?', 'Büyükbaş Mera Hayvancılığı', 'Küçükbaş Koyunculuk', 'Tiftik Keçisi', 'Kıl Keçisi', 'Arıcılık', 'A', 'Gür alpin çayırlar sığır ve büyükbaş mera hayvancılığını geliştirmiştir.');
    addQ(2, 12, 1, 'Toros Dağları\'nın dik ve kayalık yamaçlarında makilerle beslenen, ormanlara zarar verdiği için sınırlandırılan keçi türü hangisidir?', 'Kıl Keçisi', 'Tiftik Keçisi (Ankara Keçisi)', 'Merinos Koyunu', 'Kıvırcık Koyun', 'Saanen Keçisi', 'A', 'Kıl keçisi Akdeniz Toroslarında yaygındır.');
    addQ(2, 12, 1, 'Dünya rezervlerinin yaklaşık %73\'ü Türkiye\'de bulunan, roket yakıtı, cam ve seramik sanayisinde kullanılan stratejik maden hangisidir?', 'Bor Mineralleri', 'Demir', 'Bakır', 'Krom', 'Boksit', 'A', 'Balıkesir Susurluk, Kütahya Emet, Eskişehir Kırka ve Bursa Mustafa Kemal Paşa\'da zengin bor yatakları vardır.');
    addQ(2, 12, 1, 'Türkiye\'de çıkarılan tek Taş Kömürü (I. Jeolojik Zaman / Paleozoyik kökenli) havzamız neresidir?', 'Zonguldak Havzası (Ereğli-Karabük)', 'Soma', 'Afşin-Elbistan', 'Yatağan', 'Tunçbilek', 'A', 'Taş kömürü sadece Zonguldak ve çevresindedir ve demir-çelik sanayisinde enerji kaynağı olarak kullanılır.');
    addQ(2, 12, 1, 'III. Jeolojik zamanda oluşan, kalorisi taş kömüründen düşük ancak Türkiye\'nin hemen her bölgesinde bolca bulunan kömür türü nedir?', 'Linyit Kömürü', 'Taş Kömürü', 'Antrasit', 'Kok Kömürü', 'Torf', 'A', 'Linyit yatakları termik santrallerimizde (Afşin-Elbistan, Soma, Yatağan) elektrik üretiminde kullanılır.');
    addQ(2, 12, 1, 'Türkiye\'nin ilk petrol kuyusu nerede açılmıştır ve en çok petrol çıkarılan ilimiz neresidir?', 'Batman (Raman Dağı)', 'Diyarbakır', 'Adıyaman', 'Siirt', 'Şırnak (Gabar)', 'A', '1940\'ta Raman Dağı\'nda petrol bulunmuş ve Batman Rafinerisi kurulmuştur.');
    addQ(2, 12, 1, 'Jeotermal enerji (yer altı sıcak su buharı) ile elektrik üreten santrallerimiz ilk olarak nerede kurulmuştur?', 'Denizli Sarayköy ve Aydın Germencik', 'İzmir Aliağa', 'Kocaeli Dilovası', 'Bursa Orhangazi', 'Afyon Sandıklı', 'A', 'Kırıklı fay hatlarının çok olduğu Ege Bölgesi jeotermal elektrik üretiminin merkezidir.');

    // Level 2: Orta Düzey
    addQ(2, 12, 2, 'Paslanmaz çelik yapımında kullanılan, Elazığ Guleman ve Muğla Fethiye-Köyceğiz\'de çıkarılan maden hangisidir?', 'Krom', 'Bakır', 'Boksit', 'Kurşun', 'Çinko', 'A', 'Krom paslanmaz çelik sanayisinin ana maddesidir. Antalya ve Elazığ\'da ferrokrom tesisleri vardır.');
    addQ(2, 12, 2, 'Alüminyumun hammaddesi olan ve Antalya Akseki ile Konya Seydişehir\'de çıkarılıp işlenen maden hangisidir?', 'Boksit', 'Barit', 'Mermer', 'Asbest', 'Kükürt', 'A', 'Seydişehir Alüminyum Fabrikası boksit madenini işler.');
    addQ(2, 12, 2, 'Elektrik-elektronik sanayisinde iletken olarak yaygın kullanılan, Artvin Murgul, Rize Çayeli ve Kastamonu Küre\'de çıkarılan maden hangisidir?', 'Bakır', 'Demir', 'Krom', 'Cıva', 'Antimon', 'A', 'Samsun Bakır İşletmeleri\'nde Karadeniz bakırları izabe edilir.');
    addQ(2, 12, 2, 'Petrol taşımacılığında petrol rafinerilerimiz hangi illerimizde yer almaktadır?', 'Batman, İzmir (Aliağa), Kocaeli (İpraş), Kırıkkale (Orta Anadolu)', 'Adana, Mersin', 'İstanbul, Ankara', 'Antalya, Samsun', 'Zonguldak, Trabzon', 'A', 'Batman hammaddenin yanında; İzmir ve İzmit liman avantajı; Kırıkkale ise stratejik iç güvenlik avantajıyla kurulmuştur.');
    addQ(2, 12, 2, 'Türkiye\'nin ilk nükleer güç santrali nerede inşa edilmektedir?', 'Mersin - Akkuyu', 'Sinop - İnceburun', 'Kırklareli - İğneada', 'İzmir - Çeşme', 'Balıkesir - Bandırma', 'A', 'Akkuyu Nükleer Güç Santrali 4 reaktörlü devasa bir nükleer projedir.');
    addQ(2, 12, 2, 'Türkiye\'de rüzgar enerjisi santrallerinin (RES) en çok yoğunlaştığı bölge hangisidir?', 'Ege ve Marmara (İzmir, Balıkesir, Çanakkale, Manisa)', 'Karadeniz', 'Doğu Anadolu', 'Güneydoğu Anadolu', 'İç Anadolu', 'A', 'Sürekli ve güçlü rüzgar alan Çanakkale Boğazı ve Ege kıyıları RES yatırımlarının merkezidir.');
    addQ(2, 12, 2, 'Demir-çelik fabrikalarının Karabük ve Ereğli\'de kurulmasının temel sebebi nedir?', 'Taş kömürü yataklarına (Enerji kaynağına) yakınlık', 'Demir madenine yakınlık', 'Pazara yakınlık', 'İşgücü ucuzluğu', 'Ulaşım kolaylığı', 'A', 'Karabük ve İskenderun örnekleri: Karabük enerjiye yakınlık, İskenderun ise liman (ulaşım) avantajıyla kurulmuştur.');
    addQ(2, 12, 2, 'GAP projesi sonrasında Güneydoğu Anadolu\'da üretimi katlanarak Türkiye birincisi haline gelen tarım ürünü hangisidir?', 'Pamuk', 'Çay', 'Fındık', 'Şeker Pancarı', 'Zeytin', 'A', 'Şanlıurfa Ovası sulamaya açılınca Çukurova\'yı geçerek Türkiye pamuk üretiminin yarısından fazlasını karşılar hale gelmiştir.');
    addQ(2, 12, 2, 'Güneşlenme süresinin yetersiz olması ve her mevsim yağışlı geçmesi sebebiyle Karadeniz kıyılarında üretimi yapılamayan ürün grubu hangisidir?', 'Pamuk ve Buğday (Yaz kuraklığı isteyenler)', 'Çay', 'Fındık', 'Mısır', 'Kivi', 'A', 'Pamuk ve buğday olgunlaşma ve hasat döneminde mutlaka kavurucu yaz kuraklığı ister; Karadeniz\'de yazın da yağış olduğu için yetişmez.');
    addQ(2, 12, 2, 'Türkiye\'de şeker fabrikalarının hammaddeye yakın yerlerde kurulmasının zorunlu olmasının sebebi nedir?', 'Şeker pancarının hasat edildikten sonra çok kısa sürede bozulması ve şeker oranının düşmesi', 'Nakliyesinin çok pahalı olması', 'İşçilerin tarlada yaşaması', 'Devlet teşviki', 'Su kaynakları', 'A', 'Şeker pancarı çabuk bozulduğu için fabrikalar pancar ekim sahalarının hemen yanına kurulur, küspesi de besi hayvancılığında kullanılır.');

    // Level 3: Zor & Detay
    addQ(2, 12, 3, 'Petrol ve doğalgaz sondaj kuyularında çamur ağırlaştırıcı olarak kullanılan, Alanya ve Gazipaşa\'da bolca çıkarılan maden hangisidir?', 'Barit', 'Mermer', 'Feldspat', 'Lüle Taşı', 'Oltu Taşı', 'A', 'Barit yüksek yoğunluğu nedeniyle sondaj çamurlarında basınç dengeleyici olarak kullanılır.');
    addQ(2, 12, 3, 'Eskişehir\'de çıkarılan süs eşyası ve pipo yapımında kullanılan beyaz renkli mineral ile Erzurum\'da çıkarılan siyah renkli kehribar taşları sırasıyla hangileridir?', 'Lüle Taşı (Eskişehir) - Oltu Taşı (Erzurum)', 'Mermer - Granit', 'Kuvars - Ametist', 'Oniks - Akik', 'Zümrüt - Yakut', 'A', 'Eskişehir Lüle taşı, Erzurum Oltu taşı el sanatları ve hediyelik eşya simgesidir.');
    addQ(2, 12, 3, 'Türkiye\'nin ihraç ettiği madenler içinde parasal gelir bakımından birinci sırada yer alan maden hangisidir?', 'İşlenmiş ve Blok Mermer (Doğal Taşlar)', 'Bor', 'Krom', 'Demir', 'Bakır', 'A', 'Afyon, Marmara Adası, Bilecik ve Elazığ mermerleri Türkiye\'nin maden ihracat şampiyonudur.');
    addQ(2, 12, 3, 'Nadas tarımının (toprağı bir yıl ekmeyip dinlendirme) en yaygın olduğu ve erozyonu tetiklediği bölge hangisidir?', 'İç Anadolu ve Güneydoğu Anadolu', 'Karadeniz', 'Akdeniz', 'Marmara', 'Kıyı Ege', 'A', 'Kuraklık ve sulama yetersizliği nedeniyle İç Anadolu\'da nadas çoktur; sulama geliştikçe nadas azalır.');
    addQ(2, 12, 3, 'Aşağıdaki tarım ürünlerinden hangisinin ekim alanı devlet tekelinde OLMAMASINA rağmen iklim seçiciliği yüzünden en dardır?', 'Çay ve Muz', 'Haşhaş', 'Tütün', 'Pirinç', 'Kenevir', 'A', 'Çay sadece Doğu Karadeniz kıyılarında, Muz sadece Akdeniz mikroklimasında yetişebilir.');
    addQ(2, 12, 3, 'Pirinç (çeltik) üretim alanlarının devlet iznine ve kontrolüne tabi olmasının gerçek halk sağlığı gerekçesi nedir?', 'Sıtma hastalığına yol açan sivrisinek üremesini engellemek', 'Uyuşturucu yapımı', 'Toprağı tuzlandırması', 'Pahalı olması', 'Kota uygulaması', 'A', 'Çeltik bataklık suda yetiştiği için sivrisinek üremesini ve sıtma salgınını önlemek amacıyla yerleşim yerlerinden uzağa izinle ekilir.');
    addQ(2, 12, 3, 'Türkiye\'de arıcılık faaliyetlerinin ve bal üretiminin en kaliteli ve yaygın olduğu dağlık ve zengin bitki örtülü illerimiz hangileridir?', 'Muğla (Çam balı), Ordu, Rize (Anzer), Hakkari, Kars', 'Konya ve Aksaray', 'Edirne ve Tekirdağ', 'Şanlıurfa', 'Gaziantep', 'A', 'Muğla çam balında dünya merkezidir; Ordu, Rize ve Doğu Anadolu yaylaları çiçek balında öncüdür.');
    addQ(2, 12, 3, 'Büyükşehirlerin etrafında (İstanbul, Ankara, İzmir, Bolu, Balıkesir) besi ve kümes hayvancılığının aşırı gelişmiş olmasının temel nedeni nedir?', 'Tüketici nüfusun fazlalığı ve hızlı pazarlama imkanı (Pazara yakınlık)', 'İklimin uygunluğu', 'Yem bitkilerinin çokluğu', 'Geniş meraların varlığı', 'Su kaynakları', 'A', 'Besi ve kümes hayvancılığı iklime bağımlı değildir; kapalı çiftliklerde büyük kentlerin günlük et ve yumurta ihtiyacını karşılar.');
    addQ(2, 12, 3, 'Deniz balıkçılığında Türkiye toplam balık avının yaklaşık %75\'ini tek başına karşılayan denizimiz hangisidir?', 'Karadeniz', 'Marmara Denizi', 'Ege Denizi', 'Akdeniz', 'Van Gölü', 'A', 'Karadeniz besin maddesi (plankton) zenginliği ve oksijen bolluğu nedeniyle en çok balık avlanan denizimizdir.');
    addQ(2, 12, 3, 'Türkiye\'de yer altı kaynaklarından doğal gaz üretimi hangi tesislerde yapılmaktadır?', 'Kırklareli - Hamitabat, Mardin - Çamurlu ve Sakarya Gaz Sahası (Filyos)', 'Batman Raman', 'Soma', 'Yatağan', 'Seydişehir', 'A', 'Trakya Hamitabat ve Karadeniz Sakarya Gaz Sahası yerli doğalgaz üretimimizin ana kaynaklarıdır.');

};
