// KPSS Tarih Complete Bank (210 Questions - 7 Subcategories, 3 Levels, 10 Q per level)
module.exports = function (addQ) {
// KPSS Tarih Authentic Questions Bank (210 Questions - 7 Subcategories, 3 Levels, 10 Q per level)
// Category: 1 (Tarih)


    // -------------------------------------------------------------------------
    // Subcat 1: İslamiyet Öncesi Türk Tarihi
    // -------------------------------------------------------------------------
    // Level 1: Temel Kavramlar & Devletler
    addQ(1, 1, 1, 'İslamiyet öncesi Türk devletlerinde hükümdara yönetme yetkisinin Gök Tengri tarafından verildiği inancına ne ad verilir?', 'Kut', 'Kurultay', 'Yargu', 'Töre', 'Toygun', 'A', 'Kut inancı kan yoluyla babadan oğula geçen kutsal egemenlik anlayışıdır.');
    addQ(1, 1, 1, 'Tarihte bilinen ilk Türk devleti aşağıdakilerden hangisidir?', 'Göktürkler', 'Asya Hun Devleti', 'Uygurlar', 'Avarlar', 'Hazarlar', 'B', 'Bilinen ilk teşkilatlı Türk devleti Asya Hun Devleti olup kurucusu Teoman\'dır.');
    addQ(1, 1, 1, 'İlk kez yerleşik hayata geçen ve Maniheizm dinini kabul eden Türk devleti hangisidir?', 'Köktürkler', 'Hunlar', 'Uygurlar', 'Karluklar', 'Kırgızlar', 'C', 'Bögü Kağan döneminde Maniheizmi kabul eden Uygurlar yerleşik hayata geçmiştir.');
    addQ(1, 1, 1, 'Türk adıyla kurulan ilk devlet aşağıdakilerden hangisidir?', 'I. Göktürk Devleti', 'Asya Hun Devleti', 'Kutluk Devleti', 'Uygur Devleti', 'Akhunlar', 'A', 'Bumin Kağan tarafından 552 yılında kurulan Göktürk Devleti, Türk adını resmi olarak kullanan ilk devlettir.');
    addQ(1, 1, 1, 'Türk tarihinin ilk yazılı belgeleri kabul edilen Orhun Abideleri hangi devlet dönemine aittir?', 'Asya Hun Devleti', 'II. Göktürk (Kutluk) Devleti', 'Uygurlar', 'Hazarlar', 'Karahanlılar', 'B', 'Orhun Kitabeleri (Kül Tigin, Bilge Kağan, Tonyukuk) II. Göktürk Devleti döneminde dikilmiştir.');
    addQ(1, 1, 1, 'İslamiyet öncesi Türklerde ölen kişinin ardından yakılan ağıta ne denirdi?', 'Yuğ', 'Sagu', 'Koşuk', 'Balbal', 'Kurgan', 'B', 'Cenaze törenine Yuğ, okunan ağıtlara ise Sagu denir.');
    addQ(1, 1, 1, 'Eski Türklerde devlet işlerinin görüşülüp karara bağlandığı meclise ne ad verilirdi?', 'Kurultay (Toy)', 'Pankuş', 'Senato', 'Divan', 'Tiyanşan', 'A', 'Kurultay, hükümdar, hatun ve boy beylerinin katıldığı karar ve danışma organıdır.');
    addQ(1, 1, 1, 'Orduda onluk teşkilatlanma sistemini ilk kuran Türk hükümdarı kimdir?', 'Teoman', 'Mete Han', 'Bumin Kağan', 'İlteriş Kağan', 'Attila', 'B', 'Mete Han MÖ 209 yılında onluk sistemi kurmuş ve TSK\'nın kuruluş yılı kabul edilmiştir.');
    addQ(1, 1, 1, 'Eski Türklerde mezarların başına dikilen insan heykeli şeklindeki taşlara ne denir?', 'Kurgan', 'Balbal', 'Stupa', 'Kümbet', 'Yurt', 'B', 'Balballar, kişinin hayattayken öldürdüğü düşman sayısını simgeleyen mezar taşlarıdır.');
    addQ(1, 1, 1, 'Musevilik dinini benimseyen tek Türk devleti aşağıdakilerden hangisidir?', 'Peçenekler', 'Hazarlar', 'Bulgarlar', 'Kumanlar', 'Avarlar', 'B', 'Hazarlar yöneticileri Museviliği kabul eden tek Türk devletidir.');

    // Level 2: Orta Düzey & Teşkilat
    addQ(1, 1, 2, 'Eski Türk devletlerinde hükümdarın erkek çocuklarına ne unvan verilirdi?', 'Tigin', 'Şad', 'İnanç', 'Ataman', 'Subaşı', 'A', 'Hükümdarın oğullarına Tigin denir. Tiginleri eğiten kişilere ise Ataman veya İnal denirdi.');
    addQ(1, 1, 2, 'Kutluk Devleti\'nin kurucusu olan ve devleti derleyip toplayan anlamına gelen unvanı alan kağan kimdir?', 'Bumin Kağan', 'Kutluk (İlteriş) Kağan', 'Kapgan Kağan', 'Bilge Kağan', 'Mukan Kağan', 'B', 'İlteriş unvanı ili/devleti derleyen toplayan anlamına gelir.');
    addQ(1, 1, 2, 'Avrupa Hun Devleti\'nin en parlak dönemini yaşatan ve Avrupalılarca "Tanrı\'nın Kırbacı" olarak anılan hükümdar kimdir?', 'Balamir', 'Uldız', 'Rua', 'Attila', 'Dengezik', 'D', 'Attila Nibelungen destanında da Etzel adıyla anılan büyük fatihtir.');
    addQ(1, 1, 2, 'Kendi adına para bastıran ilk Türk hükümdarı aşağıdakilerden hangisidir?', 'Baga Tarkan', 'Mete Han', 'Bumin Kağan', 'Mukan Kağan', 'Kül Tigin', 'A', 'Türgiş hükümdarı Baga Tarkan kendi adına madeni para bastıran ilk Türk hükümdarıdır.');
    addQ(1, 1, 2, 'İslamiyet öncesi Türklerde yazısız hukuk kurallarına ne ad verilirdi?', 'Töre', 'Yasa', 'Fıkıh', 'Buyruk', 'Şeriat', 'A', 'Töre, örf ve adetlerden beslenen esnek ancak hükümdarın dahi uymak zorunda olduğu yazısız hukuk kurallarıdır.');
    addQ(1, 1, 2, 'Eski Türk devlet teşkilatında doğuyu asıl hükümdar, batıyı ise yabgu unvanıyla hanedan üyesi yönetirdi. Bu yönetim tarzına ne denir?', 'İkili Teşkilat', 'Feodalite', 'Monarşi', 'Oligarşi', 'Merkeziyetçilik', 'A', 'Türklerde federal yapının göstergesi olan yönetim tarzı İkili Teşkilattır.');
    addQ(1, 1, 2, 'Hristiyanlığı kabul ederek hem Slavlaşan hem de İstanbul\'u ilk kuşatan Türk devleti hangisidir?', 'Avarlar', 'Hazarlar', 'Bulgarlar', 'Macarlar', 'Uygurlar', 'A', 'Avarlar (Juan-Juan) Sasaniler ile birleşerek İstanbul\'u ilk kez kuşatan Türk devletidir.');
    addQ(1, 1, 2, 'Bizans ordusunda ücretli askerlik yaparken Malazgirt Savaşı\'nda Alparslan\'ın tarafına geçen Türk toplulukları hangileridir?', 'Peçenekler ve Uzlar', 'Kumanlar ve Hazarlar', 'Karluklar ve Kırgızlar', 'Bulgarlar ve Macarlar', 'Avarlar ve Türgişler', 'A', 'Peçenekler ve Uzlar Malazgirt Savaşı\'nda taraf değiştirerek zaferde kilit rol oynamışlardır.');
    addQ(1, 1, 2, 'Cengiz Han\'a itaat eden ilk Türk devleti ve ilk Müslüman Türk topluluğu sırasıyla hangileridir?', 'Kırgızlar - Karluklar', 'Uygurlar - Oğuzlar', 'Hazarlar - Kumanlar', 'Kıpçaklar - Peçenekler', 'Göktürkler - Türgişler', 'A', 'Moğollara itaat eden ilk Türk devleti Kırgızlar, ilk Müslüman Türk topluluğu ise Karluklardır.');
    addQ(1, 1, 2, 'Eski Türklerde devlet hazinesinden ve mali işlerden sorumlu görevliye ne ad verilirdi?', 'Ağılıg', 'Tudun', 'Yargucı', 'Otacı', 'Tamgacı', 'A', 'Ağılıg maliyeci/hazineci, Tudun ise vergi memuru veya validir.');

    // Level 3: İleri Düzey & ÖSYM Çıkmış / Tuzak Sorular
    addQ(1, 1, 3, 'Orhun Yazıtları\'nı Danimarkalı dilbilimci Vilhelm Thomsen çözmüştür. Bu yazıtlarda adı geçen ilk vezir ve Türklerin ilk tarihçisi kabul edilen devlet adamı kimdir?', 'Tonyukuk', 'Kül Tigin', 'Bilge Kağan', 'İlteriş Kağan', 'Bögü Kağan', 'A', 'Tonyukuk Türk tarihinin ilk veziri ve hatırat yazarı kabul edilir.');
    addQ(1, 1, 3, 'Manas Destanı hangi Türk kavmine aittir ve günümüzde dünyanın en uzun destanı kabul edilir?', 'Kırgızlar', 'Kazaklar', 'Özbekler', 'Uygurlar', 'Tatarlar', 'A', 'Kırgızlara ait Manas Destanı yaşayan ve en uzun Türk destanıdır.');
    addQ(1, 1, 3, 'Eski Türklerde hükümdarın eşi olan Hatun\'un elçi kabul etmesi ve kurultaya katılması aşağıdakilerden hangisinin doğrudan kanıtıdır?', 'Kadının devlet yönetiminde söz sahibi olduğunun', 'Monarşinin zayıfladığının', 'Çok eşliliğin yaygın olduğunun', 'Törenin hiçe sayıldığının', 'Demokrasiye geçildiğinin', 'A', 'Hatun\'un siyasi yetkileri Türk kadınının yönetimdeki saygın statüsünü gösterir.');
    addQ(1, 1, 3, 'Uygurların kütüphaneler kurması, matbaa ve kâğıt kullanması, fresk (duvar resmi) ve minyatür yapması neyin doğrudan bir sonucudur?', 'Yerleşik hayata geçmelerinin', 'Savaşçı özelliklerini kaybetmelerinin', 'Çin\'e bağımlı olmalarının', 'Kut inancını terk etmelerinin', 'Göçebe kalmalarının', 'A', 'Yerleşik kültür mimari, sanat, kütüphanecilik ve şehirleşmeyi geliştirmiştir.');
    addQ(1, 1, 3, 'Oğuz Kağan Destanı\'nda anlatılan hükümdarın tarihsel olarak hangi Hun hükümdarı ile özdeşleştiği kabul edilir?', 'Mete Han', 'Teoman', 'Attila', 'Bumin Kağan', 'İlteriş Kağan', 'A', 'Oğuz Kağan Destanı\'ndaki ana kahramanın Mete Han olduğu kabul edilmektedir.');
    addQ(1, 1, 3, 'Talas Savaşı\'nda (751) Müslüman Arapların yanında yer alarak İslamiyet\'in Orta Asya\'da yayılmasını sağlayan Türk boyu hangisidir?', 'Karluklar', 'Oğuzlar', 'Kıpçaklar', 'Peçenekler', 'Türgişler', 'A', 'Karluklar Talas Savaşı\'nda Abbasi ordusuna destek vererek zaferi sağlamış ve topluca İslam\'a geçmiştir.');
    addQ(1, 1, 3, 'Eski Türk toplum yapısında en küçük birimden en büyüğe doğru sıralanış aşağıdakilerden hangisidir?', 'Oguş - Urug - Boy - Bodun - İl', 'Urug - Oguş - Boy - İl - Bodun', 'Boy - Oguş - Urug - İl - Bodun', 'Oguş - Boy - Urug - Bodun - İl', 'İl - Bodun - Boy - Urug - Oguş', 'A', 'Oguş (Aile), Urug (Sülale), Boy (Kabile), Bodun (Millet), İl (Devlet).');
    addQ(1, 1, 3, 'Orta Asya\'da yapılan arkeolojik kazılarda Türklerin en eski kültür merkezi kabul edilen yerleşim hangisidir?', 'Anav', 'Afanasyevo', 'Andronovo', 'Karasuk', 'Tagar', 'B', 'Orta Asya\'nın en eski kültürü Anav, Türklere ait en eski kültür ise Afanasyevo\'dur.');
    addQ(1, 1, 3, 'İslamiyet öncesinde Türklerin mezarlara ölüleriyle birlikte değerli eşyalarını ve atlarını koymaları neyin kanıtıdır?', 'Ahiret (ölümden sonraki yaşam) inancının', 'Göçebe hayat tarzının', 'Zengin bir maden kültürünün', 'Şamanların etkisinin', 'Törenin bozulduğunun', 'A', 'Kurganlara eşya konulması ruhun yaşamaya devam ettiği inancını (ahiret) gösterir.');
    addQ(1, 1, 3, 'İpek Yolu egemenliği için Sasanilerle birleşip Akhunları yıkan, ardından Bizans ile anlaşıp Sasanilere karşı cephe alan Türk devleti hangisidir?', 'I. Göktürk Devleti', 'Asya Hun Devleti', 'Uygurlar', 'Kutluk Devleti', 'Karahanlılar', 'A', 'Göktürk Devleti İpek Yolu kontrolü için pragmatik diplomatik ittifaklar kurmuştur.');

    // -------------------------------------------------------------------------
    // Subcat 2: İlk Türk-İslam Devletleri
    // -------------------------------------------------------------------------
    // Level 1: Temel Bilgiler
    addQ(1, 2, 1, 'Orta Asya\'da kurulan ilk Müslüman Türk devleti aşağıdakilerden hangisidir?', 'Karahanlılar', 'Gazneliler', 'Büyük Selçuklu Devleti', 'Tolunoğulları', 'İhşidiler', 'A', 'Satuk Buğra Han döneminde İslamiyet\'i resmi din kabul eden Karahanlılar Orta Asya\'daki ilk Müslüman Türk devletidir.');
    addQ(1, 2, 1, 'Mısır\'da kurulan ilk Müslüman Türk devleti aşağıdakilerden hangisidir?', 'Tolunoğulları', 'İhşidiler', 'Eyyubiler', 'Memlükler', 'Fatımiler', 'A', 'Tolunoğulları (868) Mısır\'da kurulan ilk Türk-İslam devletidir.');
    addQ(1, 2, 1, '1071 Malazgirt Savaşı\'nda Bizans İmparatoru Romen Diyojen\'i mağlup ederek Anadolu\'nun kapılarını Türklere açan Selçuklu sultanı kimdir?', 'Sultan Alparslan', 'Tuğrul Bey', 'Melikşah', 'Sultan Sencer', 'Çağrı Bey', 'A', 'Alparslan 1071 Malazgirt Zaferi ile Türklerin Anadolu\'ya kalıcı yerleşimini sağlamıştır.');
    addQ(1, 2, 1, 'İlk Türkçe siyasetname ve Türk-İslam edebiyatının ilk eseri kabul edilen Kutadgu Bilig kime aittir?', 'Yusuf Has Hacip', 'Kaşgarlı Mahmut', 'Edip Ahmet Yükneki', 'Ahmet Yesevi', 'Nizamülmülk', 'A', 'Kutadgu Bilig (Mutluluk Veren Bilgi) Yusuf Has Hacip tarafından Tabgaç Buğra Han\'a sunulmuştur.');
    addQ(1, 2, 1, 'Araplara Türkçeyi öğretmek ve Türkçenin zenginliğini göstermek amacıyla yazılan ilk Türkçe sözlük hangisidir?', 'Divânu Lugâti\'t-Türk', 'Atabetü\'l Hakayık', 'Divan-ı Hikmet', 'Siyasetname', 'Şehname', 'A', 'Kaşgarlı Mahmut\'un Bağdat\'ta Abbasi Halifesine sunduğu eser Divânu Lugâti\'t-Türk\'tür.');
    addQ(1, 2, 1, 'Sultan unvanını kullanan ilk Türk hükümdarı aşağıdakilerden hangisidir?', 'Gazneli Mahmut', 'Alparslan', 'Tuğrul Bey', 'Satuk Buğra Han', 'Harun Reşid', 'A', 'Gazneli Mahmut Abbasi halifesini Şii Büveyhoğulları baskısından kurtardığı için Sultan unvanını almıştır.');
    addQ(1, 2, 1, 'İlk Türk mutasavvıfı kabul edilen ve Divan-ı Hikmet adlı eserin sahibi olan düşünür kimdir?', 'Hoca Ahmet Yesevi', 'Mevlana', 'Yunus Emre', 'Hacı Bektaş Veli', 'Ahi Evran', 'A', 'Ahmet Yesevi Pir-i Türkistan olarak bilinir ve eseri Divan-ı Hikmet\'tir.');
    addQ(1, 2, 1, 'Büyük Selçuklu Devleti\'nin resmi dili, edebiyat dili ve eğitim dili hangi dildi?', 'Resmi ve edebi dil Farsça, eğitim dili Arapça', 'Türkçe', 'Arapça', 'Süryanice', 'Latince', 'A', 'Selçuklularda saray ve ordu dili Türkçe iken, resmi yazışma dili Farsça, bilim dili Arapça idi.');
    addQ(1, 2, 1, 'Nizamiye Medreselerini kurarak İslam dünyasında eğitimin kurumsallaşmasını sağlayan ünlü vezir kimdir?', 'Nizamülmülk', 'Köprülü Mehmet Paşa', 'Sokullu Mehmet Paşa', 'Vezir Tonyukuk', 'Pargalı İbrahim', 'A', 'Büyük Selçuklu veziri Nizamülmülk Nizamiye medreselerini açmış ve Siyasetname\'yi kaleme almıştır.');
    addQ(1, 2, 1, 'Büyük Selçuklu Devleti\'nin yıkılış sürecine girmesine neden olan 1141 tarihli savaş hangisidir?', 'Katvan Savaşı', 'Dandanakan Savaşı', 'Pasinler Savaşı', 'Yassıçemen Savaşı', 'Kösedağ Savaşı', 'A', 'Karahıtaylar ile yapılan 1141 Katvan Savaşı yenilgisi Büyük Selçuklu\'yu çöküşe götürmüştür.');

    // Level 2: Orta Düzey
    addQ(1, 2, 2, 'Büyük Selçuklu Devleti\'nde hükümdar çocuklarını (melik) devlet yönetimi konusunda eğiten tecrübeli devlet adamlarına ne denirdi?', 'Atabey', 'Lala', 'Ataman', 'Subaşı', 'İnanç', 'A', 'Selçuklularda Atabey, Osmanlıda ise bu kuruma Lala denilmiştir.');
    addQ(1, 2, 2, 'Kudüs\'ü Haçlıların elinden Hıttin Savaşı (1187) ile geri alarak III. Haçlı Seferi\'ne yol açan hükümdar kimdir?', 'Selahaddin Eyyubi', 'Baybars', 'Nureddin Zengi', 'Kutuz', 'Sultan Kalavun', 'A', 'Selahaddin Eyyubi Hıttin Zaferi ile Kudüs\'ü Haçlı işgalinden kurtarmıştır.');
    addQ(1, 2, 2, 'Moğolları tarihte ilk kez durduran Ayn Calut (1260) Savaşı hangi devlete aittir?', 'Memlükler', 'Eyyubiler', 'Büyük Selçuklular', 'Gazneliler', 'Harzemşahlar', 'A', 'Sultan Kutuz ve Baybars komutasındaki Memlük ordusu Moğolları ilk kez Ayn Calut\'ta durdurmuştur.');
    addQ(1, 2, 2, 'Türk-İslam devletlerinde ordu komutanlarına ve güvenlik işlerinden sorumlu kişilere ne ad verilirdi?', 'Subaşı', 'Muhtesip', 'Kadı', 'Hacib', 'Müşrif', 'A', 'Subaşı ordu komutanı ve şehir güvenliğinden sorumlu amirdir.');
    addQ(1, 2, 2, 'Çarşı ve pazarları denetleyen, fiyat ve tartı kontrollerini yapan görevli kimdir?', 'Muhtesip', 'Kadıasker', 'Defterdar', 'Ulak', 'Candar', 'A', 'Muhtesip belediye zabıtası niteliğindedir, piyasa teftişi yapar.');
    addQ(1, 2, 2, 'Karahanlılar Devleti\'nin resmi dili olarak Türkçeyi kullanması neyin bir göstergesidir?', 'Milli kültür ve kimliklerini koruduklarının', 'Arapça bilmediklerinin', 'İslamiyet\'i tam benimsemediklerinin', 'Dışa kapalı bir ekonomi izlediklerinin', 'Ticareti önemsemediklerinin', 'A', 'Karahanlılar halkı ve yöneticisi Türk olan, Türkçeyi resmi dil yapan milli bir devletti.');
    addQ(1, 2, 2, 'Hindistan\'a 17 sefer düzenleyerek İslamiyet\'in bu bölgeye yerleşmesini sağlayan Türk hükümdarı kimdir?', 'Gazneli Mahmut', 'Babür Şah', 'Timur', 'Tuğrul Bey', 'Uluğ Bey', 'A', 'Gazneli Mahmut Hindistan seferleriyle İslamiyet\'in yayılmasına ve kast sisteminin sarsılmasına yol açmıştır.');
    addQ(1, 2, 2, 'Türk-İslam devletlerinde hükümdar ile halk ve hükümdar ile divan üyeleri arasındaki iletişimi sağlayan saray görevlisi kimdir?', 'Hacib (Hacibü\'l-Hüccab)', 'Emir-i Ahur', 'Cameder', 'Silahtar', 'Serhenk', 'A', 'Hacip saray protokolünü düzenler ve sultanın en güvendiği mülki amirdir.');
    addQ(1, 2, 2, 'Selçuklularda ordu mensuplarına ve memurlara maaş yerine gelir getiren toprakların tahsis edildiği sisteme ne denir?', 'İkta Sistemi', 'İltizam', 'Malikane', 'Müsadere', 'Pençik', 'A', 'İkta sistemi hazineden para çıkmadan ordu beslenmesini ve üretimin denetimini sağlamıştır.');
    addQ(1, 2, 2, 'Dandanakan Savaşı (1040) sonucunda bağımsızlığını kazanan ve resmen kurulan devlet hangisidir?', 'Büyük Selçuklu Devleti', 'Gazneliler', 'Karahanlılar', 'Harzemşahlar', 'Eyyubiler', 'A', '1040 Dandanakan Zaferi ile Gazneliler yıkılış sürecine girmiş, Büyük Selçuklular resmen kurulmuştur.');

    // Level 3: Zor & Detay
    addQ(1, 2, 3, 'Büyük Selçuklularda mali işlerden sorumlu ve vergilerin toplanmasını denetleyen divan hangisidir?', 'Divan-ı İstifa', 'Divan-ı Arz', 'Divan-ı İşraf', 'Divan-ı Tuğra', 'Divan-ı Mezalim', 'A', 'Divan-ı İstifa maliyeden sorumlu divandır, başkanı Müstevfidir.');
    addQ(1, 2, 3, 'Devletin idari ve mali işlerinin teftişinden sorumlu olan Selçuklu divanı hangisidir?', 'Divan-ı İşraf', 'Divan-ı İnşa', 'Divan-ı Berid', 'Divan-ı Arz', 'Divan-ı Saltanat', 'A', 'Divan-ı İşraf denetim/teftiş divanı olup başkanı Müşriftir.');
    addQ(1, 2, 3, 'Sultanın başkanlığında toplanan, ağır siyasi suçların ve üst düzey yöneticilerin davalarının görüşüldüğü yüksek mahkeme hangisidir?', 'Divan-ı Mezalim', 'Divan-ı Ahkam', 'Şeri Mahkeme', 'Örfi Mahkeme', 'Yargu', 'A', 'Divan-ı Mezalim adaletin en üst merciidir.');
    addQ(1, 2, 3, 'Hasan Sabbah\'ın kurduğu Batıni (Haşhaşi) tarikatının suikastlarına kurban giden en ünlü Selçuklu veziri kimdir?', 'Nizamülmülk', 'Tacülmülk', 'Fahreddin Ali', 'Cacabey', 'Karatay', 'A', 'Büyük vezir Nizamülmülk Batıniler tarafından 1092 yılında şehit edilmiştir.');
    addQ(1, 2, 3, 'Semerkant ve Buhara gibi şehirlerin İslam dünyasında sırasıyla aldıkları unvanlar hangileridir?', 'Şehirlerin Şahı - Kubbetü\'l-İslam', 'Bağdat\'ın İncisi - Darü\'l-Mülk', 'Medinetü\'s-Selam - Şehirlerin Anası', 'Cennet Şehri - Belde-i Tayyibe', 'Darü\'l-Hilafet - Payitaht', 'A', 'Semerkant "Şehirlerin Şahı", Buhara ise Ahlat ve Belh ile birlikte "Kubbetü\'l-İslam" olarak anılmıştır.');
    addQ(1, 2, 3, 'Babür Devleti hükümdarı Şah Cihan tarafından eşi Mümtaz Mahal anısına Hindistan\'ın Agra kentinde yaptırılan şaheser hangisidir?', 'Tac Mahal', 'Moti Mescidi', 'Kızıl Kale', 'Hümayun Türbesi', 'Lahor Kalesi', 'A', 'Tac Mahal beyaz mermerden yapılmış dünyanın en görkemli anıt mezarlarından biridir.');
    addQ(1, 2, 3, 'İlk Türk denizcisi kabul edilen ve 1081 yılında İzmir merkezli ilk Türk beyliğini kuran komutan kimdir?', 'Çaka Bey', 'Umur Bey', 'Karesi Bey', 'Saruhan Bey', 'Aydınoğlu Mehmet Bey', 'A', 'Çaka Bey 1081\'de ilk donanmayı kurmuş ve Türk Deniz Kuvvetleri\'nin kuruluş yılı olmuştur.');
    addQ(1, 2, 3, 'Anadolu\'da kurulan ilk Türk beyliklerinden hangisi Divriği Ulu Camii ve Darüşşifası\'nı inşa etmiş ve UNESCO mirasına girmiştir?', 'Mengücekliler', 'Danişmentliler', 'Artuklular', 'Saltuklular', 'Çaka Beyliği', 'A', 'Sivas Divriği Ulu Camii Mengücekliler döneminde Ahmet Şah ve Melike Turan tarafından yaptırılmıştır.');
    addQ(1, 2, 3, 'Anadolu Selçuklu Devleti\'nin ilk başkenti neresiydi ve I. Haçlı Seferi sonucu başkent nereye taşınmıştır?', 'İznik - Konya', 'Konya - Sivas', 'Kayseri - İznik', 'Bursa - Edirne', 'İznik - Alanya', 'A', 'Kutalmışoğlu Süleyman Şah İznik\'i başkent yapmış, I. Haçlı Seferi\'nde İznik düşünce başkent Konya\'ya taşınmıştır.');
    addQ(1, 2, 3, '1176 Miryokefalon Savaşı\'nın Türk tarihindeki en temel önemi aşağıdakilerden hangisidir?', 'Anadolu\'nun kesin olarak Türk yurdu olduğunun tescillenmesi', 'Bizans İmparatorluğu\'nun yıkılması', 'İlk beyliklerin kurulması', 'Haçlı seferlerinin tamamen bitmesi', 'Kösedağ yenilgisinin yaşanması', 'A', 'Miryokefalon Zaferi ile Bizans savunmaya çekilmiş, Anadolu\'nun tapusu Türklerin eline geçmiştir.');

    // -------------------------------------------------------------------------
    // Subcat 3: Osmanlı Devleti Kuruluş & Yükselme
    // -------------------------------------------------------------------------
    // Level 1: Temel Olaylar
    addQ(1, 3, 1, 'Osmanlı Devleti ile Bizans arasında yapılan tarihteki ilk savaş hangisidir?', 'Koyunhisar (Bafeus) Savaşı', 'Maltepe Savaşı', 'Sırpsındığı Savaşı', 'I. Kosova Savaşı', 'Varna Savaşı', 'A', '1302 Koyunhisar Savaşı Osman Gazi döneminde Bizans tekfurlarına karşı kazanılmıştır.');
    addQ(1, 3, 1, 'Osmanlı Devleti\'nde Rumeli\'ye ilk geçiş hangi kalenin fethi ve Çimpe Kalesi\'nin üs olarak alınmasıyla gerçekleşmiştir?', 'Çimpe Kalesi', 'Gelibolu Kalesi', 'Kilitbahir', 'Rumeli Hisarı', 'Belgrad Kalesi', 'A', 'Orhan Bey döneminde Bizans\'a yardım karşılığı 1353\'te Çimpe Kalesi alınarak Rumeli\'ye adım atılmıştır.');
    addQ(1, 3, 1, 'Osmanlı Devleti\'nde Divan teşkilatı, vezirlik makamı ve ilk düzenli ordu (Yaya ve Müsellem) kimin döneminde kurulmuştur?', 'Orhan Bey', 'Osman Gazi', 'I. Murad', 'Yıldırım Bayezid', 'II. Mehmed', 'A', 'Orhan Bey beylikten devlete geçişi sağlayan tüm temel teşkilatlanmaları başlatmıştır.');
    addQ(1, 3, 1, 'Osmanlı Devleti\'nde padişah unvanını ve Sultan unvanını ilk kullanan hükümdarlar kimlerdir?', 'I. Murad - Orhan Bey', 'Osman Gazi - Orhan Bey', 'Yıldırım Bayezid - Çelebi Mehmed', 'Fatih - Yavuz', 'II. Murad - I. Murad', 'A', 'Orhan Bey Sultan unvanını sikkeye bastıran, I. Murad ise Padişah unvanını kullanan hükümdardır.');
    addQ(1, 3, 1, 'İstanbul\'u fethederek Orta Çağ\'ı kapatıp Yeni Çağ\'ı açan Osmanlı padişahı kimdir?', 'II. Mehmed (Fatih)', 'Yavuz Sultan Selim', 'Kanuni Sultan Süleyman', 'I. Murad', 'Yıldırım Bayezid', 'A', '29 Mayıs 1453\'te İstanbul\'u fetheden II. Mehmed "Fatih" unvanını almıştır.');
    addQ(1, 3, 1, 'Ankara Savaşı\'nda (1402) Timur\'a esir düşen ve Osmanlı\'nın Fetret Devri\'ne girmesine sebep olan padişah kimdir?', 'I. Bayezid (Yıldırım)', 'I. Murad', 'Çelebi Mehmed', 'II. Murad', 'Orhan Gazi', 'A', 'Yıldırım Bayezid Ankara Savaşı sonrası esir düşmüş ve 11 yıllık Fetret Devri başlamıştır.');
    addQ(1, 3, 1, 'Fetret Devri\'ne son vererek devleti yıkılmaktan kurtardığı için Osmanlı\'nın ikinci kurucusu sayılan padişah kimdir?', 'I. Mehmed (Çelebi)', 'II. Murad', 'Fatih Sultan Mehmed', 'II. Bayezid', 'Yavuz Sultan Selim', 'A', 'Çelebi Mehmed kardeşlerini saf dışı bırakarak birliği yeniden tesis etmiştir.');
    addQ(1, 3, 1, 'Yavuz Sultan Selim döneminde Memlük Devleti\'ne son verilerek Halifeliğin Osmanlı\'ya geçtiği savaşlar hangileridir?', 'Mercidabık ve Ridaniye Savaşları', 'Çaldıran ve Turnadağ', 'Otlukbeli ve Çaldıran', 'Mohaç ve Preveze', 'Varna ve II. Kosova', 'A', '1516 Mercidabık ve 1517 Ridaniye Savaşları ile Memlükler yıkılmış, halifelik Osmanlı\'ya geçmiştir.');
    addQ(1, 3, 1, 'Dünyanın en kısa süren meydan savaşı kabul edilen ve Macar Krallığı\'nı iki saatte yıkan zafer hangisidir?', 'Mohaç Meydan Muharebesi (1526)', 'Preveze Deniz Zaferi', 'Zigetvar Kuşatması', 'Çaldıran Savaşı', 'Kerne Muharebesi', 'A', 'Kanuni Sultan Süleyman 1526 Mohaç Zaferi ile Macaristan\'ı Osmanlı topraklarına katmıştır.');
    addQ(1, 3, 1, 'Akdeniz\'i Türk gölü haline getiren ve Haçlı donanmasını bozguna uğratan 1538 tarihli deniz zaferi hangisidir?', 'Preveze Deniz Zaferi', 'İnebahtı Savaşı', 'Cerbe Deniz Savaşı', 'Navarin Baskını', 'Çeşme Baskını', 'A', 'Barbaros Hayreddin Paşa komutasındaki Osmanlı donanması Andrea Doria komutasındaki Haçlıları Preveze\'de mağlup etmiştir.');

    // Level 2: Orta Düzey
    addQ(1, 3, 2, 'Osmanlı\'nın Balkanlar\'daki egemenliğini kesinleştiren ve Haçlıların Türkleri Balkanlar\'dan atma ümidini yok eden savaş hangisidir?', 'II. Kosova Savaşı (1448)', 'I. Kosova Savaşı', 'Varna Savaşı', 'Niğbolu Savaşı', 'Sırpsındığı Savaşı', 'A', 'II. Murad komutasındaki Osmanlı ordusu 1448 II. Kosova Zaferi ile Balkan hakimiyetini perçinlemiştir.');
    addQ(1, 3, 2, 'Yıldırım Bayezid\'e Haçlılara karşı kazandığı Niğbolu Zaferi (1396) sonrası Abbasi Halifesi tarafından hangi unvan verilmiştir?', 'Sultan-ı İklim-i Rum', 'Hadimü\'l-Haremeyn', 'Kayser-i Rum', 'Sahipkıran', 'Gazi-i Muazzam', 'A', 'Niğbolu Zaferi sonrası Abbasi Halifesi Yıldırım\'a "Sultan-ı İklim-i Rum" (Anadolu Diyarının Sultanı) unvanını vermiştir.');
    addQ(1, 3, 2, 'Anadolu Türk siyasi birliğini kesin olarak sağlayan, Turnadağ Savaşı (1515) ile Osmanlı\'ya bağlanan beylik hangisidir?', 'Dulkadiroğulları', 'Karamanoğulları', 'Candaroğulları', 'Germiyanoğulları', 'Hamitoğulları', 'A', 'Yavuz Sultan Selim Turnadağ Savaşı ile Dulkadiroğulları\'na son vererek Anadolu Türk birliğini kesinleştirmiştir.');
    addQ(1, 3, 2, 'Avusturya Arşidükünün protokolde Osmanlı sadrazamına denk sayıldığı 1533 tarihli antlaşma hangisidir?', 'İstanbul (İbrahim Paşa) Antlaşması', 'Zitvatorok Antlaşması', 'Vasvar Antlaşması', 'Karlofça Antlaşması', 'Pasarofça Antlaşması', 'A', '1533 İstanbul Antlaşması Osmanlı\'nın Avusturya üzerindeki siyasi üstünlüğünün zirvesidir.');
    addQ(1, 3, 2, 'Fatih Sultan Mehmed\'in deniz ticaretinde Venedik\'e karşı denge kurmak amacıyla ilk kez ticari ayrıcalık (kapitülasyon) verdiği devlet hangisidir?', 'Venedik', 'Fransa', 'İngiltere', 'Hollanda', 'Ceneviz', 'A', 'Fatih 1479\'da Venedik\'e ticari imtiyazlar ve İstanbul\'da Balyos (elçi) bulundurma hakkı vermiştir.');
    addQ(1, 3, 2, 'Kırım\'ın fethi (1475) ile Osmanlı Devleti hangi denizi tamamen bir Türk gölü haline getirmiştir?', 'Karadeniz', 'Akdeniz', 'Ege Denizi', 'Marmara Denizi', 'Kızıldeniz', 'A', 'Gedik Ahmet Paşa\'nın Kırım\'ı almasıyla Karadeniz Türk gölü haline gelmiştir.');
    addQ(1, 3, 2, 'Osmanlı Devleti\'nde Şehzadelerin sancaklara gönderilerek devlet tecrübesi kazanmasını zorunlu kılan ve kardeş katlini yasalaştıran kanunname hangisidir?', 'Kanunname-i Âli Osman', 'Ferman-ı Adalet', 'Tanzimat Fermanı', 'Sened-i İttifak', 'Mecelle', 'A', 'Fatih Sultan Mehmed Kanunname-i Âli Osman ile devlet teşkilatını ve veraset kurallarını kanunlaştırmıştır.');
    addQ(1, 3, 2, 'Osmanlı donanmasının tarihte ilk kez yakıldığı olay hangisidir?', 'İnebahtı Deniz Savaşı (1571)', 'Çeşme Baskını', 'Navarin Baskını', 'Sinop Baskını', 'Preveze', 'A', 'Kıbrıs\'ın fethi sonrası Haçlı donanması 1571 İnebahtı\'da Osmanlı donanmasını yakmıştır.');
    addQ(1, 3, 2, 'II. Bayezid döneminde yaşanan ve Osmanlı\'nın Batı seferlerinin duraksamasına, iç sorunun dış soruna dönüşmesine neden olan olay nedir?', 'Cem Sultan Olayı', 'Şahkulu İsyanı', 'Babazünnun İsyanı', 'Bozoklu Celal İsyanı', 'Kabakçı Mustafa İsyanı', 'A', 'Cem Sultan Rodos Şövalyelerine ve Papalığa sığınarak olayı uluslararası bir krize dönüştürmüştür.');
    addQ(1, 3, 2, 'Safevi Devleti (İran) ile Yavuz Sultan Selim arasında Şiilik propagandasını engellemek amacıyla yapılan 1514 tarihli savaş hangisidir?', 'Çaldıran Savaşı', 'Turnadağ Savaşı', 'Otlukbeli Savaşı', 'Ridaniye Savaşı', 'Kasr-ı Şirin', 'A', 'Yavuz 1514 Çaldıran Zaferi ile Şah İsmail\'i mağlup etmiş ve Doğu Anadolu güvenliğini sağlamıştır.');

    // Level 3: Zor & Detay
    addQ(1, 3, 3, 'Osmanlı\'nın 1533 İstanbul Antlaşması ile Avusturya\'ya kurduğu diplomatik üstünlüğü kaybettiği ve padişah ile kayserin denk sayıldığı 1606 tarihli antlaşma hangisidir?', 'Zitvatorok Antlaşması', 'Vasvar Antlaşması', 'Bucaş Antlaşması', 'Karlofça Antlaşması', 'Hotin Antlaşması', 'A', '1606 Zitvatorok Antlaşması ile Avusturya kralı Osmanlı padişahına denk sayılmış, protokol üstünlüğü bitmiştir.');
    addQ(1, 3, 3, 'Osmanlı Devleti\'nin Batı\'da en geniş sınırlara ulaştığı 1672 tarihli antlaşma hangisidir?', 'Bucaş Antlaşması', 'Karlofça Antlaşması', 'Zitvatorok Antlaşması', 'Hotin Antlaşması', 'Ferhat Paşa Antlaşması', 'A', 'Lehistan ile imzalanan Bucaş Antlaşması ile Podolya ve Kamaniçe alınmış, Batı\'da en geniş sınıra ulaşılmıştır.');
    addQ(1, 3, 3, 'Osmanlı Devleti\'nin Doğu\'da en geniş sınırlara ulaştığı (Azerbaycan, Gürcistan, Dağıstan) 1590 tarihli antlaşma hangisidir?', 'Ferhat Paşa Antlaşması', 'Kasr-ı Şirin Antlaşması', 'Nasuh Paşa Antlaşması', 'Serav Antlaşması', 'Amasya Antlaşması', 'A', 'III. Murad döneminde İran ile imzalanan Ferhat Paşa Antlaşması ile Doğu\'da en geniş sınıra ulaşılmıştır.');
    addQ(1, 3, 3, 'Günümüz Türkiye-İran sınırını büyük ölçüde belirleyen ve Zagros Dağları\'nı sınır kabul eden 1639 tarihli antlaşma hangisidir?', 'Kasr-ı Şirin Antlaşması', 'Ferhat Paşa Antlaşması', 'Nasuh Paşa Antlaşması', 'Ahmet Paşa Antlaşması', 'Kerden Antlaşması', 'A', 'IV. Murad\'ın Bağdat fethi sonrası imzalanan Kasr-ı Şirin Antlaşması bugünkü sınırın temelidir.');
    addQ(1, 3, 3, 'Osmanlı Devleti\'nin büyük çapta toprak kaybettiği ve Orta Avrupa egemenliğinin sona erdiği ilk antlaşma hangisidir?', 'Karlofça Antlaşması (1699)', 'Pasarofça Antlaşması', 'Küçük Kaynarca Antlaşması', 'Yaş Antlaşması', 'Belgrad Antlaşması', 'A', '1699 Karlofça Antlaşması ile Osmanlı ilk kez büyük çapta toprak kaybetmiş ve Gerileme Dönemi başlamıştır.');
    addQ(1, 3, 3, 'Osmanlı Devleti\'nde Şeyhülislam\'ın yetkilerini kısıtlayan ve ilk bütçeyi hazırlayan Tarhuncu Ahmet Paşa hangi dönem sadrazamıdır?', 'XVII. Yüzyıl (Duraklama)', 'Lale Devri', 'Tanzimat Dönemi', 'Yükselme Dönemi', 'II. Meşrutiyet', 'A', 'Tarhuncu Ahmet Paşa IV. Mehmed döneminde denk bütçe hazırlayan ilk devlet adamıdır.');
    addQ(1, 3, 3, 'Genç Osman\'ın (II. Osman) Hotin Seferi sırasında yeniçerilerin disiplinsizliğini görerek hangi kurumu kaldırmayı planlaması canına mal olmuştur?', 'Yeniçeri Ocağı', 'Sipahi Ocağı', 'Enderun', 'Divan-ı Hümayun', 'Kapıkulu Süvarileri', 'A', 'Genç Osman yeniçerileri kaldırmak istediği için yeniçeriler tarafından Yedikule zindanlarında katledilmiştir.');
    addQ(1, 3, 3, 'Osmanlı Devleti\'nin Lale Devri\'ne girmesine neden olan ve Batı\'nın üstünlüğünün kabul edildiği 1718 antlaşması hangisidir?', 'Pasarofça Antlaşması', 'Karlofça Antlaşması', 'Belgrad Antlaşması', 'Küçük Kaynarca Antlaşması', 'Prut Antlaşması', 'A', '1718 Pasarofça Antlaşması ile Osmanlı savunma politikasına geçmiş ve Lale Devri başlamıştır.');
    addQ(1, 3, 3, 'Kırım\'ın bağımsız olduğu ve Osmanlı\'nın ilk kez Müslüman bir toprağı kaybettiği 1774 tarihli antlaşma hangisidir?', 'Küçük Kaynarca Antlaşması', 'Yaş Antlaşması', 'Aynalıkavak Tenkihnamesi', 'Bükreş Antlaşması', 'Edirne Antlaşması', 'A', 'Küçük Kaynarca ile Kırım bağımsız olmuş, Karadeniz Türk gölü olmaktan çıkmış, Rusya\'ya kapitülasyon ve tazminat verilmiştir.');
    addQ(1, 3, 3, 'Kırım\'ın Rusya\'ya ait olduğunu Osmanlı\'nın resmen kabul ettiği ve Dağılma Dönemi\'nin başlangıcı sayılan 1792 antlaşması hangisidir?', 'Yaş Antlaşması', 'Küçük Kaynarca Antlaşması', 'Bükreş Antlaşması', 'Edirne Antlaşması', 'Hünkar İskelesi Antlaşması', 'A', '1792 Yaş Antlaşması ile Kırım kesin olarak Rus toprağı kabul edilmiştir.');

// KPSS Tarih Part 2 (Subcategories 4, 5, 6, 7 - 120 Questions)
// Category: 1 (Tarih)


    // -------------------------------------------------------------------------
    // Subcat 4: Osmanlı Kültür ve Medeniyeti
    // -------------------------------------------------------------------------
    // Level 1: Temel Teşkilat
    addQ(1, 4, 1, 'Osmanlı Devleti\'nde padişahtan sonra en yetkili kişi olan ve padişahın mührünü taşıyan devlet adamı kimdir?', 'Sadrazam (Veziriazam)', 'Şeyhülislam', 'Kazasker', 'Defterdar', 'Kaptanıderya', 'A', 'Sadrazam padişahın mutlak vekilidir ve serdar-ı ekrem sıfatıyla orduya komuta eder.');
    addQ(1, 4, 1, 'Osmanlı Devleti\'nde adalet, eğitim ve kadı-müderris tayinlerinden sorumlu Divan üyesi kimdir?', 'Kazasker (Kadıasker)', 'Nişancı', 'Defterdar', 'Reisülküttab', 'Şeyhülislam', 'A', 'Kazasker adalet ve eğitim işlerinden sorumlu olup İlmiye sınıfının en üst divan temsilcisidir.');
    addQ(1, 4, 1, 'Devletin gelir ve giderlerini hesaplayan, bütçeyi hazırlayan maliye sorumlusu Divan üyesi kimdir?', 'Defterdar', 'Nişancı', 'Sadrazam', 'Yeniçeri Ağası', 'Müneccimbaşı', 'A', 'Defterdar Kalemiye sınıfına mensup maliye başıdır.');
    addQ(1, 4, 1, 'Padişah fermanlarına tuğra çeken, fethedilen toprakları tahrir defterine kaydeden görevli kimdir?', 'Nişancı', 'Reisülküttab', 'Kazasker', 'Çavuşbaşı', 'Kapıcılar Koğuşu', 'A', 'Nişancı tahrir kayıtlarını tutar ve örfi hukukun uzmanıdır.');
    addQ(1, 4, 1, 'Osmanlı\'da gayrimüslim çocukların devşirilerek saray bürokrasisinde veya Yeniçeri Ocağı\'nda istihdam edildiği saray okulu hangisidir?', 'Enderun', 'Birun', 'Harem', 'Medrese', 'Darülfünun', 'A', 'Enderun sarayın iç bölümünde üst düzey yönetici yetiştiren mekteptir.');
    addQ(1, 4, 1, 'Tımar sistemi kapsamında dirlik sahiplerinin beslemekle yükümlü olduğu atlı askerlere ne ad verilirdi?', 'Cebelü', 'Yeniçeri', 'Levent', 'Akıncı', 'Humbaracı', 'A', 'Dirlik sahipleri gelirlerine göre Cebelü denilen zırhlı atlı asker beslemek zorundaydı.');
    addQ(1, 4, 1, 'Osmanlı\'da Şeyhülislam\'ın bir kararın İslam dinine uygun olup olmadığını belirten yazılı onayına ne denir?', 'Fetva', 'Ferman', 'Berat', 'Hatt-ı Hümayun', 'Adaletname', 'A', 'Şeyhülislam fetva makamıdır.');
    addQ(1, 4, 1, 'Osmanlı\'da esnaf ve zanaatkârların bir araya geldiği, kalite ve narh (fiyat) kontrolü yapan meslek teşkilatına ne denir?', 'Lonca Teşkilatı', 'İltizam', 'Ayanlık', 'Düyun-ı Umumiye', 'Reaya', 'A', 'Ahiliğin devamı niteliğindeki Loncalar esnaf dayanışmasını ve üretim kontrolünü sağlamıştır.');
    addQ(1, 4, 1, 'Yeniçeri askerlerinin üç ayda bir aldıkları maaşa ne ad verilirdi?', 'Ulufe', 'Cülus', 'Bahşiş', 'Dirlik', 'İkta', 'A', 'Ulufe üç ayda bir dağıtılan maaş, Cülus ise tahta geçişte ödenen bahşiştir.');
    addQ(1, 4, 1, 'Osmanlı Devleti\'nde halkın devlete ödediği ürün üzerinden alınan 1/10 oranındaki şeri vergiye ne denir?', 'Öşür (Aşar)', 'Haraç', 'Cizye', 'Avarız', 'Ağnam', 'A', 'Müslümanlardan öşür, gayrimüslimlerden haraç ve askerlik karşılığı cizye alınırdı.');

    // Level 2: Orta Düzey
    addQ(1, 4, 2, 'Osmanlı\'da bürokratik yönetici sınıflar kaça ayrılır ve Seyfiye sınıfının temsilcileri kimlerdir?', 'Seyfiye (Kılıç Ehli/Askeri-İdari) - Sadrazam, Vezirler, Beylerbeyi, Sancakbeyi', 'İlmiye', 'Kalemiye', 'Reaya', 'Lonca', 'A', 'Seyfiye yönetim ve ordu, İlmiye din-hukuk-eğitim, Kalemiye bürokrasi ve maliyedir.');
    addQ(1, 4, 2, 'Osmanlı\'da İlmiye sınıfının başında yer alan ve Divan üyesi olmayıp sadrazama denk protokol statüsünde olan dini lider kimdir?', 'Şeyhülislam (Müftü)', 'Kazasker', 'Nakibüleşraf', 'Müderris', 'Kadı', 'A', 'Şeyhülislam Kanuni döneminde protokolde sadrazama denk kabul edilmiştir.');
    addQ(1, 4, 2, 'Osmanlı\'da devlet arazilerinin (Miri arazi) gelirlerine göre ayrıldığı Has, Zeamet ve Tımar dirliklerinin sırasıyla yıllık gelir limitleri nelerdir?', 'Has: 100.000 akçeden fazla, Zeamet: 20.000-100.000 akçe, Tımar: 3.000-20.000 akçe', 'Tımar en yüksek, Has en düşük', 'Hepsi eşit', 'Has sadece padişaha', 'Dirlik parayla satılır', 'A', 'Dirlikler Has, Zeamet ve Tımar olarak hiyerarşik gelir dilimlerine ayrılmıştır.');
    addQ(1, 4, 2, 'Vergi toplama hakkının açık artırma usulüyle mültezimlere belirli bir süre için kiralanması sistemine ne ad verilir?', 'İltizam Sistemi', 'Malikane', 'Esham', 'Müsadere', 'Muaccele', 'A', 'İltizam peşin nakit para ihtiyacını karşılamak için eyalet vergi gelirlerinin ihale edilmesidir.');
    addQ(1, 4, 2, 'İltizam sisteminin ömür boyu verilmesi şekline dönüştürülmesi uygulamasına ne ad verilmiştir?', 'Malikane Sistemi', 'İkta', 'Tımar', 'Vakıf', 'Kapan', 'A', 'Malikane sistemi toprağı ömür boyu kiralayarak yerel ayanların güçlenmesine zemin hazırlamıştır.');
    addQ(1, 4, 2, 'Ölen veya haksız kazanç sağladığı iddia edilen devlet görevlilerinin mallarına devlet tarafından el konulması usulüne ne denir?', 'Müsadere Usulü', 'İltizam', 'Gedikoğlu', 'Narh', 'Avarız', 'A', 'Müsadere özel mülkiyeti kısıtlayan bir yöntem olup Tanzimat Fermanı ile resmen kaldırılmıştır.');
    addQ(1, 4, 2, 'Mimar Sinan\'ın çıraklık, kalfalık ve ustalık eserleri sırasıyla hangi yapılardır?', 'Şehzade Camii - Süleymaniye Camii - Selimiye Camii', 'Süleymaniye - Selimiye - Sultanahmet', 'Selimiye - Şehzade - Süleymaniye', 'Rüstem Paşa - Mihrimah Sultan - Selimiye', 'Beyazıt - Selimiye - Şehzade', 'A', 'Mimar Sinan: Çıraklık (Şehzadebaşı), Kalfalık (Süleymaniye), Ustalık (Edirne Selimiye).');
    addQ(1, 4, 2, 'Osmanlı Devleti\'nde dış işlerinden ve diplomasiden sorumlu makam haline gelen Nişancı yardımcılığı kökenli görevli kimdir?', 'Reisülküttab', 'Mektupçu', 'Amedi', 'Divan Katibi', 'Sadaret Kethüdası', 'A', 'XVII. yüzyıldan itibaren Reisülküttaplık Hariciye Nezareti\'ne (Dışişleri Bakanlığı) dönüşmüştür.');
    addQ(1, 4, 2, 'Olağanüstü hallerde (savaş, deprem, kıtlık) halktan toplanan ve zamanla sürekli hale gelen vergiye ne denir?', 'Avarız Vergisi', 'Öşür', 'Ağnam', 'Bacıbazar', 'Çiftbozan', 'A', 'Avarız vergisi ilk kez II. Bayezid döneminde Küçük Kıyamet olarak anılan depremde toplanmıştır.');
    addQ(1, 4, 2, 'Tarlasını sebepsiz yere 3 yıl üst üste boş bırakan köylüden alınan cezai vergiye ne ad verilir?', 'Çiftbozan Vergisi', 'Ağnam', 'İspenç', 'Derbent', 'İzn-i Sefine', 'A', 'Çiftbozan vergisi tarımsal üretimin sürekliliğini temin etmek amacıyla konulmuştur.');

    // Level 3: Zor & Detay
    addQ(1, 4, 3, 'Osmanlı klasik döneminde mahkemelerde kadının verdiği kararları kaydeden ve günümüzde önemli birincil kaynak olan defterlere ne denir?', 'Şeriye Sicilleri', 'Mühimme Defterleri', 'Tahrir Defterleri', 'Ahkam Defterleri', 'Bab-ı Asafi', 'A', 'Şeriye Sicilleri Osmanlı sosyal, hukuki ve iktisadi hayatının en temel belgeleridir.');
    addQ(1, 4, 3, 'Divan-ı Hümayun\'da alınan kararların kaydedildiği resmi defterlere ne ad verilir?', 'Mühimme Defterleri', 'Şeriye Sicilleri', 'Ruznamçe', 'Temettuat', 'Tahrir', 'A', 'Mühimme defterleri devletin en önemli siyasi ve idari kararlarının kronolojik kaydıdır.');
    addQ(1, 4, 3, 'Osmanlı\'da Seyit ve Şeriflerin (Peygamber soyundan gelenlerin) işleriyle ilgilenen görevliye ne ad verilirdi?', 'Nakibüleşraf', 'Kadıasker', 'Müderris', 'Muhtesip', 'Kethüda', 'A', 'Nakibüleşraf Peygamber soyunun kaydını tutan ve haklarını koruyan saygın bir makamdı.');
    addQ(1, 4, 3, 'Osmanlı\'da tek bir cins malın (örneğin un, ipek, yağ) toptan ticaretinin yapıldığı ve tartıldığı yerlere ne denirdi?', 'Kapan Hanı', 'Bedesten', 'Arasta', 'Kervansaray', 'Ribat', 'A', 'Tek tip ürünlerin satıldığı yerlere Kapan (Yağkapanı, Unkapanı) denirdi.');
    addQ(1, 4, 3, 'Kıymetli kumaş, mücevher ve silah gibi değerli malların alınıp satıldığı, güvenlikli kapalı çarşı bölümüne ne ad verilir?', 'Bedesten', 'Kapan', 'İmarethane', 'Külliye', 'Tabhane', 'A', 'Bedestenler Osmanlı ticaret merkezlerinin kalbini oluşturan kubbeli taş binalardır.');
    addQ(1, 4, 3, 'Osmanlı Devleti\'nde minyatür sanatçılarına "Nakkaş" denirdi. Lale Devri\'nin en ünlü minyatür ustası kimdir?', 'Levni', 'Nigari', 'Matrakçı Nasuh', 'Nakkaş Osman', 'Şeker Ahmet Paşa', 'A', 'Levni Surname-i Vehbi\'yi resimleyen Lale Devri\'nin baş nakkaşıdır.');
    addQ(1, 4, 3, 'İlk Türk matbaasını İbrahim Müteferrika ile birlikte 1727 yılında Lale Devri\'nde kuran Osmanlı aydını kimdir?', 'Sait Efendi', 'Yirmisekiz Mehmet Çelebi', 'Nevşehirli Damat İbrahim Paşa', 'Nedim', 'Katip Çelebi', 'A', 'Sait Efendi Paris elçisi Yirmisekiz Çelebi Mehmed\'in oğlu olup matbaayı Müteferrika ile kurmuştur.');
    addQ(1, 4, 3, 'Seyahatname adlı devasa 10 ciltlik eseriyle Osmanlı coğrafyasını ve kültürünü anlatan ünlü seyyah kimdir?', 'Evliya Çelebi', 'Katip Çelebi', 'Piri Reis', 'Seydi Ali Reis', 'Ali Kuşçu', 'A', 'Evliya Çelebi XVII. yüzyılın en büyük Türk seyyahıdır.');
    addQ(1, 4, 3, 'Kitab-ı Bahriye adlı eseri kaleme alan ve ilk dünya haritasını çizen ünlü Osmanlı denizcisi kimdir?', 'Piri Reis', 'Seydi Ali Reis', 'Barbaros Hayreddin', 'Turgut Reis', 'Oruç Reis', 'A', 'Piri Reis çizdiği harita ve Kitab-ı Bahriye ile dünya denizcilik tarihine geçmiştir.');
    addQ(1, 4, 3, 'Fatih döneminde Semerkant\'tan İstanbul\'a davet edilen, Ayasofya Medresesi başmüderrisi yapılan astronom ve matematikçi kimdir?', 'Ali Kuşçu', 'Kadızade-i Rumi', 'Takiyüddin Mehmet', 'Uluğ Bey', 'Molla Fenari', 'A', 'Ali Kuşçu Fatih tarafından el üstünde tutulan büyük astronomdur.');

    // -------------------------------------------------------------------------
    // Subcat 5: Kurtuluş Savaşı ve Cepheler
    // -------------------------------------------------------------------------
    // Level 1: Temel Olaylar
    addQ(1, 5, 1, 'Mustafa Kemal Paşa Milli Mücadele\'yi fiilen başlatmak üzere hangi tarihte Samsun\'a ayak basmıştır?', '19 Mayıs 1919', '23 Nisan 1920', '29 Ekim 1923', '30 Ağustos 1922', '10 Ağustos 1920', 'A', 'Mustafa Kemal 9. Ordu Müfettişi olarak Bandırma vapuruyla 19 Mayıs 1919\'da Samsun\'a çıkmıştır.');
    addQ(1, 5, 1, 'Milli Mücadele\'nin "amacı, gerekçesi ve yöntemi" ilk kez hangi belgede ilan edilmiştir?', 'Amasya Genelgesi', 'Havza Genelgesi', 'Erzurum Kongresi', 'Sivas Kongresi', 'Misak-ı Milli', 'A', 'Amasya Genelgesi (22 Haziran 1919) milletin bağımsızlığını yine milletin azim ve kararının kurtaracağını belirterek ihtilal beyannamesi olmuştur.');
    addQ(1, 5, 1, 'Toplanış amacı bakımından bölgesel, aldığı kararlar bakımından ulusal olan kongre hangisidir?', 'Erzurum Kongresi', 'Amasya Görüşmeleri', 'Sivas Kongresi', 'Balıkesir Kongresi', 'Alaşehir Kongresi', 'A', 'Erzurum Kongresi Doğu illeri için toplanmış ancak tüm yurdu kapsayan kararlar almıştır.');
    addQ(1, 5, 1, 'Temsil Heyeti\'nin tüm yurdu temsil ettiği ve tüm cemiyetlerin "Anadolu ve Rumeli Müdafaa-i Hukuk Cemiyeti" adı altında birleştirildiği kongre hangisidir?', 'Sivas Kongresi', 'Erzurum Kongresi', 'Amasya Kongresi', 'Pozantı Kongresi', 'Edirne Kongresi', 'A', 'Sivas Kongresi (Eylül 1919) tam yetkili milli kongredir, manda ve himaye kesin olarak reddedilmiştir.');
    addQ(1, 5, 1, 'Son Osmanlı Mebusan Meclisi\'nde kabul edilen ve milli sınırları belirleyen tarihi bildiri hangisidir?', 'Misak-ı Milli (Milli Ant)', 'Teşkilat-ı Esasiye', 'Amasya Protokolü', 'Bilecik Görüşmesi', 'Sevr Antlaşması', 'A', '28 Ocak 1920\'de kabul edilen Misak-ı Milli bağımsız Türkiye\'nin sınırlarını çizmiştir.');
    addQ(1, 5, 1, 'Türkiye Büyük Millet Meclisi (TBMM) hangi tarihte Ankara\'da resmen açılmıştır?', '23 Nisan 1920', '19 Mayıs 1919', '29 Ekim 1923', '1 Kasım 1922', '12 Ocak 1920', 'A', 'TBMM 23 Nisan 1920\'de Hacı Bayram Camii\'nde kılınan cuma namazı sonrası dualarla açılmıştır.');
    addQ(1, 5, 1, 'Düzenli ordunun Batı Cephesi\'nde kazandığı ilk askeri zafer hangisidir?', 'I. İnönü Zaferi', 'II. İnönü Zaferi', 'Sakarya Meydan Muharebesi', 'Büyük Taarruz', 'Aslıhanlar Muharebesi', 'A', 'İsmet Paşa komutasındaki düzenli ordu Ocak 1921\'de Yunan ordusunu I. İnönü\'de durdurmuştur.');
    addQ(1, 5, 1, 'Doğu Cephesi komutanı Kazım Karabekir Paşa Ermenileri mağlup ederek TBMM\'nin ilk askeri ve siyasi başarısı olan hangi antlaşmayı imzalamıştır?', 'Gümrü Antlaşması (1920)', 'Moskova Antlaşması', 'Kars Antlaşması', 'Ankara Antlaşması', 'Mudanya Mütarekesi', 'A', 'Aralık 1920 Gümrü Antlaşması ile Sevr\'i reddeden ilk devlet Ermenistan olmuş ve Doğu Cephesi kapanmıştır.');
    addQ(1, 5, 1, 'Mustafa Kemal Paşa\'ya "Mareşallik" rütbesi ve "Gazilik" unvanı hangi zaferden sonra verilmiştir?', 'Sakarya Meydan Muharebesi', 'Büyük Taarruz', 'I. İnönü', 'Çanakkale Savaşı', 'Trablusgarp Savaşı', 'A', '22 gün 22 gece süren Sakarya Zaferi (1921) sonrası TBMM Mustafa Kemal\'e Gazi ve Mareşal unvanı vermiştir.');
    addQ(1, 5, 1, 'Kurtuluş Savaşı\'nın askeri safhasını sona erdiren ve İstanbul, Boğazlar ile Doğu Trakya\'nın savaşsız kurtarılmasını sağlayan ateşkes hangisidir?', 'Mudanya Ateşkes Antlaşması', 'Mondros Ateşkes Antlaşması', 'Lozan Barış Antlaşması', 'Sevr Antlaşması', 'Brest-Litovsk', 'A', '11 Ekim 1922 Mudanya Mütarekesi ile İsmet İnönü diplomatik zafer kazanmıştır.');

    // Level 2: Orta Düzey
    addQ(1, 5, 2, 'I. İnönü Zaferi\'nin içerideki ve dışarıdaki sonuçları arasında aşağıdakilerden hangisi yer almaz?', 'Fransa ile Ankara Antlaşması imzalanması', 'Sovyet Rusya ile Moskova Antlaşması imzalanması', 'Afganistan ile Dostluk Antlaşması yapılması', 'İstiklal Marşı\'nın kabul edilmesi', 'Teşkilat-ı Esasiye Kanunu\'nun (1921 Anayasası) kabulü', 'A', 'Fransa ile Ankara Antlaşması Sakarya Zaferi\'nden sonra imzalanmıştır.');
    addQ(1, 5, 2, 'İstiklal Marşı hangi yarışma ile seçilmiş, güftesi kime aittir ve ilk olarak hangi gazetede yayımlanmıştır?', 'Mehmet Akif Ersoy - Açıksöz Gazetesi', 'Ziya Gökalp - İrade-i Milliye', 'Tevfik Fikret - Hakimiyet-i Milliye', 'Yahya Kemal - Tasvir-i Efkar', 'Namık Kemal - Tercüman-ı Ahval', 'A', 'Mehmet Akif\'in yazdığı marş Maarif Vekaleti yarışmasıyla seçilmiş ve 12 Mart 1921\'de kabul edilmiştir.');
    addQ(1, 5, 2, 'TBMM\'yi tanıyan ilk Müslüman devlet aşağıdakilerden hangisidir?', 'Afganistan', 'İran', 'Pakistan', 'Mısır', 'Azerbaycan', 'A', '1 Mart 1921\'de imzalanan Türk-Afgan Dostluk Antlaşması ile Afganistan TBMM\'yi tanıyan ilk Müslüman devlettir.');
    addQ(1, 5, 2, 'TBMM\'yi tanıyan ilk büyük Avrupa devleti ve Misak-ı Milli\'yi tanıyan ilk süper güç hangisidir?', 'Sovyet Rusya', 'Fransa', 'İtalya', 'İngiltere', 'Almanya', 'A', '16 Mart 1921 Moskova Antlaşması ile Sovyet Rusya TBMM\'yi tanıyan ilk Avrupalı güç olmuştur.');
    addQ(1, 5, 2, 'Moskova Antlaşması ile Türkiye\'nin Misak-ı Milli sınırlarından verdiği "ilk taviz" neresidir?', 'Batum', 'Hatay', 'Musul', 'Boğazlar', 'Kıbrıs', 'A', 'Moskova Antlaşması\'nda Batum Gürcistan\'a (Sovyet idaresine) bırakılarak ilk taviz verilmiştir.');
    addQ(1, 5, 2, 'Kütahya-Eskişehir Muharebeleri devam ederken Mustafa Kemal Paşa\'nın Ankara\'da topladığı eğitim kongresi hangisidir?', 'I. Maarif Kongresi', 'İzmir İktisat Kongresi', 'Sanayi Kongresi', 'Tıp Kongresi', 'Tarih Kurultayı', 'A', 'Mustafa Kemal top sesleri Ankara\'dan duyulurken Maarif Kongresi\'ni toplayarak eğitime verdiği önemi göstermiştir.');
    addQ(1, 5, 2, 'Kütahya-Eskişehir yenilgisi sonrası meclisin tüm yetkilerini 3 aylığına Mustafa Kemal\'e devrettiği kanun hangisidir?', 'Başkomutanlık Kanunu', 'Hıyanet-i Vataniye Kanunu', 'Firariler Kanunu', 'Teşkilat-ı Esasiye', 'Tekalif-i Milliye', 'A', '5 Ağustos 1921 Başkomutanlık Kanunu ile yasama, yürütme ve ordu komutanlığı Mustafa Kemal\'e geçmiştir.');
    addQ(1, 5, 2, 'Ordunun acil ihtiyaçlarını halktan karşılamak amacıyla Başkomutan Mustafa Kemal\'in yayımladığı emirler hangisidir?', 'Tekalif-i Milliye Emirleri', 'Tamim-i Amasya', 'Nutuk', 'Misak-ı Maarif', 'Kanunname', 'A', '7-8 Ağustos 1921\'de yayımlanan Tekalif-i Milliye Emirleri Sakarya Savaşı öncesi topyekûn seferberliktir.');
    addQ(1, 5, 2, 'Fransa\'nın TBMM\'yi tanıdığı, Güney Cephesi\'ni kapatan ve Hatay hariç güney sınırımızı çizen 1921 antlaşması hangisidir?', 'Ankara Antlaşması', 'Mudanya Mütarekesi', 'Gümrü Antlaşması', 'Moskova Antlaşması', 'Kars Antlaşması', 'A', 'Sakarya Zaferi sonrası Fransa ile imzalanan Ankara Antlaşması ile TBMM\'yi tanıyan ilk İtilaf devleti Fransa olmuştur.');
    addQ(1, 5, 2, 'Doğu sınırımızın (Kars, Ardahan, Artvin) kesinleşmesini sağlayan ve Sovyet Kafkas Cumhuriyetleri ile yapılan antlaşma hangisidir?', 'Kars Antlaşması (1921)', 'Gümrü Antlaşması', 'Moskova Antlaşması', 'Brest-Litovsk', 'Batum Antlaşması', 'A', 'Sakarya Zaferi\'nin ardından Ekim 1921\'de imzalanan Kars Antlaşması doğu sınırımıza son şeklini vermiştir.');

    // Level 3: Zor & Detay
    addQ(1, 5, 3, 'Gediz Taarruzu\'nda Kuva-yı Milliye\'nin başarısız olması üzerine düzenli ordunun kurulmasını hızlandıran Batı Cephesi komutanı kimdi?', 'Ali Fuat Cebesoy', 'Refet Bele', 'Fevzi Çakmak', 'Kazım Karabekir', 'Rauf Orbay', 'A', 'Gediz yenilgisi sonrası Ali Fuat Paşa Moskova elçiliğine atanmış, ordu İsmet ve Refet beyler arasında ikiye ayrılmıştır.');
    addQ(1, 5, 3, 'Mustafa Kemal\'in "Hattı müdafaa yoktur, sathı müdafaa vardır. O satıh bütün vatandır." tarihi emrini verdiği savaş hangisidir?', 'Sakarya Meydan Muharebesi', 'Dumlupınar (Büyük Taarruz)', 'I. İnönü Savaşı', 'Çanakkale Savaşı', 'Trablusgarp Savaşı', 'A', 'Sakarya Meydan Muharebesi stratejik geri çekilmeyi ve vatan sathının topyekûn savunulmasını simgeler.');
    addQ(1, 5, 3, 'Lozan Barış Konferansı\'na TBMM adına başdelege olarak katılan ve heyet başkanlığı yapan devlet adamı kimdir?', 'İsmet İnönü', 'Rauf Orbay', 'Yusuf Kemal Tengirşek', 'Fethi Okyar', 'Hasan Saka', 'A', 'Mudanya\'daki diplomatik başarısı nedeniyle İsmet Paşa Dışişleri Bakanı yapılarak Lozan\'a başdelege gönderilmiştir.');
    addQ(1, 5, 3, 'Lozan Barış Antlaşması\'nda Türkiye lehine çözümlenemeyen ve sonraya bırakılan tek sınır meselesi hangisidir?', 'Irak Sınırı (Musul Sorunu)', 'Suriye Sınırı', 'Yunanistan Sınırı', 'Boğazlar', 'Kapitülasyonlar', 'A', 'Musul meselesi İngiltere ile ikili görüşmelere bırakılmış ve 1926 Ankara Antlaşması ile çözülmüştür.');
    addQ(1, 5, 3, 'Lozan\'da çözülen Boğazlar statüsü 1936 yılına kadar nasıl düzenlenmiştir?', 'Başkanı Türk olan uluslararası bir komisyonun yönetimine bırakılmış ve askersizleştirilmiştir', 'Tamamen Türkiye\'ye bırakılmıştır', 'İngiltere\'ye verilmiştir', 'Rusya\'ya devredilmiştir', 'Hiç görüşülmemiştir', 'A', 'Boğazlar Komisyonu varlığı egemenliğimizi sınırlamış, bu kısıtlama 1936 Montrö Boğazlar Sözleşmesi ile kaldırılmıştır.');
    addQ(1, 5, 3, 'Lozan Antlaşması\'nda savaş tazminatı olarak Yunanistan\'dan alınan yerleşim yeri hangisidir?', 'Karaağaç ve Bosnaköy', 'Selanik', 'Gümülcine', 'Dedeağaç', 'Girit', 'A', 'Karaağaç ve Bosna kasabaları Yunanistan tarafından savaş tazminatı olarak Türkiye\'ye verilmiştir.');
    addQ(1, 5, 3, 'Lozan Konferansı sırasında meclis ile hükümet arasında yaşanan tartışmalar nedeniyle I. TBMM ne kararı almıştır?', 'Seçimlerin yenilenmesi kararı (II. TBMM dönemi)', 'Cumhuriyetin ilanı', 'Halifeliğin kaldırılması', 'Tekke ve zaviyelerin kapatılması', 'Parti kapatma', 'A', 'Nisan 1923\'te seçim kararı alınmış, Lozan Antlaşması Ağustos 1923\'te II. TBMM tarafından onaylanmıştır.');
    addQ(1, 5, 3, 'Milli Mücadele döneminde çıkarılan ve TBMM\'ye karşı çıkan isyanları bastırmak amacıyla kurulan olağanüstü mahkemeler hangisidir?', 'İstiklal Mahkemeleri', 'Divan-ı Harp', 'Yüce Divan', 'Nizamiye Mahkemeleri', 'Şeriye Mahkemeleri', 'A', 'İstiklal Mahkemeleri üyeleri milletvekillerinden oluşan devrim mahkemeleridir.');
    addQ(1, 5, 3, 'Mustafa Kemal\'in "Geldikleri gibi giderler!" sözünü söylediği tarihsel an hangisidir?', '13 Kasım 1918\'de İtilaf donanmasının İstanbul Boğazı\'na demirlemesi', 'Çanakkale Boğazı geçilirken', 'Samsun\'a çıkarken', 'Mondros imzalanırken', 'Sevr imzalanırken', 'A', 'Haydarpaşa Garı\'ndan bindiği Kartal istimbotunda işgal donanmasını görünce yaveri Cevat Abbas\'a bu sözü söylemiştir.');
    addQ(1, 5, 3, 'Güney Cephesi\'nde halkın gösterdiği kahramanlıklar sonucu TBMM tarafından sırasıyla Antep, Maraş ve Urfa\'ya hangi unvanlar verilmiştir?', 'Gazi (1921) - Kahraman (1973) - Şanlı (1984)', 'Şanlı - Kahraman - Gazi', 'Kahraman - Gazi - Şanlı', 'Gazi - Şanlı - Kahraman', 'Şehit - Gazi - Kahraman', 'A', 'Antep 1921\'de Gazi, Maraş 1973\'te Kahraman, Urfa 1984\'te Şanlı unvanını almıştır.');

    // -------------------------------------------------------------------------
    // Subcat 6: Atatürk İlkeleri ve İnkılap Tarihi
    // -------------------------------------------------------------------------
    // Level 1: Temel İnkılaplar
    addQ(1, 6, 1, 'Cumhuriyet hangi tarihte ilan edilmiş ve Türkiye Cumhuriyeti\'nin ilk Cumhurbaşkanı kim seçilmiştir?', '29 Ekim 1923 - Mustafa Kemal Atatürk', '23 Nisan 1920 - İsmet İnönü', '1 Kasım 1922 - Fevzi Çakmak', '3 Mart 1924 - Kazım Karabekir', '30 Ağustos 1922 - Celal Bayar', 'A', '29 Ekim 1923\'te Cumhuriyet ilan edilmiş, Mustafa Kemal ilk Cumhurbaşkanı, İsmet İnönü ilk Başbakan olmuştur.');
    addQ(1, 6, 1, 'Lozan Konferansı\'na ikilik yaratılmasını engellemek amacıyla 1 Kasım 1922\'de kaldırılan kurum hangisidir?', 'Saltanat', 'Halifelik', 'Şeriye Vekaleti', 'Enderun', 'Medreseler', 'A', '1 Kasım 1922\'de Saltanat ile Hilafet ayrılmış ve saltanat kaldırılarak Osmanlı resmen sona ermiştir.');
    addQ(1, 6, 1, 'Eğitimde birliği sağlamak amacıyla 3 Mart 1924\'te kabul edilen kanun hangisidir?', 'Tevhid-i Tedrisat Kanunu', 'Maarif Teşkilatı Kanunu', 'Harf İnkılabı Kanunu', 'Medreselerin Islahı Kanunu', 'Köy Enstitüleri Kanunu', 'A', 'Tevhid-i Tedrisat ile tüm eğitim kurumları Maarif Vekaleti\'ne (MEB) bağlanmış, medreseler kapatılmıştır.');
    addQ(1, 6, 1, '3 Mart 1924 tarihinde kabul edilen kanunlarla aşağıdakilerden hangisi gerçekleşmemiştir?', 'Cumhuriyetin ilanı', 'Halifeliğin kaldırılması', 'Tevhid-i Tedrisat Kanunu', 'Şeriye ve Evkaf Vekaleti\'nin kaldırılması', 'Erkan-ı Harbiye Vekaleti\'nin kaldırılması', 'A', 'Cumhuriyet 29 Ekim 1923\'te ilan edilmişti, 3 Mart 1924 devrim gününde ise halifelik ve eski vekaletler kaldırılmıştır.');
    addQ(1, 6, 1, 'Türkiye\'de kadınlara seçme ve seçilme haklarının tanınması sürecinin kronolojik sırası (BMW) nasıldır?', 'Belediye (1930) - Muhtarlık (1933) - Vekillik (1934)', 'Muhtarlık - Belediye - Vekillik', 'Vekillik - Belediye - Muhtarlık', 'Belediye - Vekillik - Muhtarlık', 'Hepsi 1926 Medeni Kanun\'la verildi', 'A', 'Kadınlara siyasi haklar BMW şifresiyle: Belediye (1930), Muhtar (1933), Milletvekili (1934). Medeni Kanun\'da siyasi hak YOKTUR.');
    addQ(1, 6, 1, 'Yeni Türk Harflerinin (Latin esaslı Türk alfabesi) kabul edildiği tarih hangisidir?', '1 Kasım 1928', '29 Ekim 1923', '3 Mart 1924', '17 Şubat 1926', '5 Aralık 1934', 'A', '1 Kasım 1928\'de yeni harfler kabul edilmiş, okuma yazma seferberliği için Millet Mektepleri açılmıştır.');
    addQ(1, 6, 1, 'Mustafa Kemal Atatürk\'e "Başöğretmen" unvanı hangi kurumun açılışı ve ne zaman verilmiştir?', '24 Kasım 1928 - Millet Mektepleri', '23 Nisan 1920 - TBMM', '29 Ekim 1923 - Cumhuriyet', '1 Kasım 1928 - Harf Devrimi', '19 Mayıs 1919 - Samsun', 'A', 'Millet Mektepleri\'nin talimatnamesiyle 24 Kasım 1928\'de Atatürk\'e Başöğretmenlik unvanı verilmiştir. Bugün Öğretmenler Günü\'dür.');
    addQ(1, 6, 1, 'İsviçre Medeni Kanunu örnek alınarak hazırlanan ve kadın-erkek eşitliğini sağlayan Türk Medeni Kanunu hangi yılda kabul edilmiştir?', '17 Şubat 1926', '1923', '1924', '1928', '1934', 'A', '17 Şubat 1926\'da kabul edilen Medeni Kanun ile tek eşlilik, resmi nikah, mirasta ve şahitlikte eşitlik getirilmiştir.');
    addQ(1, 6, 1, 'Ekonomik bağımsızlığı hedefleyen ve "Milli ekonomi ilkeleri"ni belirleyen I. İzmir İktisat Kongresi\'nin başkanı kimdir?', 'Kazım Karabekir', 'İsmet İnönü', 'Celal Bayar', 'Mustafa Kemal', 'Fevzi Çakmak', 'A', '17 Şubat 1923\'te toplanan İzmir İktisat Kongresi\'nin başkanlığını Kazım Karabekir yapmıştır.');
    addQ(1, 6, 1, 'Atatürk ilkelerinden hangisi sınıf mücadelesini reddeder, toplumda eşitliği, adaleti ve ayrıcalıksız bir sosyal yapıyı savunur?', 'Halkçılık', 'Devletçilik', 'Cumhuriyetçilik', 'Laiklik', 'İnkılapçılık', 'A', 'Halkçılık kanun önünde eşitlik, dayanışma ve imtiyazsız sınıfsız toplum anlayışıdır.');

    // Level 2: Orta Düzey
    addQ(1, 6, 2, 'Cumhuriyet döneminde kurulan ilk muhalefet partisi aşağıdakilerden hangisidir?', 'Terakkiperver Cumhuriyet Fırkası (1924)', 'Serbest Cumhuriyet Fırkası', 'Demokrat Parti', 'Milli Kalkınma Partisi', 'Ahali Fırkası', 'A', 'Kazım Karabekir, Rauf Orbay, Ali Fuat Cebesoy, Adnan Adıvar ve Refet Bele tarafından kurulmuştur.');
    addQ(1, 6, 2, 'Terakkiperver Cumhuriyet Fırkası\'nın kapatılmasına ve Takrir-i Sükun Kanunu\'nun çıkarılmasına neden olan isyan hangisidir?', 'Şeyh Sait İsyanı (1925)', 'Menemen Olayı', 'Bursa Olayı', 'Razgrad Olayı', 'Vagon-Li Olayı', 'A', 'Şubat 1925\'te çıkan rejim karşıtı Şeyh Sait İsyanı sonrası Takrir-i Sükun Kanunu çıkarılmış ve TCF kapatılmıştır.');
    addQ(1, 6, 2, 'Menemen Olayı (Kubilay Olayı - 1930) hangi muhalefet partisinin kendisini feshetmesinden kısa süre sonra gerçekleşmiştir?', 'Serbest Cumhuriyet Fırkası', 'Terakkiperver Cumhuriyet Fırkası', 'Halk Fırkası', 'Millet Partisi', 'Osmanlı Ahrar Fırkası', 'A', 'Ali Fethi Okyar partisini kapattıktan kısa bir süre sonra Derviş Mehmet ve yandaşları Menemen\'de asteğmen Kubilay\'ı şehit etmiştir.');
    addQ(1, 6, 2, 'Cumhuriyet döneminde açılan ilk özel banka ve ilk kamu yatırım bankası sırasıyla hangileridir?', 'İş Bankası (1924) - Sümerbank (1933)', 'Ziraat Bankası - Halkbank', 'Osmanlı Bankası - Etibank', 'Merkez Bankası - Vakıfbank', 'İller Bankası - Denizbank', 'A', '1924\'te Celal Bayar genel müdürlüğünde İş Bankası, 1933\'te I. Beş Yıllık Sanayi Planı için Sümerbank kurulmuştur.');
    addQ(1, 6, 2, '1929 Dünya Ekonomik Buhranı (Büyük Buhran) sonrasında Türkiye\'de zorunlu olarak benimsenen ve uygulanan Atatürk ilkesi hangisidir?', 'Devletçilik', 'Milliyetçilik', 'Laiklik', 'Cumhuriyetçilik', 'İnkılapçılık', 'A', 'Özel sektörün yetersiz sermayesi ve dünya krizi nedeniyle sanayi yatırımlarını devlet üstlenmiş (Devletçilik).');
    addQ(1, 6, 2, 'Türk karasularında deniz ticareti ve liman işletme hakkını millileştiren ve yabancı tekelini kıran 1 Temmuz 1926 tarihli kanun hangisidir?', 'Kabotaj Kanunu', 'Teşvik-i Sanayi Kanunu', 'Gümrük Kanunu', 'Ticaret Kanunu', 'Denizcilik Nizamnamesi', 'A', 'Kabotaj Kanunu ile Türk denizleri millileştirilmiş ve Milliyetçilik ilkesi doğrultusunda bayram ilan edilmiştir.');
    addQ(1, 6, 2, '1928 yılında anayasada yapılan değişiklikle hangi ifade anayasa metninden çıkarılmıştır?', '"Devletin dini İslam\'dır" maddesi', '"Başkent Ankara\'dır"', '"Resmi dil Türkçe\'dir"', '"Egemenlik kayıtsız şartsız milletindir"', '"Cumhurbaşkanı 4 yıllığına seçilir"', 'A', '1928 değişikliği ile "Devletin dini İslam\'dır" ibaresi çıkarılarak anayasa laikleşme yolunda dev adım atmıştır.');
    addQ(1, 6, 2, 'Atatürk ilkeleri hangi yılda Türkiye Cumhuriyeti Anayasası\'na (1924 Anayasası) resmen girmiştir?', '1937', '1924', '1928', '1934', '1946', 'A', '5 Şubat 1937 anayasa değişikliği ile 6 Atatürk ilkesi anayasanın 2. maddesine dahil edilmiştir.');
    addQ(1, 6, 2, 'Milli kültür ve tarih bilincini geliştirmek amacıyla kurulan Türk Tarih Kurumu (1931) ve Türk Dil Kurumu (1932) hangi ilkeyle doğrudan ilişkilidir?', 'Milliyetçilik', 'Devletçilik', 'Laiklik', 'Halkçılık', 'İnkılapçılık', 'A', 'Türk kimliği, dili ve tarihini araştıran kurumlar Milliyetçilik ilkesinin doğrudan ürünüdür.');
    addQ(1, 6, 2, '1934 yılında çıkarılan Soyadı Kanunu ile Mustafa Kemal\'e "Atatürk" soyadını kim vermiştir?', 'Türkiye Büyük Millet Meclisi (Kanunla)', 'İsmet İnönü', 'Türk Dil Kurumu', 'Celal Bayar', 'Halk oylamasıyla', 'A', '24 Kasım 1934\'te TBMM çıkardığı özel bir kanunla Mustafa Kemal\'e "Atatürk" soyadını vermiştir.');

    // Level 3: Zor & Detay
    addQ(1, 6, 3, 'Darülfünun\'un kapatılarak yerine modern İstanbul Üniversitesi\'nin kurulmasını (1933) sağlayan İsviçreli profesörün hazırladığı rapor kime aittir?', 'Prof. Albert Malche', 'John Dewey', 'Alexander Rüstow', 'Ernst Reuter', 'Paul Hindemith', 'A', 'Albert Malche Raporu doğrultusunda 1933 Üniversite Reformu yapılmış ve İstanbul Üniversitesi açılmıştır.');
    addQ(1, 6, 3, 'Mustafa Kemal Atatürk\'ün naşının 1938-1953 yılları arasında geçici olarak muhafaza edildiği mekan neresidir?', 'Ankara Etnografya Müzesi', 'TBMM Bahçesi', 'Dolmabahçe Sarayı', 'Çankaya Köşkü', 'Gülhane Parkı', 'A', 'Atatürk\'ün naşı 1953\'te Anıtkabir tamamlanana kadar Ankara Etnografya Müzesi\'nde korunmuştur.');
    addQ(1, 6, 3, 'Anıtkabir\'in mimarları aşağıdakilerden hangisidir?', 'Emin Onat ve Orhan Arda', 'Mimar Vedat Tek ve Kemalettin Bey', 'Sedat Hakkı Eldem', 'Bruno Taut', 'Clemens Holzmeister', 'A', 'Açılan uluslararası yarışmayı kazanan Prof. Emin Onat ve Doç. Orhan Arda Anıtkabir\'i projelendirmiştir.');
    addQ(1, 6, 3, 'Mustafa Kemal\'in bizzat kaleme aldığı, 1919-1927 yıllarını kapsayan ve CHP\'nin II. Kurultayı\'nda 6 günde okuduğu eseri hangisidir?', 'Nutuk (Söylev)', 'Vatandaş İçin Medeni Bilgiler', 'Geometri Kılavuzu', 'Zabit ve Kumandan ile Hasbihal', 'Anafartalar Hatıraları', 'A', 'Nutuk "1919 senesi Mayısının 19. günü Samsun\'a çıktım" cümlesiyle başlar ve Gençliğe Hitabe ile biter.');
    addQ(1, 6, 3, 'Atatürk döneminin son Başbakanı ve son Meclis Başkanı sırasıyla kimlerdir?', 'Celal Bayar - Abdülhalik Renda', 'İsmet İnönü - Kazım Özalp', 'Fethi Okyar - Refik Saydam', 'Şükrü Saracoğlu - Hasan Saka', 'Adnan Menderes - Fuat Köprülü', 'A', 'Atatürk vefat ettiğinde Başbakan Celal Bayar, Meclis Başkanı ise Abdülhalik Renda idi.');
    addQ(1, 6, 3, '1934 yılında Bozkurt-Lotus davası olarak bilinen davada Türkiye\'yi Lahey Adalet Divanı\'nda başarıyla savunan Adalet Bakanı kimdir?', 'Mahmut Esat Bozkurt', 'Şükrü Saraçoğlu', 'Tevfik Rüştü Aras', 'Cemil Sait Barlas', 'Yusuf Kemal Tengirşek', 'A', 'Mahmut Esat Bey Lahey\'de davayı kazanmış ve Atatürk tarafından kendisine "Bozkurt" soyadı verilmiştir.');
    addQ(1, 6, 3, '1932 yılında Türkiye\'nin Milletler Cemiyeti\'ne (Cemiyet-i Akvam) katılması hangi devletlerin davetiyle gerçekleşmiştir?', 'İspanya\'nın teklifi ve Yunanistan\'ın desteğiyle', 'İngiltere ve Fransa', 'Sovyetler Birliği ve Almanya', 'ABD ve İtalya', 'İran ve Afganistan', 'A', 'Türkiye başvurarak değil, İspanya ve Yunanistan\'ın davetiyle Milletler Cemiyeti\'ne üye olmuştur.');
    addQ(1, 6, 3, '1936 Montrö Boğazlar Sözleşmesi\'ni Türkiye adına imzalayan dönemin Dışişleri Bakanı kimdir?', 'Tevfik Rüştü Aras', 'İsmet İnönü', 'Fethi Okyar', 'Şükrü Saracoğlu', 'Numan Menemencioğlu', 'A', 'Atatürk döneminin en uzun süre görev yapan Dışişleri Bakanı Tevfik Rüştü Aras\'tır.');
    addQ(1, 6, 3, 'Mustafa Kemal\'in "Kırk asırlık Türk yurdu düşman elinde esir kalamaz" ve "Şahsi meselem" dediği dış politika konusu hangisidir?', 'Hatay Sorunu', 'Musul Sorunu', 'Boğazlar Meselesi', 'Ege Adaları', 'Kıbrıs Meselesi', 'A', 'Atatürk Hatay için sağlığını hiçe sayarak Adana ve Mersin gezilerine çıkmış, Hatay 1939\'da anavatana katılmıştır.');
    addQ(1, 6, 3, 'Hatay Cumhuriyeti\'nin ilk ve tek Cumhurbaşkanı ile Başbakanı kimlerdir?', 'Cumhurbaşkanı Tayfur Sökmen - Başbakan Abdurrahman Melek', 'İsmet İnönü - Celal Bayar', 'Kazım Karabekir - Rauf Orbay', 'Fevzi Çakmak - Refik Saydam', 'Ali Fuat Cebesoy - Refet Bele', 'A', '1938\'de kurulan bağımsız Hatay Devleti\'nin Cumhurbaşkanı Tayfur Sökmen, Başbakanı Abdurrahman Melek\'tir.');

    // -------------------------------------------------------------------------
    // Subcat 7: Çağdaş Türk ve Dünya Tarihi
    // -------------------------------------------------------------------------
    // Level 1: Temel Bilgiler
    addQ(1, 7, 1, 'Türkiye\'nin İtalya ve Almanya tehdidine karşı Balkan sınırlarını güvence altına almak için 1934\'te imzaladığı pakt hangisidir?', 'Balkan Antantı', 'Sadabat Paktı', 'Bağdat Paktı', 'Varşova Paktı', 'NATO', 'A', 'Türkiye, Yunanistan, Yugoslavya ve Romanya arasında Balkan Antantı imzalanmıştır.');
    addQ(1, 7, 1, 'İtalya\'nın Habeşistan\'a saldırması üzerine Türkiye, İran, Irak ve Afganistan arasında Doğu sınırını korumak için 1937\'de kurulan pakt hangisidir?', 'Sadabat Paktı', 'Balkan Antantı', 'CENTO', 'SEATO', 'Briand-Kellogg', 'A', 'Tahran\'da Sadabat Sarayı\'nda Türkiye, İran, Irak ve Afganistan arasında imzalanmıştır.');
    addQ(1, 7, 1, 'II. Dünya Savaşı sırasında Türkiye Cumhuriyeti Cumhurbaşkanı kimdi?', 'İsmet İnönü', 'Mustafa Kemal Atatürk', 'Celal Bayar', 'Cemal Gürsel', 'Fevzi Çakmak', 'A', '1938-1950 yılları arasında İsmet İnönü Cumhurbaşkanlığı yapmıştır.');
    addQ(1, 7, 1, 'Türkiye, II. Dünya Savaşı\'na fiilen girmemiş ancak San Francisco Konferansı\'na katılıp Birleşmiş Milletler kurucu üyesi olabilmek için savaşın sonunda kime savaş ilan etmiştir?', 'Almanya ve Japonya', 'İtalya ve İngiltere', 'Sovyetler Birliği', 'ABD', 'Fransa', 'A', 'Şubat 1945\'te simgesel olarak Almanya ve Japonya\'ya savaş ilan edilmiştir.');
    addQ(1, 7, 1, 'Türkiye Cumhuriyeti çok partili hayata kesin olarak hangi yılda geçmiş ve ilk tek dereceli genel seçim ne zaman yapılmıştır?', '1946 Genel Seçimleri', '1924', '1930', '1950', '1960', 'A', '1946\'da çok partili seçim yapılmış, 1950 seçimlerinde ise Demokrat Parti iktidara gelmiştir.');
    addQ(1, 7, 1, '1950 yılında Demokrat Parti\'nin iktidara geldiği seçimler tarihe hangi isimle geçmiştir?', 'Beyaz İhtilal', 'Gül Devrimi', 'Kadife Devrim', 'Hürriyet Devrimi', 'Milli Mücadele', 'A', '27 yıllık CHP iktidarının sandık yoluyla kansız devredilmesine "Beyaz İhtilal" denmiştir.');
    addQ(1, 7, 1, 'Türkiye hangi savaşa asker göndererek 1952 yılında Kuzey Atlantik Paktı\'na (NATO) resmen üye olmuştur?', 'Kore Savaşı (1950)', 'Vietnam Savaşı', 'Körfez Savaşı', 'II. Dünya Savaşı', 'Afganistan Savaşı', 'A', 'Tahsin Yazıcı komutasındaki Türk Tugayı Kunuri\'de kahramanlık göstermiş ve Türkiye NATO\'ya kabul edilmiştir.');
    addQ(1, 7, 1, 'Kıbrıs Türklerinin haklarını savunmak amacıyla kurulan ve "Toros" kod adıyla anılan Kıbrıs Türk Federe Devleti lideri kimdir?', 'Rauf Denktaş', 'Fazıl Küçük', 'Bülent Ecevit', 'Necmettin Erbakan', 'Cengiz Topel', 'A', 'Rauf Denktaş KKTC\'nin kurucu Cumhurbaşkanıdır.');
    addQ(1, 7, 1, '1974 yılında gerçekleştirilen Kıbrıs Barış Harekâtı\'nın parola cümlesi hangisidir?', '"Ayşe tatile çıksın"', '"Güneş batıdan doğsun"', '"Zafer inananlarındır"', '"Hedef Akdeniz"', '"Barış olsun"', 'A', 'Dışişleri Bakanı Turan Güneş Başbakan Bülent Ecevit\'e "Ayşe tatile çıksın" parolasını ileterek II. harekatı başlatmıştır.');
    addQ(1, 7, 1, 'Soğuk Savaş döneminde ABD öncülüğünde Batı Bloku\'nun askeri örgütü NATO\'ya karşı Doğu Bloku\'nun kurduğu askeri pakt hangisidir?', 'Varşova Paktı', 'Kominform', 'Comecon', 'Bağdat Paktı', 'SEATO', 'A', '1955\'te SSCB öncülüğünde Varşova Paktı kurulmuştur.');

    // Level 2: Orta Düzey
    addQ(1, 7, 2, 'ABD Başkanı Truman tarafından Sovyet yayılmacılığına karşı Türkiye ve Yunanistan\'a askeri ve mali yardım öngören doktrin hangisidir?', 'Truman Doktrini (1947)', 'Marshall Planı', 'Eisenhower Doktrini', 'Monroe Doktrini', 'Breznev Doktrini', 'A', 'Truman Doktrini ile Türkiye Batı Bloku güvenlik şemsiyesine dahil olmuştur.');
    addQ(1, 7, 2, 'II. Dünya Savaşı\'nda yıkılan Avrupa ekonomilerini canlandırmak amacıyla ABD tarafından uygulanan ekonomik yardım programı hangisidir?', 'Marshall Planı', 'Schuman Bildirisi', 'Dawes Planı', 'New Deal', 'Molotov Planı', 'A', 'Marshall Planı aralarında Türkiye\'nin de bulunduğu 16 Avrupa ülkesine hibe ve kredi sağlamıştır.');
    addQ(1, 7, 2, 'SSCB lideri Gorbaçov\'un 1985\'te başlattığı "Açıklık" ve "Yeniden Yapılanma" politikalarının Rusça isimleri nelerdir?', 'Glasnost (Açıklık) ve Perestroyka (Yeniden Yapılanma)', 'Sputnik ve Soyuz', 'Kolkhoz ve Sovkhoz', 'Duma ve Çeka', 'Bolşevik ve Menşevik', 'A', 'Glasnost şeffaflığı, Perestroyka ise ekonomik yeniden yapılanmayı amaçlamış ancak SSCB\'nin dağılmasına yol açmıştır.');
    addQ(1, 7, 2, 'Soğuk Savaş döneminde ABD ile SSCB\'yi nükleer savaşın eşiğine getiren 1962 tarihli kriz hangisidir?', 'Küba Füze Krizi (Füzeler Bunalımı)', 'Berlin Buhranı', 'U-2 Casus Uçak Krizi', 'Süveyş Krizi', 'Kore Krizi', 'A', 'Küba füzeleri krizi sırasında Türkiye\'deki Jüpiter füzeleri de pazarlık konusu yapılmıştır.');
    addQ(1, 7, 2, 'Bosna Savaşı\'nda halkını savunan, "Bilge Kral" olarak anılan ve bağımsız Bosna-Hersek\'in ilk cumhurbaşkanı olan lider kimdir?', 'Aliya İzzetbegoviç', 'Haris Silayciç', 'Bakir İzzetbegoviç', 'Tito', 'Enver Hoca', 'A', 'Aliya İzzetbegoviç İslam Deklarasyonu\'nun yazarı ve Bosna\'nın efsanevi lideridir.');
    addQ(1, 7, 2, 'Türk dünyasıyla ilişkileri geliştirmek, kültürel ve teknik iş birliğini sağlamak amacıyla 1992\'de kurulan Türk kurumu hangisidir?', 'TİKA (Türk İşbirliği ve Koordinasyon Ajansı)', 'YTB', 'TÜRKSOY', 'Yunus Emre Enstitüsü', 'Kızılay', 'A', 'TİKA Orta Asya ve Balkanlar başta olmak üzere kalkınma yardımları yürüten çatı kuruluştur.');
    addQ(1, 7, 2, 'Avrupa Birliği\'nin temeli kabul edilen 1951 tarihli antlaşma ve kurulan birlik hangisidir?', 'Paris Antlaşması - Avrupa Kömür ve Çelik Topluluğu (AKÇT)', 'Roma Antlaşması - AET', 'Maastricht Antlaşması', 'Lizbon Antlaşması', 'Schengen Antlaşması', 'A', 'Schuman Bildirisi sonucu 1951 Paris Antlaşması ile AKÇT kurulmuştur.');
    addQ(1, 7, 2, 'Bağlantısızlar Hareketi\'nin (Üçüncü Dünya) ilkeleri hangi konferansta belirlenmiştir?', '1955 Bandung Konferansı', 'Yalta Konferansı', 'Potsdam Konferansı', 'Tahran Konferansı', 'Helsinki Nihai Senedi', 'A', 'Endonezya\'da toplanan Bandung Konferansı Bağlantısızlar Hareketi\'nin doğuşudur.');
    addQ(1, 7, 2, '1991 yılında Sovyetler Birliği\'nin dağılmasıyla bağımsızlığını ilan eden ilk Türk cumhuriyeti hangisidir?', 'Azerbaycan', 'Kazakistan', 'Özbekistan', 'Türkmenistan', 'Kırgızistan', 'A', 'Azerbaycan bağımsızlığını ilan etmiş ve Türkiye Azerbaycan\'ı tanıyan ilk ülke olmuştur.');
    addQ(1, 7, 2, 'Hindistan\'ın bağımsızlık mücadelesinde "Tuz Yürüyüşü" ve "Pasif Direniş" yöntemlerini uygulayan manevi lider kimdir?', 'Mahatma Gandi', 'Muhammed Ali Cinnah', 'Cevahir Lal Nehru', 'İndira Gandi', 'Subhas Chandra Bose', 'A', 'Mahatma Gandi şiddetsiz sivil itaatsizliğin öncüsüdür.');

    // Level 3: Zor & Detay
    addQ(1, 7, 3, '1973 Arap-İsrail (Yom Kippur) Savaşı sonrası petrol fiyatlarının fırlamasıyla başlayan krizde barış sağlamak için uygulanan "Mekik Diplomasisi" hangi ABD Dışişleri Bakanı\'na aittir?', 'Henry Kissinger', 'George Marshall', 'John Foster Dulles', 'Zbigniew Brzezinski', 'Cyrus Vance', 'A', 'Henry Kissinger İsrail, Mısır ve Suriye arasında mekik dokuyarak 1978 Camp David Sözleşmesi\'ne giden yolu açmıştır.');
    addQ(1, 7, 3, 'İsrail ile Mısır arasında barış sağlayan ve bir Arap devletinin İsrail\'i ilk kez resmen tanıdığı 1978 antlaşması hangisidir?', 'Camp David Antlaşması', 'Oslo Görüşmeleri', 'Madrid Konferansı', 'Wye River', 'Abraham Anlaşmaları', 'A', 'Enver Sedat ve Menahem Begin arasında imzalanan Camp David ile Mısır Sina Yarımadası\'nı geri almıştır.');
    addQ(1, 7, 3, 'İran-Irak Savaşı\'nda (1980-1988) ABD\'nin gizlice İran\'a silah satıp gelirini Nikaragua\'daki gerillalara aktarması skandalına ne ad verilir?', 'İran-Kontra Skandalı', 'Watergate Skandalı', 'Monika Skandalı', 'Pentagon Belgeleri', 'Körfez Skandalı', 'A', 'İran-Kontra Skandalı Ronald Reagan döneminin en büyük dış politika krizidir.');
    addQ(1, 7, 3, '1995 yılında Bosna Savaşı\'na son veren ve Aliya İzzetbegoviç, Slobodan Miloseviç ve Franjo Tudjman tarafından imzalanan barış antlaşması hangisidir?', 'Dayton Barış Antlaşması', 'Cenevre Antlaşması', 'Brüksel Protokolü', 'Paris Sözleşmesi', 'Helsinki Senedi', 'A', 'ABD\'nin Ohio eyaletinde imzalanan Dayton Antlaşması ile Bosna-Hersek devleti kurulmuştur.');
    addQ(1, 7, 3, 'Avrupa Birliği\'ne üye ülkeler arasında ortak para birimi (Euro) ve tek pazar kriterlerini belirleyen 1992 antlaşması hangisidir?', 'Maastricht Antlaşması', 'Roma Antlaşması', 'Amsterdam Antlaşması', 'Nice Antlaşması', 'Lizbon Antlaşması', 'A', '1992 Maastricht Antlaşması ile Avrupa Ekonomik Topluluğu resmi olarak "Avrupa Birliği" adını almıştır.');
    addQ(1, 7, 3, 'Türkiye\'nin AB\'ye tam üyelik yolunda 1963 yılında imzaladığı ortaklık antlaşması hangisidir?', 'Ankara Antlaşması', 'Katma Protokol', 'Gümrük Birliği', 'Kopenhag Kriterleri', 'Helsinki Zirvesi', 'A', '12 Eylül 1963\'te imzalanan Ankara Antlaşması Türkiye-AET ortaklığının hukuki temelidir.');
    addQ(1, 7, 3, '1988 yılında Azerbaycan toprağı Karabağ\'da Ermenilerin gerçekleştirdiği ve yüzlerce masum sivilin katledildiği insanlık faciası hangisidir?', 'Hocalı Katliamı (1992)', 'Srebrenitsa Katliamı', 'Kanlı Noel', 'Halepçe Katliamı', 'Reçak Katliamı', 'A', '26 Şubat 1992\'de gerçekleşen Hocalı Katliamı insanlık tarihinin en acı trajedilerindendir.');
    addQ(1, 7, 3, '1975 Helsinki Nihai Senedi ile temelleri atılan ve üye ülkelerde insan hakları, demokrasi ve güvenliği izleyen uluslararası örgüt hangisidir?', 'AGİT (Avrupa Güvenlik ve İşbirliği Teşkilatı)', 'Avrupa Konseyi', 'OECD', 'UNESCO', 'Uluslararası Af Örgütü', 'A', 'AGİK (daha sonra AGİT) Soğuk Savaş yumuşama döneminin en önemli diplomatik kazanımıdır.');
    addQ(1, 7, 3, '1964 yılında Kıbrıs\'ta Rum saldırılarına karşı uyarı uçuşu yaparken uçağı düşen ve Rumlar tarafından şehit edilen ilk Türk hava harp şehidi kimdir?', 'Yüzbaşı Cengiz Topel', 'Vecihi Hürkuş', 'Ahmet Ali Çeliktel', 'Fethi Bey', 'Sabiha Gökçen', 'A', 'Cengiz Topel Erenköy Direnişi sırasında şehit düşmüş ve adı pek çok sokağa, okula verilmiştir.');
    addQ(1, 7, 3, 'ASALA terör örgütünün Türk diplomatlarına yönelik suikastlarına karşı Türkiye\'nin yürüttüğü mücadelede 1980\'lerde örgütün çöküşünü hızlandıran eylem hangisidir?', 'Orly Havalimanı Saldırısı (1983) sonrası uluslararası desteğin bitmesi', 'Viyana eylemi', 'Lizbon baskını', 'Madrid suikastı', 'Atina operasyonu', 'A', '1983 Orly saldırısında Fransız sivillerin de ölmesi örgütün Batı desteğini tamamen kaybetmesine yol açmıştır.');

};
