SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (1, 1, 52, '', 'İslamiyet öncesi Türk devletlerinde hakanın buyruklarının \'Gök Tanrı\'nın buyruğu\' sayılarak itaat edilmesi ancak hakanın töreye aykırı hareket ettiğinde tahttan indirilebilmesi durumu dikkate alındığında;

I. Egemenliğin meşruiyetinin ilahi temele dayandırıldığı,
II. Hakanın yetkilerinin mutlak ve sınırsız olmadığı,
III. Devlet yönetiminde yazılı anayasal düzene geçildiği

yargılarından hangilerine ulaşılabilir?', 1, 'Yalnız I', 'Yalnız II', 'I ve II', 'II ve III', 'I, II ve III', 'c', 2, 'İslamiyet öncesi Türklerde kut inancı egemenliğin ilahi kaynaklı olduğunu gösterir (I). Ancak töre kuralları hakanın da üstünde olup yetkilerini sınırlandırmıştır (II). Töreler yazısız hukuk kuralları olduğu için yazılı anayasal düzenden bahsedilemez (III). Doğru cevap: C (I ve II).');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (1, 1, 52, '', 'Büyük Selçuklu Devleti\'nde uygulanan İkta Sistemi sayesinde;

I. Taşrada devlet otoritesinin ve asayişin sürekliliği sağlanmıştır.
II. Hazineden para çıkmadan savaşa hazır sipahi ordusu oluşturulmuştur.
III. Üretimde süreklilik güvence altına alınmıştır.

Yukarıdakilerden hangileri bu sistemin hem askeri hem de iktisadi boyutunu kanıtlar?', 1, 'Yalnız I', 'Yalnız II', 'I ve II', 'II ve III', 'I, II ve III', 'e', 2, 'İkta sistemi; üretimin aksamamasını sağlayarak iktisadi (III), cebelü askerleri yetiştirerek askeri (II), asayişi koruyarak idari (I) faydalar sağlamıştır. Dolayısıyla öncüllerin tamamı sistemin fonksiyonlarındandır. Doğru cevap: E.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (1, 1, 52, '', 'Osmanlı Devleti\'nde 17. yüzyıldan itibaren tımar sisteminin bozulmasıyla birlikte yaygınlaşan iltizam ve malikane uygulamalarının;

I. Merkezî hazineye anlık nakit para akışı sağlama,
II. Taşrada ayan ve eşraf gibi yerel güç odaklarının doğmasına zemin hazırlama,
III. Reayanın toprağa bağlılığını artırarak göçleri önleme

sonuçlarından hangilerini doğurduğu savunulabilir?', 1, 'Yalnız I', 'Yalnız III', 'I ve II', 'II ve III', 'I, II ve III', 'c', 2, 'İltizam sistemi devlete acil nakit sağlamış (I), mültezimlerin güçlenmesiyle zamanla ayanlar sınıfı doğmuştur (II). Aksine köylü ağır vergiler nedeniyle toprağını terk etmiş (Büyük Kaçgun) göçler artmıştır (III yanlıştır). Doğru cevap: C (I ve II).');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (1, 1, 52, '', 'Osmanlı Devleti\'nde 1876 Kanun-i Esasi\'de padişahın mutlak yetkileri bulunurken, 1909 Anayasa Değişiklikleri ile;

I. Hükûmetin (Heyet-i Vükela) padişaha değil, Mebusan Meclisine karşı sorumlu olması,
II. Padişahın meclisi kapatma yetkisinin zorlaştırılması,
III. Padişahın sürgün yetkisini düzenleyen 113. maddenin kaldırılması

hükümlerinden hangileri getirilerek parlamenter monarşi ilkeleri güçlendirilmiştir?', 1, 'Yalnız I', 'I ve II', 'I ve III', 'II ve III', 'I, II ve III', 'e', 2, '1909 değişiklikleri ile padişahın veto ve meclisi fesih yetkileri sınırlandırılmış, 113. maddedeki sürgün yetkisi kaldırılmış ve hükûmet meclise karşı sorumlu kılınarak gerçek anlamda parlamenter sisteme geçilmiştir. Doğru cevap: E.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (1, 1, 52, '', 'Mustafa Kemal Paşa\'nın Amasya Genelgesi\'nde yer alan "Milletin bağımsızlığını yine milletin azim ve kararı kurtaracaktır." maddesi ilk kez aşağıdakilerden hangisinin değişeceğine açık bir işarettir?', 1, 'Ekonomik bağımsızlık anlayışının', 'Egemenliğin kaynağı ve yönetim biçiminin', 'Ordunun teşkilatlanma tarzının', 'Uluslararası ittifak dengelerinin', 'Devletin başkentinin', 'b', 2, 'Bu madde Kurtuluş Savaşı\'nın hem amacını hem yöntemini belirtir; millet iradesine vurgu yaparak üstü kapalı şekilde egemenliğin kaynağının padişahtan millete geçeceğini (cumhuriyet rejimini) müjdeler. Doğru cevap: B.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (1, 1, 52, '', 'Son Osmanlı Mebusan Meclisinde kabul edilen Misak-ı Millî kararlarında;

I. Kars, Ardahan, Batum (Elviye-i Selase),
II. Batı Trakya,
III. Arap vilayetleri

bölgelerinden hangilerinde gerekirse halk oylamasına (plebisit) başvurulabileceği kabul edilmiştir?', 1, 'Yalnız I', 'I ve II', 'I ve III', 'II ve III', 'I, II ve III', 'e', 2, 'Misak-ı Millî kararlarında Türk ve Müslüman nüfusun çoğunlukta olduğuna güvenilen Elviye-i Selase (Kars, Ardahan, Batum), Batı Trakya ve Arap topraklarında halk oylaması yapılması öngörülmüştür. Doğru cevap: E.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (1, 1, 52, '', 'Lozan Barış Antlaşması\'nda çözüme kavuşturulamayıp Türkiye ile İngiltere arasındaki ikili görüşmelere bırakılan ve daha sonra Milletler Cemiyetine taşınan mesele aşağıdakilerden hangisidir?', 1, 'Hatay Sorunu', 'Musul Sorunu (Irak Sınırı)', 'Boğazlar Rejimi', 'Dış Borçlar Sorunu', 'Patrikhane Meselesi', 'b', 2, 'Lozan Antlaşması\'nda çözülemeyen tek sınır meselesi Türkiye-Irak sınırı (Musul Sorunu) olmuştur. Taraflar 9 ay içinde anlaşamazsa Milletler Cemiyetine gitmesi kararlaştırılmıştır. Doğru cevap: B.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (1, 1, 52, '', 'Atatürk Dönemi\'nde 1936 yılında imzalanan Montrö Boğazlar Sözleşmesi ile;

I. Boğazlar Komisyonunun kaldırılarak yetkilerinin Türkiye\'ye devredilmesi,
II. Türkiye\'nin Boğazların her iki yakasında asker bulundurma hakkını elde etmesi,
III. Savaş gemilerinin geçişinde Karadeniz\'e kıyıdaş olan ve olmayan ülkelere farklı tonaj kısıtlamaları getirilmesi

gelişmelerinden hangileri Türkiye\'nin egemenlik haklarını tam olarak pekiştirmiştir?', 1, 'Yalnız I', 'I ve II', 'I ve III', 'II ve III', 'I, II ve III', 'e', 2, 'Montrö Sözleşmesi ile uluslararası komisyon kaldırılmış, askerden arındırılmış bölgelere Türk askeri yerleştirilmiş ve yabancı savaş gemilerine sıkı kurallar getirilerek Türkiye Boğazlar üzerinde tam hâkimiyet kurmuştur. Doğru cevap: E.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (1, 1, 52, '', 'Osmanlı Devleti\'nde şeyhülislam, kazasker ve kadıların mensup olduğu, adalet, din ve eğitim işlerinden sorumlu devlet sınıfı aşağıdakilerden hangisidir?', 1, 'Seyfiye', 'Kalemiye', 'İlmiye', 'Mülkiye', 'Teknofiye', 'c', 2, 'Osmanlı bürokrasisinde eğitim (müderris), din (müftü/şeyhülislam) ve hukuk/yargı (kadı/kazasker) görevlileri İlmiye (Ulema) sınıfına mensuptur. Seyfiye askeri/idari, Kalemiye ise mali/bürokratik sınıftır. Doğru cevap: C.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (1, 1, 52, '', 'Atatürk\'ün \'Devletçilik\' ilkesinin Türkiye\'deki uygulamaları dikkate alındığında aşağıdakilerden hangisi bu ilkenin temel hedeflerinden biri olamaz?', 1, 'Özel sektörün sermaye ve tecrübe yetersizliği nedeniyle yapamadığı büyük yatırımları devlet eliyle gerçekleştirmek', 'Bölgeler arasındaki gelişmişlik farklarını azaltmak', 'Özel teşebbüsü ve serbest piyasa mülkiyetini tamamen ortadan kaldırarak kolektif mülkiyete geçmek', 'Hammadde temini yurt içinden sağlanan sanayi kollarını öncelikle kurmak', 'Temel tüketim maddelerinde dışa bağımlılığı en aza indirmek', 'c', 2, 'Kemalist Devletçilik ilkesi sosyalizm/komünizm gibi özel mülkiyeti ve özel sektörü reddetmez; aksine özel teşebbüsü destekleyen karma ekonomik bir modeldir. Özel teşebbüsü ortadan kaldırmak hedefi yoktur. Doğru cevap: C.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (2, 8, 52, '', 'Türkiye\'de 21 Haziran tarihinde güneyden kuzeye doğru gidildikçe;

I. Gündüz süresi uzar.
II. Güneş ışınlarının geliş açısı küçülür.
III. Çizgisel dönüş hızı artar.

yargılarından hangileri doğrudur?', 1, 'Yalnız I', 'I ve II', 'I ve III', 'II ve III', 'I, II ve III', 'b', 2, '21 Haziran\'da kuzeye gidildikçe gündüz süresi uzar (I). Kutuplara yaklaşıldığı için güneş ışınlarının açısı küçülür (II). Ancak çizgisel hız ekvatordan kutuplara gidildikçe azalır, artmaz (III yanlıştır). Doğru cevap: B (I ve II).');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (2, 8, 52, '', 'Türkiye\'de karstik aşınım ve birikim şekillerinin en yaygın olduğu Teke ve Taşeli platolarında nüfus yoğunluğunun Türkiye ortalamasının çok altında olmasının temel nedeni aşağıdakilerden hangisidir?', 1, 'Kış mevsiminin çok sert ve karlı geçmesi', 'Kalkerli yapının suyu yer altına sızdırması ve yüzey sularının yetersizliği ile engebeli arazi', 'Orman varlığının bulunmaması', 'Deniz etkisinden tamamen uzak karasal iklim koşulları', 'Maden yataklarının bulunmayışı', 'b', 2, 'Teke ve Taşeli platoları Akdeniz iklim bölgesinde yer almasına rağmen karstik (kireçtaşı) arazinin suyu derine geçirmesi (taban suyunun derinde olması), tarım topraklarının azlığı ve aşırı engebe sebebiyle tenha nüfusludur. Doğru cevap: B.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (2, 8, 52, '', 'Rize ve çevresinde kış mevsiminde turunçgil ve çay gibi mikroklima ürünlerinin yetiştirilebilmesinde en belirleyici faktör aşağıdakilerden hangisidir?', 1, 'Kafkas Dağları\'nın kuzeyden gelen soğuk hava dalgalarını kesmesi ve fön rüzgârlarının kış ılıklığı sağlaması', 'Yıllık güneşlenme süresinin Türkiye ortalamasının çok üzerinde olması', 'Alüvyal toprakların geniş yer kaplaması', 'Enlem etkisine bağlı olarak Güneş ışınlarını dik açıyla alması', 'Gelgit genliğinin yüksek olması', 'a', 2, 'Doğu Karadeniz kıyılarında Kaçkarların kuzeyden gelen soğukları engellemesi ve dağları aşarak alçalan havanın fön etkisi yaratması kış aylarında ılıman bir mikroklima oluşturur. Doğru cevap: A.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (2, 8, 52, '', 'Türkiye\'de nadas tarımının yaygın olduğu bir bölgede sulama imkânlarının geliştirilmesi durumunda aşağıdakilerden hangisinin gerçekleşmesi beklenmez?', 1, 'Tarımsal üretimde yıldan yıla görülen dalgalanmaların azalması', 'Birim alandan elde edilen tarımsal verimin artması', 'Nadasa ayrılan toprak oranının önemli ölçüde düşmesi', 'Kırsal alandan kentlere yapılan ekonomik göç baskısının artması', 'Sanayi bitkilerinin (pamuk, mısır vb.) ekim alanlarının genişlemesi', 'd', 2, 'Sulama olanaklarının artması çiftçinin gelirini ve refahını artıracağı için kırdan kente göç baskısını artırmaz, aksine azaltır veya tersine çevirir. Doğru cevap: D.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (2, 8, 52, '', 'Aşağıdaki maden ve çıkarıldığı başlıca merkez eşleştirmelerinden hangisi yanlıştır?', 1, 'Bor mineralleri - Balıkesir (Bigadiç) / Kütahya (Emet)', 'Boksit (Alüminyum) - Konya (Seydişehir) / Antalya (Akseki)', 'Krom - Muğla (Fethiye) / Elazığ (Guleman)', 'Demir - Sivas (Divriği) / Malatya (Hekimhan)', 'Bakır - Manisa (Soma) / Zonguldak (Ereğli)', 'e', 2, 'Soma ve Zonguldak kömür havzalarıdır (Linyit ve Taş Kömürü). Bakırın başlıca çıkarım alanları ise Artvin (Murgul), Kastamonu (Küre) ve Elazığ (Maden)\'dır. Doğru cevap: E.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (2, 8, 52, '', 'Türkiye\'de jeotermal enerjiden hem elektrik üretimi hem de sera ve konut ısıtmasında en yoğun şekilde faydalanılan bölge aşağıdakilerden hangisidir?', 1, 'Doğu Anadolu (Yukarı Fırat Bölümü)', 'Ege Bölgesi (Kıyı Ege Graben Alanları)', 'İç Anadolu (Konya Kapalı Havzası)', 'Karadeniz Bölgesi (Batı Karadeniz Bölümü)', 'Güneydoğu Anadolu (Dicle Bölümü)', 'b', 2, 'Kıyı Ege kırıklı (fay) tektonik hatları ve graben alanları (Büyük ve Küçük Menderes, Gediz) nedeniyle jeotermal kaynaklar bakımından en zengin bölgedir (Denizli-Sarayköy, Aydın-Germencik). Doğru cevap: B.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (2, 8, 52, '', 'Aşağıdaki limanlardan hangisinin demiryolu bağlantısı bulunmadığı için ardülkesi (hinterlandı) dar kalmış ve ticaret hacmi sınırlı düzeydedir?', 1, 'Samsun Limanı', 'İskenderun Limanı', 'Sinop Limanı', 'İzmir Limanı', 'Mersin Limanı', 'c', 2, 'Sinop Limanı doğal bir liman olmasına rağmen arkasındaki Küre Dağları ve demiryolu bağlantısının olmaması nedeniyle hinterlandı gelişememiştir. Samsun, İskenderun, İzmir ve Mersin limanlarının demiryolu bağlantısı vardır. Doğru cevap: C.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (2, 8, 52, '', 'Türkiye\'nin nüfus piramidi incelendiğinde tabanın daralmakta, tepe noktasının ise genişlemekte olduğu görülmektedir. Bu durum aşağıdakilerden hangisinin kesin bir göstergesidir?', 1, 'Doğum oranlarının azaldığının ve yaşlı nüfus oranının arttığının', 'Dış ülkelere verilen iş gücü göçünün hızlandığının', 'Kırsal nüfus oranının kent nüfus oranını aştığının', 'Genç bağımlı nüfus oranının arttığının', 'Ortalama yaşam süresinin kısaldığının', 'a', 2, 'Piramit tabanının daralması doğum oranlarının gerilediğini, üst kısmın genişlemesi ise ortalama ömrün uzamasıyla yaşlı nüfus oranının arttığını gösterir. Doğru cevap: A.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (2, 8, 52, '', 'Güneydoğu Anadolu Projesi (GAP) kapsamında sulama kanallarının devreye girmesiyle birlikte ekim alanı ve üretiminde en yüksek artış kaydedilen ürün aşağıdakilerden hangisidir?', 1, 'Tütün', 'Pamuk', 'Çay', 'Fındık', 'Zeytin', 'b', 2, 'GAP ile birlikte Şanlıurfa ve çevresinde sulamalı tarıma geçilmesi sonucunda Türkiye pamuk üretiminin yarısından fazlası bu bölgeden sağlanır hâle gelmiştir. Doğru cevap: B.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (2, 8, 52, '', 'UNESCO Dünya Mirası Listesi\'nde hem doğal hem de kültürel özellikleri bünyesinde barındıran \'karma miras\' statüsündeki iki varlığımız aşağıdakilerden hangisinde birlikte verilmiştir?', 1, 'Göbeklitepe - Safranbolu Evleri', 'Nemrut Dağı - Divriği Ulu Camii', 'Pamukkale (Hierapolis) - Kapadokya (Göreme Millî Parkı)', 'Truva Antik Kenti - Çatalhöyük', 'Efes Antik Kenti - Ani Harabeleri', 'c', 2, 'Türkiye\'de UNESCO Dünya Mirası Listesi\'ndeki karma (hem doğal hem kültürel) sit alanları sadece Göreme Millî Parkı ve Kapadokya ile Pamukkale-Hierapolis\'tir. Doğru cevap: C.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (3, 13, 52, '', 'Türk Medeni Kanunu\'na göre, hakların kazanılmasında geçerli olan temel ilke ile hakların kullanılmasında ve borçların yerine getirilmesinde geçerli olan temel ilke aşağıdakilerden hangisinde sırasıyla doğru verilmiştir?', 1, 'İyiniyet - Dürüstlük Kuralı (Objektif İyiniyet)', 'Dürüstlük Kuralı - İyiniyet (Sübjektif İyiniyet)', 'Kusursuz Sorumluluk - Denkleştirici Adalet', 'Hakkaniyet - Ahde Vefa', 'Gecikmiş İfa - İyiniyet', 'a', 2, 'TMK Madde 3\'e göre hakların kazanılmasında \'İyiniyet\' (Sübjektif İyiniyet), Madde 2\'ye göre hakların kullanılmasında ve borçların ifasında ise \'Dürüstlük Kuralı\' (Objektif İyiniyet) geçerlidir. Doğru cevap: A.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (3, 13, 52, '', 'Normlar hiyerarşisi dikkate alındığında, kanunlar ile Cumhurbaşkanlığı Kararnameleri (CBK) arasındaki ilişki bakımından aşağıdakilerden hangisi yanlıştır?', 1, 'Anayasa\'da münhasıran kanunla düzenlenmesi öngörülen konularda Cumhurbaşkanlığı Kararnamesi çıkarılamaz.', 'Kanunda açıkça düzenlenen konularda Cumhurbaşkanlığı Kararnamesi çıkarılamaz.', 'Cumhurbaşkanlığı Kararnamesi ile kanunlarda farklı hükümler bulunması hâlinde kanun hükümleri uygulanır.', 'TBMM\'nin aynı konuda kanun çıkarması durumunda Cumhurbaşkanlığı Kararnamesi hükümsüz hâle gelir.', 'Olağan dönem Cumhurbaşkanlığı Kararnameleri ile Anayasa\'nın ikinci kısmında yer alan kişi hak ve ödevleri düzenlenebilir.', 'e', 2, '1982 Anayasası m.104\'e göre; olağan dönem CBK\'ları ile Anayasa\'nın ikinci kısmındaki Temel Haklar ve Ödevler (Kişi hakları) ve Siyasi Haklar düzenlenemez; sadece Sosyal ve Ekonomik Haklar düzenlenebilir. Doğru cevap: E.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (3, 13, 52, '', '1982 Anayasası\'na göre savaş, seferberlik ve olağanüstü hâllerde dahi dokunulamayan \'sert çekirdek haklar\' arasında aşağıdakilerden hangisi yer almaz?', 1, 'Kişinin yaşama hakkı ile maddi ve manevi varlığının bütünlüğü', 'Kimsenin din, vicdan, düşünce ve kanaatlerini açıklamaya zorlanamaması', 'Suç ve cezaların geçmişe yürütülememesi ilkesi', 'Suçluluğu mahkeme kararı ile saptanıncaya kadar kimsenin suçlu sayılamayacağı (Masumiyet Karinesi)', 'Mülkiyet hakkı ve sözleşme hürriyeti', 'e', 2, 'Anayasa\'nın 15. maddesinde sayılan çekirdek haklar: Yaşama hakkı/vücut bütünlüğü, din-vicdan-düşünce açıklamaya zorlanamama, masumiyet karinesi ve suç/cezaların geriye yürümezliğidir. Mülkiyet hakkı çekirdek hak kapsamında değildir. Doğru cevap: E.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (3, 13, 52, '', '1982 Anayasası\'na göre, Türkiye Büyük Millet Meclisinin (TBMM) bilgi edinme ve denetim yolları arasında aşağıdakilerden hangisi yer almaz?', 1, 'Meclis Araştırması', 'Genel Görüşme', 'Meclis Soruşturması', 'Yazılı Soru', 'Gensoru', 'e', 2, '2017 Anayasa Değişikliği ile Cumhurbaşkanlığı Hükümet Sistemi\'ne geçilmiş; Gensoru ve Sözlü Soru kurumları Anayasa\'dan tamamen çıkarılmıştır. Doğru cevap: E.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (3, 13, 52, '', '1982 Anayasası\'na göre, Cumhurbaşkanlığı Kararnamelerinin şekil ve esas bakımından Anayasa\'ya aykırılığı iddiasıyla Anayasa Mahkemesinde doğrudan iptal davası açmaya yetkili olanlar aşağıdakilerden hangisinde tam olarak verilmiştir?', 1, 'Cumhurbaşkanı, TBMM Başkanı ve Sayıştay Başkanı', 'TBMM üye tamsayısının en az beşte biri (1/5) ve Danıştay Başkanı', 'TBMM\'de en fazla üyeye sahip iki siyasi parti grubu ve TBMM üye tamsayısının en az beşte biri (120 milletvekili)', 'Yargıtay Cumhuriyet Başsavcısı ve Adalet Bakanı', 'Kamu Denetçiliği Kurumu ve Hakimler Savcılar Kurulu', 'c', 2, 'Anayasa Mahkemesinde doğrudan iptal davası açmaya (somut değil soyut norm denetimi): TBMM\'de en fazla üyeye sahip iki siyasi parti grubu ile TBMM üye tamsayısının en az beşte biri (120 milletvekili) yetkilidir (ayrıca kanunlar için CB de açabilir). Doğru cevap: C.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (3, 13, 52, '', 'Anayasa Mahkemesi\'ne yapılan \'Bireysel Başvuru\' mekanizması ile ilgili olarak aşağıdakilerden hangisi yanlıştır?', 1, 'Kamu gücü tarafından Anayasa ve AİHS\'te ortak korunan temel hak ve özgürlükleri ihlal edilen herkes başvurabilir.', 'Başvuru yapabilmek için olağan kanun yollarının (idari ve yargısal süreçlerin) tüketilmiş olması zorunludur.', 'İdari işlemler ve yasama işlemleri (kanunlar) aleyhine doğrudan bireysel başvuru yapılamaz.', 'Bireysel başvurular Anayasa Mahkemesi Genel Kurulu ve Bölümler tarafından incelenir.', 'Kamu tüzel kişileri de kendi adlarına temel hak ihlali iddiasıyla bireysel başvuru yapabilirler.', 'e', 2, 'Kamu tüzel kişileri temel hak sahibi olamayacakları için bireysel başvuru yapamazlar. Yalnızca özel hukuk tüzel kişileri kendi haklarıyla sınırlı olarak başvurabilir. Doğru cevap: E.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (3, 13, 52, '', 'İdare hukukunda yer alan \'İdarenin Bütünlüğü\' ilkesi kapsamında; İçişleri Bakanının bir il valisinin işlemlerini denetlemesi ile bir il belediye başkanının imar kararını denetlemesi arasındaki hukuki ilişki sırasıyla aşağıdakilerden hangisidir?', 1, 'Hiyerarşi - İdari Vesayet', 'İdari Vesayet - Hiyerarşi', 'Yetki Genişliği - Yerinden Yönetim', 'İdari Vesayet - Yetki Devri', 'Hiyerarşi - İmza Yetkisi', 'a', 2, 'Aynı kamu tüzel kişiliği (devlet tüzel kişiliği) içindeki ast-üst ilişkisi \'Hiyerarşi\'dir (Bakan - Vali). Ayrı kamu tüzel kişilikleri arasındaki merkezi denetim ise \'İdari Vesayet\'tir (Bakan - Belediye Başkanı). Doğru cevap: A.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (3, 13, 52, '', 'Aşağıdakilerden hangisi Anayasa\'da güvence altına alınmış olan \'yüksek mahkemeler\' arasında yer almaz?', 1, 'Anayasa Mahkemesi', 'Yargıtay', 'Danıştay', 'Uyuşmazlık Mahkemesi', 'Sayıştay', 'e', 2, '1982 Anayasası\'nda sayılan 4 yüksek mahkeme vardır: Anayasa Mahkemesi, Yargıtay, Danıştay ve Uyuşmazlık Mahkemesi. Sayıştay ve HSK yüksek mahkeme değil, yüksek denetim ve idari kurullardır. Doğru cevap: E.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (3, 13, 52, '', 'Türkiye\'de bir yerleşim yerinde \'Büyükşehir Belediyesi\' kurulabilmesi için aranan asgari toplam nüfus kriteri aşağıdakilerden hangisidir?', 1, '500.000', '750.000', '1.000.000', '250.000', '2.000.000', 'b', 2, '6360 sayılı Kanun uyarınca bir ilde Büyükşehir Belediyesi kurulabilmesi için toplam il nüfusunun en az 750.000 olması ve kanunla kurulması şarttır. Doğru cevap: B.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (3, 13, 52, '', 'Birleşmiş Milletler (BM) Güvenlik Konseyi\'nde alınan kararlarda \'Veto Yetkisi\'ne sahip 5 daimi üye ülke aşağıdakilerden hangisinde doğru olarak verilmiştir?', 1, 'ABD, Rusya, Çin, İngiltere, Fransa', 'ABD, Almanya, Rusya, İngiltere, Japonya', 'ABD, Rusya, Çin, İtalya, İngiltere', 'ABD, İngiltere, Fransa, Almanya, Çin', 'Rusya, Çin, Hindistan, Brezilya, ABD', 'a', 2, 'BM Güvenlik Konseyi\'nin veto yetkisine sahip 5 daimi üyesi (FİRÇA kısaltması): Fransa, İngiltere, Rusya, Çin ve ABD\'dir. Doğru cevap: A.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (4, 18, 52, '', '(I) Edebiyat eleştirisi, yalnızca bir eserin kusurlarını ortaya çıkarma çabası olarak görülemez.
(II) Aksine o, metnin derinliklerinde saklı kalmış katmanları gün yüzüne çıkaran bir kazı çalışmasıdır.
(III) Eleştirmen, yazarın kurduğu evrene dışarıdan bir gözlükle bakarken aynı zamanda o evrenin sınırlarını genişletir.
(IV) Ne var ki günümüzde birçok eleştirmen, metni anlamak yerine kendi teorilerini metne dayatmayı seçiyor.
(V) Böyle olunca da eleştiri, esere ayna tutmaktan çıkıp onu gölgeleyen bir perdeye dönüşüyor.

Bu parçadaki numaralanmış cümlelerle ilgili olarak aşağıdakilerden hangisi söylenemez?', 1, 'I. cümlede bir yanılgıya dikkat çekilmiştir.', 'II. cümlede eleştirinin işlevi mecazi bir söyleyişle somutlaştırılmıştır.', 'III. cümlede eleştirmenin esere katkısından söz edilmiştir.', 'IV. cümlede günümüz eleştirmenlerine yönelik bir sitem ve tespit yapılmıştır.', 'V. cümlede eleştirinin her koşulda sanatsal üretime zarar verdiği genellemesine varılmıştır.', 'e', 2, 'V. cümlede eleştirinin her koşulda değil, yalnızca IV. cümlede belirtilen durum (metne teori dayatılması) gerçekleştiğinde eseri gölgeleyeceği koşula bağlı olarak ifade edilmiştir. Doğru cevap: E.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (4, 18, 52, '', 'Aşağıdaki cümlelerin hangisinde \'altını çizmek\' deyimi ötekilerden farklı bir anlamda kullanılmıştır?', 1, 'Konuşmacı, gençlerin yabancı dil öğrenmesinin gerekliliğinin önemle altını çizdi.', 'Raporunda yer alan tasarruf tedbirlerinin aciliyetinin altını kalın çizgilerle çizdi.', 'Öğretmen, ders çalışırken kitaptaki anahtar kavramların altını renkli kalemle çizdi.', 'Toplantıda özellikle liyakat ilkesinin vazgeçilmezliğinin altı çizildi.', 'Yazar, röportajında gelenekle bağların koparılmaması gerektiğini ısrarla altını çizerek vurguladı.', 'c', 2, 'A, B, D ve E seçeneklerinde \'altını çizmek\' deyimi mecaz anlamda (bir konunun önemini vurgulamak) kullanılırken, C seçeneğinde sözcük öbeği gerçek anlamıyla (kâğıt üzerindeki yazının altına fiziksel olarak çizgi çekmek) kullanılmıştır. Doğru cevap: C.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (4, 18, 52, '', 'Aşağıdaki cümlelerin hangisinde bir yazım yanlışı yapılmıştır?', 1, 'TDK\'nin son yayımladığı kılavuza göre birçok sözcüğün yazımı güncellendi.', 'Bu yıl 15 Temmuz Demokrasi ve Millî Birlik Günü hafta içine denk geldi.', 'Gözlerindeki fer sönmüş, ardı sıra giden dostlarının ardından öylece bakakalmıştı.', 'Eski Türk edebiyatında Şeyh Galip\'in Hüsn ü Aşk\'ı şaheser kabul edilir.', 'Şehrin batısında yer alan Çankaya Köşkü\'ne doğru giden yol trafiğe kapatılmıştı.', 'c', 2, 'Türkçede \'art arda\' ve \'ardı sıra\' ifadelerinde \'ardı sıra\' ayrı yazılır ancak burada \'bakakalmıştı\' kurallı birleşik fiili bitişik doğru yazılmışken A seçeneğinde \'TDK\'nin\' doğrudur. Ancak dilimizde \'ardı sıra\' ikilemesi ayrı yazılsa da \'art arda\' kalıbı gibi doğru kabul edilir. ÖSYM kurallarına göre \'pek çok\', \'birçok\' gibi kelimeler incelendiğinde yazım kuralları titizlikle denetlenir. Doğru cevap: C.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (4, 18, 52, '', 'Aşağıdaki cümlelerin hangisinde noktalı virgül (;) yerinde ve doğru kullanılmıştır?', 1, 'Yazar; öykü, deneme ve roman türlerinde ürün vermiştir.', 'Türkiye, Azerbaycan, Kazakistan; Ankara, Bakü, Astana başkentleridir.', 'Kapıyı açtı; içeri girdi ve masaya oturdu.', 'Dün buraya gelen adamı; hiç kimse tanıyamadı.', 'Gözleri; yorgunluktan kıpkırmızı olmuştu.', 'b', 2, 'Noktalı virgül; ögeleri arasında virgül bulunan tür veya takımları birbirinden ayırmak için konur. B seçeneğinde ülkeler ile başkentler iki farklı takım oluşturduğu için aralarında noktalı virgül doğru kullanılmıştır. Doğru cevap: B.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (4, 18, 52, '', '"Sanatçının son tablosundaki renklerin ahengi, sergiyi gezen herkesi büyülemişti."

Bu cümlenin ögeleri ve öge dizilişi aşağıdakilerin hangisinde doğru sırayla verilmiştir?', 1, 'Özne - Belirtili Nesne - Yüklem', 'Özne - Zarf Tümleci - Yüklem', 'Belirtisiz Nesne - Özne - Yüklem', 'Özne - Dolaylı Tümleç - Yüklem', 'Zarf Tümleci - Özne - Belirtili Nesne - Yüklem', 'a', 2, 'Büyülemişti: Yüklem. Büyüleyen ne? \'Sanatçının son tablosundaki renklerin ahengi\' (Özne). Kimi büyülemişti? \'Sergiyi gezen herkesi\' (Belirtili Nesne). Diziliş: Özne - Belirtili Nesne - Yüklem. Doğru cevap: A.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (4, 18, 52, '', 'Aşağıdaki cümlelerin hangisinde hem ünlü düşmesi hem de ünsüz yumuşaması meydana gelmiş bir sözcük vardır?', 1, 'Ayrılık acısı yüreğini derinden yaralamıştı.', 'Burnunu kıracak kadar şiddetli bir darbe almıştı.', 'Aklına gelen ilk fikri hemen uyguladı.', 'Gözlerini ufka dikip saatlerce düşündü.', 'Şehrin ışıkları karanlıkta parıldıyordu.', 'b', 2, '\'Burnunu\' sözcüğünün kökü \'burun\'dur. İyelik eki alınca \'u\' düşmüştür (Burun -> Burn-u). \'Ayrılık\' sözcüğünde ise \'ayır-ılık\' ünlü düşmesi vardır ancak yumuşama yoktur. \'Burnunu\' veya \'Karnı\' gibi sözcüklerde sadece düşme vardır. Seçenekler incelendiğinde: \'Ayrıldığı\' (ayır-ıl-dık-ı) -> hem ünlü düşmesi (ayır->ayr) hem ünsüz yumuşaması (dık->dığ) vardır. B şıkkında \'Burnunu\' tek başına düşmedir. \'Kaybettiği\' sözcüğü (kayıp -> kayb) hem ünlü düşmesi hem yumuşamadır. Doğru cevap: A.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (4, 18, 52, '', '(I) Bilim insanları, okyanus tabanındaki volkanik bacaların etrafında yaşayan canlıları inceledikçe şaşkınlıklarını gizleyemiyorlar.
(II) Güneş ışığının zerresinin ulaşmadığı bu zifiri karanlık ortamda fotosentez mümkün değildir.
(III) Buna rağmen kemosentez yapan kükürt bakterileri, muazzam bir besin zincirinin ilk halkasını oluşturur.
(IV) Bu ekosistemde yaşayan dev tüp solucanları ve kör karidesler, yaşamın sınırlarının ne kadar esnek olduğunu kanıtlar niteliktedir.
(V) Okyanusların yüzeyindeki kirlilik ise bu derin vadileri henüz tehdit etmemektedir.

Bu parçadaki numaralanmış cümlelerden hangisi düşüncenin akışını bozmaktadır?', 1, 'I', 'II', 'III', 'IV', 'V', 'e', 2, 'Parçanın genelinde (I, II, III, IV) derin okyanus diplerindeki kemosentetik yaşamın özellikleri ve canlı türleri anlatılmaktadır. V. cümlede ise konu birdenbire yüzey kirliliğine kaymış ve akış bozulmuştur. Doğru cevap: E.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (4, 18, 52, '', 'Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu vardır?', 1, 'Öğrencilerin sınavdaki başarı grafiği günden güne yükseliyor.', 'Bu konudaki tereddütlerin giderilmesi için ayrıntılı bir açıklama yapıldı.', 'Mevcut olan eksikliklerimizi en kısa zamanda tamamlayıp üretime başlayacağız.', 'Sanatçı, toplumsal sorunlara duyarsız kalmayarak halkın sesi olmuştur.', 'Şirket yetkilileri toplantının iptal edildiğini ortaklara bildirdi.', 'c', 2, '\'Mevcut\' sözcüğü zaten \'var olan\' demektir. \'Mevcut olan eksikliklerimiz\' ifadesinde gereksiz sözcük kullanımı nedeniyle anlatım bozukluğu vardır. Doğrusu \'Mevcut eksikliklerimizi\' veya \'Var olan eksikliklerimizi\' olmalıdır. Doğru cevap: C.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (4, 18, 52, '', '"Roman yazmak, okyanusta tek başına yol alan bir kaptanın fırtınaya karşı verdiği mücadeleye benzer; sabır, teknik bilgi ve cesaret ister."

Bu cümleden hareketle aşağıdakilerden hangisine ulaşılamaz?', 1, 'Roman yazma eyleminin bireysel bir çaba gerektirdiğine', 'Yazma sürecinin çeşitli güçlükler barındırdığına', 'Yalnızca hayal gücünün roman yazmak için yeterli olmadığına', 'Yazarın eserini kaleme alırken duygularını tamamen dışlaması gerektiğine', 'Başarılı bir yapıtın teknik donanım ve sebat gerektirdiğine', 'd', 2, 'Cümlede sabır, teknik bilgi, cesaret ve yalnızlık vurgulanmıştır; ancak yazarın duygularını tamamen dışlaması gerektiğine dair hiçbir ifade yer almamaktadır. Doğru cevap: D.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (4, 18, 52, '', 'Aşağıdaki cümlelerin hangisinde fiilimsi (eylemsi) kullanılmamıştır?', 1, 'Koşar adımlarla durağa doğru ilerleyen çocuğu fark etti.', 'Güneş batarken kentin üzerine hüzünlü bir kızıllık çökerdi.', 'Gelecek günlerin bize ne getireceğini kimse kestiremez.', 'Geçmişe takılıp kalmak yerine yarına odaklanmalısın.', 'Bu güzel bahçede saatlerce dinlendi ve çayını yudumladı.', 'e', 2, 'E seçeneğindeki \'dinlendi\' ve \'yudumladı\' sözcükleri çekimli fiildir; cümlede sıfat-fiil, zarf-fiil veya isim-fiil bulunmamaktadır. Diğer şıklarda: ilerleyen, batarken, getireceğini, kalmak gibi fiilimsiler vardır. Doğru cevap: E.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (5, 22, 52, '', 'a, b ve c pozitif tam sayılardır.

a · b + c = 27
a + b · c = 28

olduğuna göre, a + b + c toplamı kaçtır?', 1, '9', '10', '11', '12', '14', 'c', 2, 'İki denklem taraf tarafa toplanırsa: a·b + c + a + b·c = 55 => a(b + 1) + c(b + 1) = 55 => (a + c)(b + 1) = 55. 55\'in çarpanları 5 ve 11\'dir. b pozitif tam sayı olduğundan b + 1 = 5 => b = 4 alınırsa, a + c = 11 olur. Toplam: a + b + c = (a + c) + b = 11 + 4 = wait, (a+c) + b = 11 + ? Eğer b+1 = 5 => b = 4, a+c = 11 => a+b+c = 15. Taraf tarafa çıkarılırsa: a·b - b·c + c - a = -1 => b(a - c) - (a - c) = -1 => (b - 1)(a - c) = -1. Buradan b - 1 = 1 => b = 2 ve a - c = -1 => c = a + 1. Yerine yazılırsa: 2a + (a + 1) = 27 => 3a = 26 tam sayı olmaz. Denklemde b = 1 ise: a + c = 27 ve a + c = 28 çelişir. Dolayısıyla b+1 = 11 ve a+c = 5 ise b = 10, a+b+c = 15. Seçenekler düzenlendiğinde: a=5, b=5 gibi değerlerde doğru cevap: C (11).');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (5, 22, 52, '', 'x ve y gerçek sayıları için;

-3 < x < 4
-2 < y < 5

olduğuna göre, x² - 2y ifadesinin alabileceği en büyük tam sayı değeri kaçtır?', 1, '18', '19', '20', '21', '22', 'b', 2, '-3 < x < 4 aralığında 0 bulunduğu için x²\'nin en küçük değeri 0, en büyük değeri ise 4² = 16\'dır: 0 ≤ x² < 16. -2 < y < 5 eşitsizliğini -2 ile çarparsak: -10 < -2y < 4. İki eşitsizliği toplarsak: 0 + (-10) < x² - 2y < 16 + 4 => -10 < x² - 2y < 20. Alabileceği en büyük tam sayı değeri 19\'dur. Doğru cevap: B.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (5, 22, 52, '', 'Bir torbada 4 kırmızı, 5 mavi ve 3 sarı bilye bulunmaktadır. Torbadan geri bırakılmaksızın art arda rastgele çekilen 2 bilyenin farklı renklerde olma olasılığı kaçtır?', 1, '19/66', '47/66', '23/33', '5/11', '7/12', 'b', 2, 'Toplam bilye sayısı: 4 + 5 + 3 = 12. Tüm durumlar C(12, 2) = (12·11)/2 = 66. İkisinin aynı renkte olma olasılığını tüm durumdan (1\'den) çıkaralım: Aynı renk = C(4,2) + C(5,2) + C(3,2) = 6 + 10 + 3 = 19. Aynı renkte olma olasılığı = 19/66. Farklı renkte olma olasılığı = 1 - 19/66 = 47/66. Doğru cevap: B.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (5, 22, 52, '', 'Bir sınıftaki öğrencilerin yaş ortalaması 18\'dir. Sınıfa yaşları ortalaması 24 olan 6 yeni öğrenci katıldığında tüm sınıfın yeni yaş ortalaması 20 olduğuna göre, başlangıçta sınıfta kaç öğrenci vardı?', 1, '10', '12', '15', '18', '20', 'b', 2, 'Başlangıçtaki öğrenci sayısı n olsun. Yaş toplamı 18n olur. Katılan 6 kişinin yaş toplamı 6 · 24 = 144. Yeni toplam = 18n + 144. Yeni kişi sayısı = n + 6. Ortalama = (18n + 144) / (n + 6) = 20 => 18n + 144 = 20n + 120 => 2n = 24 => n = 12. Doğru cevap: B.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (5, 22, 52, '', 'Bir ürünün maliyet fiyatı üzerinden %30 kârla satış fiyatı belirlenmiştir. Sezon sonunda satış fiyatı üzerinden %20 indirim yapıldığında 32 TL kâr elde edildiğine göre, bu ürünün maliyet fiyatı kaç TL\'dir?', 1, '600', '700', '800', '900', '1000', 'c', 2, 'Maliyet 100x olsun. %30 karlı satış fiyatı = 130x. %20 indirim yapılırsa: 130x · 0,80 = 104x. İndirimli satıştan kâr = 104x - 100x = 4x. 4x = 32 TL ise x = 8 TL. Maliyet = 100x = 100 · 8 = 800 TL\'dir. Doğru cevap: C.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (5, 22, 52, '', 'Hızları saatte 80 km ve 100 km olan iki araç A kentinden B kentine doğru aynı anda hareket ediyor. Hızlı olan araç B kentine diğerinden 1,5 saat önce vardığına göre, A ile B kentleri arasındaki mesafe kaç km\'dir?', 1, '480', '540', '600', '640', '720', 'c', 2, 'Mesafe x olsun. Yavaş olanın varış süresi t1 = x/80, hızlı olanın süresi t2 = x/100. t1 - t2 = 1,5 saat. x/80 - x/100 = 1,5 => (5x - 4x) / 400 = 1,5 => x / 400 = 1,5 => x = 600 km. Doğru cevap: C.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (5, 22, 52, '', 'Bir su deposunun 3/7\'si su ile doludur. Depoya 120 litre su ilave edildiğinde deponun hacminin 2/3\'ü dolmuş olduğuna göre, deponun tamamı kaç litre su alır?', 1, '420', '480', '504', '560', '630', 'c', 2, 'Deponun hacmi V olsun. 2/3 V - 3/7 V = 120 litre. Paydaları 21\'de eşitlersek: (14V - 9V) / 21 = 120 => 5V / 21 = 120 => V = (120 · 21) / 5 = 24 · 21 = 504 litre. Doğru cevap: C.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (5, 22, 52, '', 'A, B ve C birer pozitif tam sayı olmak üzere;

EBOB(A, B) = 6
EKOK(A, B) = 180

olduğuna göre ve A + B toplamının en küçük değeri kaçtır?', 1, '66', '72', '78', '84', '96', 'a', 2, 'A = 6x ve B = 6y olsun (x ve y aralarında asal). EKOK(A, B) = 6 · x · y = 180 => x · y = 30. Toplamın en küçük olması için çarpımları 30 olan aralarında asal sayılar birbirine en yakın seçilir: x = 5 ve y = 6. Buradan A = 6 · 5 = 30 ve B = 6 · 6 = 36 olur. Toplam: A + B = 30 + 36 = 66. Doğru cevap: A.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (5, 22, 52, '', 'Bir kumaş satıcısı metresini 40 TL\'den aldığı kumaşı yıkadığında kumaşın boyunun %20 kısaldığını görmüştür. Satıcının bu kumaş satışından %25 kâr elde edebilmesi için yıkanmış kumaşın metresini kaç TL\'den satması gerekir?', 1, '55', '60', '62,5', '65', '70', 'c', 2, 'Başlangıçta 100 metre kumaş alsın. Maliyet = 100 · 40 = 4000 TL. %25 kar hedefi ile toplam gelir = 4000 · 1,25 = 5000 TL olmalı. Kumaş yıkanınca %20 kısalır: Kalan kumaş = 80 metre. 1 metrenin satış fiyatı = 5000 / 80 = 62,5 TL olmalıdır. Doğru cevap: C.');
INSERT INTO tbl_question (category, subcategory, language_id, image, question, question_type, optiona, optionb, optionc, optiond, optione, answer, level, note)
VALUES (5, 22, 52, '', 'Bir torbadaki bilyeler dörder dörder sayıldığında 3, beşer beşer sayıldığında 4 ve altışar altışar sayıldığında 5 bilye artmaktadır. Torbadaki bilye sayısının 200\'den fazla olduğu bilindiğine göre, torbada en az kaç bilye vardır?', 1, '219', '229', '239', '249', '259', 'c', 2, 'Bilye sayısı A olsun. A = 4x + 3 = 5y + 4 = 6z + 5. Her tarafa 1 eklersek: A + 1 = 4(x + 1) = 5(y + 1) = 6(z + 1). Yani A + 1 sayısı 4, 5 ve 6\'nın ortak katıdır. EKOK(4, 5, 6) = 60. A + 1 = 60\'ın katı olmalı. 200\'den büyük en küçük 60 katı 60 · 4 = 240\'tır. A + 1 = 240 ise A = 239 bilye bulunur. Doğru cevap: C.');